/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The possible resource types used in UiTdatabank.
 * @export
 */
export const CommonItemType = {
    Event: 'event',
    Place: 'place',
    Organizer: 'organizer'
} as const;
export type CommonItemType = typeof CommonItemType[keyof typeof CommonItemType];


export function instanceOfCommonItemType(value: any): boolean {
    for (const key in CommonItemType) {
        if (Object.prototype.hasOwnProperty.call(CommonItemType, key)) {
            if (CommonItemType[key as keyof typeof CommonItemType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CommonItemTypeFromJSON(json: any): CommonItemType {
    return CommonItemTypeFromJSONTyped(json, false);
}

export function CommonItemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonItemType {
    return json as CommonItemType;
}

export function CommonItemTypeToJSON(value?: CommonItemType | null): any {
    return value as any;
}

export function CommonItemTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CommonItemType {
    return value as CommonItemType;
}

