/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventBookingInfo } from './EventBookingInfo';
import {
    EventBookingInfoFromJSON,
    EventBookingInfoFromJSONTyped,
    EventBookingInfoToJSON,
    EventBookingInfoToJSONTyped,
} from './EventBookingInfo';
import type { EventSubEventChildcare } from './EventSubEventChildcare';
import {
    EventSubEventChildcareFromJSON,
    EventSubEventChildcareFromJSONTyped,
    EventSubEventChildcareToJSON,
    EventSubEventChildcareToJSONTyped,
} from './EventSubEventChildcare';
import type { EventSubEventBookingAvailability } from './EventSubEventBookingAvailability';
import {
    EventSubEventBookingAvailabilityFromJSON,
    EventSubEventBookingAvailabilityFromJSONTyped,
    EventSubEventBookingAvailabilityToJSON,
    EventSubEventBookingAvailabilityToJSONTyped,
} from './EventSubEventBookingAvailability';
import type { EventStatus } from './EventStatus';
import {
    EventStatusFromJSON,
    EventStatusFromJSONTyped,
    EventStatusToJSON,
    EventStatusToJSONTyped,
} from './EventStatus';

/**
 * 
 * @export
 * @interface EventSubEventInner
 */
export interface EventSubEventInner {
    /**
     * Index of the subEvent on the parent event. `0` for the first subEvent, `1` for the second event, and so on.
     * @type {number}
     * @memberof EventSubEventInner
     */
    id?: number;
    /**
     * The date & time that the [event](./models/event.json) or [subEvent](./models/event-subEvent.json) starts, as an ISO-8601 date. For example `2021-05-17T22:00:00+00:00`.
     * 
     * Required on events when using one of the following calendarTypes:
     * 
     * - `single`
     * - `multiple`
     * - `periodic`
     * 
     * Always required on subEvents.
     * @type {Date}
     * @memberof EventSubEventInner
     */
    startDate: Date;
    /**
     * The date & time that the [event](./models/event.json) or [subEvent](./models/event-subEvent.json) ends, as an ISO-8601 date. For example `2021-05-17T22:00:00+00:00`.
     * 
     * Required on events when using one of the following calendarTypes:
     * 
     * - `single`
     * - `multiple`
     * - `periodic`
     * 
     * Always required on subEvents.
     * @type {Date}
     * @memberof EventSubEventInner
     */
    endDate: Date;
    /**
     * 
     * @type {EventSubEventChildcare}
     * @memberof EventSubEventInner
     */
    childcare?: EventSubEventChildcare;
    /**
     * 
     * @type {EventStatus}
     * @memberof EventSubEventInner
     */
    status?: EventStatus;
    /**
     * 
     * @type {EventSubEventBookingAvailability}
     * @memberof EventSubEventInner
     */
    bookingAvailability?: EventSubEventBookingAvailability | null;
    /**
     * 
     * @type {EventBookingInfo}
     * @memberof EventSubEventInner
     */
    bookingInfo?: EventBookingInfo;
    /**
     * Indicates whether this occurrence involves an overnight stay. Only present in the response when `true`. Only applicable when the event has a term with id `0.57.0.0.0` ("Kamp of vakantie").
     * @type {boolean}
     * @memberof EventSubEventInner
     */
    overnight?: boolean;
}

/**
 * Check if a given object implements the EventSubEventInner interface.
 */
export function instanceOfEventSubEventInner(value: object): value is EventSubEventInner {
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    return true;
}

export function EventSubEventInnerFromJSON(json: any): EventSubEventInner {
    return EventSubEventInnerFromJSONTyped(json, false);
}

export function EventSubEventInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventSubEventInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'childcare': json['childcare'] == null ? undefined : EventSubEventChildcareFromJSON(json['childcare']),
        'status': json['status'] == null ? undefined : EventStatusFromJSON(json['status']),
        'bookingAvailability': json['bookingAvailability'] == null ? undefined : EventSubEventBookingAvailabilityFromJSON(json['bookingAvailability']),
        'bookingInfo': json['bookingInfo'] == null ? undefined : EventBookingInfoFromJSON(json['bookingInfo']),
        'overnight': json['overnight'] == null ? undefined : json['overnight'],
    };
}

export function EventSubEventInnerToJSON(json: any): EventSubEventInner {
    return EventSubEventInnerToJSONTyped(json, false);
}

export function EventSubEventInnerToJSONTyped(value?: EventSubEventInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'startDate': value['startDate'].toISOString(),
        'endDate': value['endDate'].toISOString(),
        'childcare': EventSubEventChildcareToJSON(value['childcare']),
        'status': EventStatusToJSON(value['status']),
        'bookingAvailability': EventSubEventBookingAvailabilityToJSON(value['bookingAvailability']),
        'bookingInfo': EventBookingInfoToJSON(value['bookingInfo']),
        'overnight': value['overnight'],
    };
}

