/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventCalendarPut } from './EventCalendarPut';
import {
    EventCalendarPutFromJSON,
    EventCalendarPutFromJSONTyped,
    EventCalendarPutToJSON,
    EventCalendarPutToJSONTyped,
} from './EventCalendarPut';
import type { EventLocation } from './EventLocation';
import {
    EventLocationFromJSON,
    EventLocationFromJSONTyped,
    EventLocationToJSON,
    EventLocationToJSONTyped,
} from './EventLocation';
import type { EventMainLanguage } from './EventMainLanguage';
import {
    EventMainLanguageFromJSON,
    EventMainLanguageFromJSONTyped,
    EventMainLanguageToJSON,
    EventMainLanguageToJSONTyped,
} from './EventMainLanguage';
import type { EventPostDeprecatedType } from './EventPostDeprecatedType';
import {
    EventPostDeprecatedTypeFromJSON,
    EventPostDeprecatedTypeFromJSONTyped,
    EventPostDeprecatedTypeToJSON,
    EventPostDeprecatedTypeToJSONTyped,
} from './EventPostDeprecatedType';
import type { EventName } from './EventName';
import {
    EventNameFromJSON,
    EventNameFromJSONTyped,
    EventNameToJSON,
    EventNameToJSONTyped,
} from './EventName';

/**
 * 
 * @export
 * @interface EventPostDeprecated
 */
export interface EventPostDeprecated {
    /**
     * 
     * @type {EventMainLanguage}
     * @memberof EventPostDeprecated
     */
    mainLanguage: EventMainLanguage;
    /**
     * 
     * @type {EventName}
     * @memberof EventPostDeprecated
     */
    name: EventName;
    /**
     * 
     * @type {EventPostDeprecatedType}
     * @memberof EventPostDeprecated
     */
    type: EventPostDeprecatedType;
    /**
     * 
     * @type {EventLocation}
     * @memberof EventPostDeprecated
     */
    location: EventLocation;
    /**
     * Calendar info for the event.
     * @type {EventCalendarPut}
     * @memberof EventPostDeprecated
     */
    calendar: EventCalendarPut;
}



/**
 * Check if a given object implements the EventPostDeprecated interface.
 */
export function instanceOfEventPostDeprecated(value: object): value is EventPostDeprecated {
    if (!('mainLanguage' in value) || value['mainLanguage'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('calendar' in value) || value['calendar'] === undefined) return false;
    return true;
}

export function EventPostDeprecatedFromJSON(json: any): EventPostDeprecated {
    return EventPostDeprecatedFromJSONTyped(json, false);
}

export function EventPostDeprecatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventPostDeprecated {
    if (json == null) {
        return json;
    }
    return {
        
        'mainLanguage': EventMainLanguageFromJSON(json['mainLanguage']),
        'name': EventNameFromJSON(json['name']),
        'type': EventPostDeprecatedTypeFromJSON(json['type']),
        'location': EventLocationFromJSON(json['location']),
        'calendar': EventCalendarPutFromJSON(json['calendar']),
    };
}

export function EventPostDeprecatedToJSON(json: any): EventPostDeprecated {
    return EventPostDeprecatedToJSONTyped(json, false);
}

export function EventPostDeprecatedToJSONTyped(value?: EventPostDeprecated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mainLanguage': EventMainLanguageToJSON(value['mainLanguage']),
        'name': EventNameToJSON(value['name']),
        'type': EventPostDeprecatedTypeToJSON(value['type']),
        'location': EventLocationToJSON(value['location']),
        'calendar': EventCalendarPutToJSON(value['calendar']),
    };
}

