/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Call-to-action text to show for the link to the booking url. See [our suggested values](./entry-api/shared/booking-and-contact-info#urllabel).
 * @export
 * @interface EventBookingInfoUrlLabel
 */
export interface EventBookingInfoUrlLabel {
    /**
     * Dutch description
     * @type {string}
     * @memberof EventBookingInfoUrlLabel
     */
    nl?: string;
    /**
     * French description
     * @type {string}
     * @memberof EventBookingInfoUrlLabel
     */
    fr?: string;
    /**
     * German description
     * @type {string}
     * @memberof EventBookingInfoUrlLabel
     */
    de?: string;
    /**
     * English description
     * @type {string}
     * @memberof EventBookingInfoUrlLabel
     */
    en?: string;
}

/**
 * Check if a given object implements the EventBookingInfoUrlLabel interface.
 */
export function instanceOfEventBookingInfoUrlLabel(value: object): value is EventBookingInfoUrlLabel {
    return true;
}

export function EventBookingInfoUrlLabelFromJSON(json: any): EventBookingInfoUrlLabel {
    return EventBookingInfoUrlLabelFromJSONTyped(json, false);
}

export function EventBookingInfoUrlLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventBookingInfoUrlLabel {
    if (json == null) {
        return json;
    }
    return {
        
        'nl': json['nl'] == null ? undefined : json['nl'],
        'fr': json['fr'] == null ? undefined : json['fr'],
        'de': json['de'] == null ? undefined : json['de'],
        'en': json['en'] == null ? undefined : json['en'],
    };
}

export function EventBookingInfoUrlLabelToJSON(json: any): EventBookingInfoUrlLabel {
    return EventBookingInfoUrlLabelToJSONTyped(json, false);
}

export function EventBookingInfoUrlLabelToJSONTyped(value?: EventBookingInfoUrlLabel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nl': value['nl'],
        'fr': value['fr'],
        'de': value['de'],
        'en': value['en'],
    };
}

