/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The birthdate range of the attendees of the [event](./models/event.json).
 * @export
 * @interface EventBirthdateRange
 */
export interface EventBirthdateRange {
    /**
     * The earliest birthdate in the range, as an ISO-8601 date. For example `2021-01-31`.
     * @type {Date}
     * @memberof EventBirthdateRange
     */
    from: Date;
    /**
     * The latest birthdate in the range, as an ISO-8601 date. For example `2021-12-31`.
     * @type {Date}
     * @memberof EventBirthdateRange
     */
    to: Date;
}

/**
 * Check if a given object implements the EventBirthdateRange interface.
 */
export function instanceOfEventBirthdateRange(value: object): value is EventBirthdateRange {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function EventBirthdateRangeFromJSON(json: any): EventBirthdateRange {
    return EventBirthdateRangeFromJSONTyped(json, false);
}

export function EventBirthdateRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventBirthdateRange {
    if (json == null) {
        return json;
    }
    return {
        
        'from': (new Date(json['from'])),
        'to': (new Date(json['to'])),
    };
}

export function EventBirthdateRangeToJSON(json: any): EventBirthdateRange {
    return EventBirthdateRangeToJSONTyped(json, false);
}

export function EventBirthdateRangeToJSONTyped(value?: EventBirthdateRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'].toISOString().substring(0,10),
        'to': value['to'].toISOString().substring(0,10),
    };
}

