/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Organizer } from './Organizer';
import {
    OrganizerFromJSON,
    OrganizerFromJSONTyped,
    OrganizerToJSON,
    OrganizerToJSONTyped,
} from './Organizer';
import type { OrganizerGeo } from './OrganizerGeo';
import {
    OrganizerGeoFromJSON,
    OrganizerGeoFromJSONTyped,
    OrganizerGeoToJSON,
    OrganizerGeoToJSONTyped,
} from './OrganizerGeo';
import type { CommonAddressLocalized } from './CommonAddressLocalized';
import {
    CommonAddressLocalizedFromJSON,
    CommonAddressLocalizedFromJSONTyped,
    CommonAddressLocalizedToJSON,
    CommonAddressLocalizedToJSONTyped,
} from './CommonAddressLocalized';
import type { OrganizerContactInner } from './OrganizerContactInner';
import {
    OrganizerContactInnerFromJSON,
    OrganizerContactInnerFromJSONTyped,
    OrganizerContactInnerToJSON,
    OrganizerContactInnerToJSONTyped,
} from './OrganizerContactInner';
import type { OrganizerDescription } from './OrganizerDescription';
import {
    OrganizerDescriptionFromJSON,
    OrganizerDescriptionFromJSONTyped,
    OrganizerDescriptionToJSON,
    OrganizerDescriptionToJSONTyped,
} from './OrganizerDescription';
import type { OrganizerWorkflowStatus } from './OrganizerWorkflowStatus';
import {
    OrganizerWorkflowStatusFromJSON,
    OrganizerWorkflowStatusFromJSONTyped,
    OrganizerWorkflowStatusToJSON,
    OrganizerWorkflowStatusToJSONTyped,
} from './OrganizerWorkflowStatus';
import type { OrganizerContactPoint } from './OrganizerContactPoint';
import {
    OrganizerContactPointFromJSON,
    OrganizerContactPointFromJSONTyped,
    OrganizerContactPointToJSON,
    OrganizerContactPointToJSONTyped,
} from './OrganizerContactPoint';
import type { OrganizerEducationalDescription } from './OrganizerEducationalDescription';
import {
    OrganizerEducationalDescriptionFromJSON,
    OrganizerEducationalDescriptionFromJSONTyped,
    OrganizerEducationalDescriptionToJSON,
    OrganizerEducationalDescriptionToJSONTyped,
} from './OrganizerEducationalDescription';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
    ImageToJSONTyped,
} from './Image';
import type { OrganizerMainLanguage } from './OrganizerMainLanguage';
import {
    OrganizerMainLanguageFromJSON,
    OrganizerMainLanguageFromJSONTyped,
    OrganizerMainLanguageToJSON,
    OrganizerMainLanguageToJSONTyped,
} from './OrganizerMainLanguage';
import type { OrganizerPostDeprecated } from './OrganizerPostDeprecated';
import {
    OrganizerPostDeprecatedFromJSON,
    OrganizerPostDeprecatedFromJSONTyped,
    OrganizerPostDeprecatedToJSON,
    OrganizerPostDeprecatedToJSONTyped,
} from './OrganizerPostDeprecated';

/**
 * 
 * @export
 * @interface OrganizerPostRequest
 */
export interface OrganizerPostRequest {
    /**
     * A unique URI that acts as globally unique ID for the [organizer](./models/organizer.json). Based on [JSON-LD node identifiers](https://www.w3.org/TR/json-ld/#node-identifiers).
     * @type {string}
     * @memberof OrganizerPostRequest
     */
    id?: string;
    /**
     * 
     * @type {OrganizerMainLanguage}
     * @memberof OrganizerPostRequest
     */
    mainLanguage: OrganizerMainLanguage;
    /**
     * The unique website of the organizer.
     * @type {string}
     * @memberof OrganizerPostRequest
     */
    url: string;
    /**
     * The name of the organizer, localized in the language specified in the mainLanguage property.
     * @type {string}
     * @memberof OrganizerPostRequest
     */
    name: string;
    /**
     * 
     * @type {OrganizerDescription}
     * @memberof OrganizerPostRequest
     */
    description?: OrganizerDescription;
    /**
     * 
     * @type {OrganizerEducationalDescription}
     * @memberof OrganizerPostRequest
     */
    educationalDescription?: OrganizerEducationalDescription;
    /**
     * The address of the organizer, localized in the language specified in the mainLanguage property.
     * @type {CommonAddressLocalized}
     * @memberof OrganizerPostRequest
     */
    address?: CommonAddressLocalized;
    /**
     * 
     * @type {OrganizerGeo}
     * @memberof OrganizerPostRequest
     */
    geo?: OrganizerGeo;
    /**
     * 
     * @type {OrganizerContactPoint}
     * @memberof OrganizerPostRequest
     */
    contactPoint?: OrganizerContactPoint;
    /**
     * Describes an array of images that are linked to an [organizer](./models/organizer.json). The main image of the organizer will always be set to the first image in this list when creating/updating an organizer with multiple images.
     * @type {Array<Image>}
     * @memberof OrganizerPostRequest
     */
    images?: Array<Image>;
    /**
     * URL to the main image of the [organizer](./models/organizer.json). Will be automatically be set by UiTdatabank to the URL of the first image in `images`.
     * @type {string}
     * @memberof OrganizerPostRequest
     */
    readonly mainImage?: string;
    /**
     * One or more labels that categorize the [organizer](./models/organizer.json). Labels do not have a defined set of possible values or a hierarchy.
     * 
     * Labels are allowed to be visible for end users on publication channels.
     * 
     * Labels must match the `^(?=.{2,255}$)(?=.*\S.*\S.*)[^;]*$` pattern.
     * 
     * See [hiddenLabels](./models/organizer-hiddenLabels.json) for labels that should not be visible on publication channels.
     * @type {Array<string>}
     * @memberof OrganizerPostRequest
     */
    labels?: Array<string>;
    /**
     * Same as [labels](./models/organizer-labels.json), but for labels that should not be visible for end users on publication channels and should instead only be used for filtering or other processing.
     * 
     * Labels must match the `^(?=.{2,255}$)(?=.*\S.*\S.*)[^;]*$` pattern.
     * @type {Array<string>}
     * @memberof OrganizerPostRequest
     */
    hiddenLabels?: Array<string>;
    /**
     * Date formatted as an ISO-8601 datetime, added automatically by UiTdatabank based on the date & time the [organizer](./models/organizer.json) was created at.
     * 
     * For example `2021-05-17T22:00:00+00:00`.
     * @type {Date}
     * @memberof OrganizerPostRequest
     */
    readonly created?: Date;
    /**
     * 
     * @type {OrganizerWorkflowStatus}
     * @memberof OrganizerPostRequest
     */
    workflowStatus?: OrganizerWorkflowStatus;
    /**
     * List of languages that the [organizer](./models/organizer.json) is available in. (Not all localizable properties may contain every language though)
     * 
     * Added automatically by UiTdatabank based on the languages present in localized properties.
     * 
     * See also [completedLanguages](./models/organizer-completedLanguages.json).
     * @type {Array<OrganizerPostRequestLanguagesEnum>}
     * @memberof OrganizerPostRequest
     */
    readonly languages?: Array<OrganizerPostRequestLanguagesEnum>;
    /**
     * List of languages that _every_ localizable property on the [organizer](./models/organizer.json) is available in.
     * 
     * Added automatically by UiTdatabank based on the languages present in localized properties.
     * 
     * See also [languages](./models/organizer-languages.json).
     * @type {Array<OrganizerPostRequestCompletedLanguagesEnum>}
     * @memberof OrganizerPostRequest
     */
    readonly completedLanguages?: Array<OrganizerPostRequestCompletedLanguagesEnum>;
    /**
     * Date formatted as an ISO-8601 datetime, added automatically by UiTdatabank based on the date & time the [organizer](./models/organizer.json) was last modified.
     * 
     * For example `2021-05-17T22:00:00+00:00`.
     * @type {Date}
     * @memberof OrganizerPostRequest
     */
    readonly modified?: Date;
    /**
     * The unique identifier of the creator of the [organizer](./models/organizer.json). Usually a UUID, but can historally be an e-mail address.
     * 
     * Added automatically by UiTdatabank based on the authentication credentials used to create the organizer.
     * @type {string}
     * @memberof OrganizerPostRequest
     */
    readonly creator?: string;
    /**
     * List of contributors on an [organizer](./models/organizer.json). Only included if you request the organizer with an authenticated user who has the "Aanbod bewerken" permission on the organizer.  [Here is a detailed guide](./entry-api/shared/contributors) with more information.
     * @type {Array<string>}
     * @memberof OrganizerPostRequest
     */
    readonly contributors?: Array<string>;
    /**
     * The completeness score is a number between 0 and 100 that indicates how complete the information of an event, place or organizer is.
     * @type {number}
     * @memberof OrganizerPostRequest
     */
    readonly completeness?: number;
    /**
     * The unique website of the organizer.
     * @type {string}
     * @memberof OrganizerPostRequest
     */
    website: string;
    /**
     * Contact info of the [organizer](./models/organizer.json) in a legacy format, containing one or more phone numbers, email addresses and/or website URLs.
     * 
     * A type is used to categories the kind of contact information. The type can be either: url, email or phone.
     * @type {Array<OrganizerContactInner>}
     * @memberof OrganizerPostRequest
     */
    contact?: Array<OrganizerContactInner>;
}


/**
 * @export
 */
export const OrganizerPostRequestLanguagesEnum = {
    Nl: 'nl',
    Fr: 'fr',
    De: 'de',
    En: 'en'
} as const;
export type OrganizerPostRequestLanguagesEnum = typeof OrganizerPostRequestLanguagesEnum[keyof typeof OrganizerPostRequestLanguagesEnum];

/**
 * @export
 */
export const OrganizerPostRequestCompletedLanguagesEnum = {
    Nl: 'nl',
    Fr: 'fr',
    De: 'de',
    En: 'en'
} as const;
export type OrganizerPostRequestCompletedLanguagesEnum = typeof OrganizerPostRequestCompletedLanguagesEnum[keyof typeof OrganizerPostRequestCompletedLanguagesEnum];


/**
 * Check if a given object implements the OrganizerPostRequest interface.
 */
export function instanceOfOrganizerPostRequest(value: object): value is OrganizerPostRequest {
    if (!('mainLanguage' in value) || value['mainLanguage'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    return true;
}

export function OrganizerPostRequestFromJSON(json: any): OrganizerPostRequest {
    return OrganizerPostRequestFromJSONTyped(json, false);
}

export function OrganizerPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['@id'] == null ? undefined : json['@id'],
        'mainLanguage': OrganizerMainLanguageFromJSON(json['mainLanguage']),
        'url': json['url'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : OrganizerDescriptionFromJSON(json['description']),
        'educationalDescription': json['educationalDescription'] == null ? undefined : OrganizerEducationalDescriptionFromJSON(json['educationalDescription']),
        'address': json['address'] == null ? undefined : CommonAddressLocalizedFromJSON(json['address']),
        'geo': json['geo'] == null ? undefined : OrganizerGeoFromJSON(json['geo']),
        'contactPoint': json['contactPoint'] == null ? undefined : OrganizerContactPointFromJSON(json['contactPoint']),
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ImageFromJSON)),
        'mainImage': json['mainImage'] == null ? undefined : json['mainImage'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'hiddenLabels': json['hiddenLabels'] == null ? undefined : json['hiddenLabels'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'workflowStatus': json['workflowStatus'] == null ? undefined : OrganizerWorkflowStatusFromJSON(json['workflowStatus']),
        'languages': json['languages'] == null ? undefined : json['languages'],
        'completedLanguages': json['completedLanguages'] == null ? undefined : json['completedLanguages'],
        'modified': json['modified'] == null ? undefined : (new Date(json['modified'])),
        'creator': json['creator'] == null ? undefined : json['creator'],
        'contributors': json['contributors'] == null ? undefined : json['contributors'],
        'completeness': json['completeness'] == null ? undefined : json['completeness'],
        'website': json['website'],
        'contact': json['contact'] == null ? undefined : ((json['contact'] as Array<any>).map(OrganizerContactInnerFromJSON)),
    };
}

export function OrganizerPostRequestToJSON(json: any): OrganizerPostRequest {
    return OrganizerPostRequestToJSONTyped(json, false);
}

export function OrganizerPostRequestToJSONTyped(value?: Omit<OrganizerPostRequest, 'mainImage'|'created'|'languages'|'completedLanguages'|'modified'|'creator'|'contributors'|'completeness'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@id': value['id'],
        'mainLanguage': OrganizerMainLanguageToJSON(value['mainLanguage']),
        'url': value['url'],
        'name': value['name'],
        'description': OrganizerDescriptionToJSON(value['description']),
        'educationalDescription': OrganizerEducationalDescriptionToJSON(value['educationalDescription']),
        'address': CommonAddressLocalizedToJSON(value['address']),
        'geo': OrganizerGeoToJSON(value['geo']),
        'contactPoint': OrganizerContactPointToJSON(value['contactPoint']),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ImageToJSON)),
        'labels': value['labels'],
        'hiddenLabels': value['hiddenLabels'],
        'workflowStatus': OrganizerWorkflowStatusToJSON(value['workflowStatus']),
        'website': value['website'],
        'contact': value['contact'] == null ? undefined : ((value['contact'] as Array<any>).map(OrganizerContactInnerToJSON)),
    };
}

