/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizerEducationalDescriptionPut
 */
export interface OrganizerEducationalDescriptionPut {
    /**
     * New educational description of the organizer, localized in a single language.
     * @type {string}
     * @memberof OrganizerEducationalDescriptionPut
     */
    educationalDescription: string;
}

/**
 * Check if a given object implements the OrganizerEducationalDescriptionPut interface.
 */
export function instanceOfOrganizerEducationalDescriptionPut(value: object): value is OrganizerEducationalDescriptionPut {
    if (!('educationalDescription' in value) || value['educationalDescription'] === undefined) return false;
    return true;
}

export function OrganizerEducationalDescriptionPutFromJSON(json: any): OrganizerEducationalDescriptionPut {
    return OrganizerEducationalDescriptionPutFromJSONTyped(json, false);
}

export function OrganizerEducationalDescriptionPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerEducationalDescriptionPut {
    if (json == null) {
        return json;
    }
    return {
        
        'educationalDescription': json['educationalDescription'],
    };
}

export function OrganizerEducationalDescriptionPutToJSON(json: any): OrganizerEducationalDescriptionPut {
    return OrganizerEducationalDescriptionPutToJSONTyped(json, false);
}

export function OrganizerEducationalDescriptionPutToJSONTyped(value?: OrganizerEducationalDescriptionPut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'educationalDescription': value['educationalDescription'],
    };
}

