/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonItemType } from './CommonItemType';
import {
    CommonItemTypeFromJSON,
    CommonItemTypeFromJSONTyped,
    CommonItemTypeToJSON,
    CommonItemTypeToJSONTyped,
} from './CommonItemType';
import type { OwnershipState } from './OwnershipState';
import {
    OwnershipStateFromJSON,
    OwnershipStateFromJSONTyped,
    OwnershipStateToJSON,
    OwnershipStateToJSONTyped,
} from './OwnershipState';

/**
 * An ownership request between an owner and an item
 * @export
 * @interface Ownership
 */
export interface Ownership {
    /**
     * UUID
     * @type {string}
     * @memberof Ownership
     */
    id: string;
    /**
     * The unique id of a resource. For historical reasons, the last hyphen is sometimes missing.
     * @type {string}
     * @memberof Ownership
     */
    itemId: string;
    /**
     * 
     * @type {CommonItemType}
     * @memberof Ownership
     */
    itemType: CommonItemType;
    /**
     * The unique identifier of a user or API client.
     * @type {string}
     * @memberof Ownership
     */
    readonly ownerId: string;
    /**
     * Email address of the owner.
     * @type {string}
     * @memberof Ownership
     */
    readonly ownerEmail: string;
    /**
     * The unique identifier of a user or API client.
     * @type {string}
     * @memberof Ownership
     */
    readonly requesterId: string;
    /**
     * Email address of the requester.
     * @type {string}
     * @memberof Ownership
     */
    readonly requesterEmail: string;
    /**
     * 
     * @type {OwnershipState}
     * @memberof Ownership
     */
    state: OwnershipState;
    /**
     * Datetime in ISO-8601 format.
     * @type {Date}
     * @memberof Ownership
     */
    readonly created: Date;
    /**
     * Datetime in ISO-8601 format.
     * @type {Date}
     * @memberof Ownership
     */
    readonly modified: Date;
}



/**
 * Check if a given object implements the Ownership interface.
 */
export function instanceOfOwnership(value: object): value is Ownership {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('itemType' in value) || value['itemType'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('ownerEmail' in value) || value['ownerEmail'] === undefined) return false;
    if (!('requesterId' in value) || value['requesterId'] === undefined) return false;
    if (!('requesterEmail' in value) || value['requesterEmail'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('modified' in value) || value['modified'] === undefined) return false;
    return true;
}

export function OwnershipFromJSON(json: any): Ownership {
    return OwnershipFromJSONTyped(json, false);
}

export function OwnershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ownership {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'itemId': json['itemId'],
        'itemType': CommonItemTypeFromJSON(json['itemType']),
        'ownerId': json['ownerId'],
        'ownerEmail': json['ownerEmail'],
        'requesterId': json['requesterId'],
        'requesterEmail': json['requesterEmail'],
        'state': OwnershipStateFromJSON(json['state']),
        'created': (new Date(json['created'])),
        'modified': (new Date(json['modified'])),
    };
}

export function OwnershipToJSON(json: any): Ownership {
    return OwnershipToJSONTyped(json, false);
}

export function OwnershipToJSONTyped(value?: Omit<Ownership, 'ownerId'|'ownerEmail'|'requesterId'|'requesterEmail'|'created'|'modified'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'itemId': value['itemId'],
        'itemType': CommonItemTypeToJSON(value['itemType']),
        'state': OwnershipStateToJSON(value['state']),
    };
}

