/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonAddressLocalized } from './CommonAddressLocalized';
import {
    CommonAddressLocalizedFromJSON,
    CommonAddressLocalizedFromJSONTyped,
    CommonAddressLocalizedToJSON,
    CommonAddressLocalizedToJSONTyped,
} from './CommonAddressLocalized';

/**
 * The address the [place](./models/place.json) is located at. Localized because some parts like the municipality or street address can be different in Dutch, French, German and/or English.
 * 
 * Requires at least one locale, specifically the one defined in the [mainLanguage](./models/place-mainLanguage.json) of the place.
 * 
 * **Only add a localized version if it's an official variant!**
 * @export
 * @interface PlaceAddress
 */
export interface PlaceAddress {
    /**
     * An address in the `nl` (Dutch) language.
     * @type {CommonAddressLocalized}
     * @memberof PlaceAddress
     */
    nl?: CommonAddressLocalized;
    /**
     * An address in the `fr` (French) language.
     * @type {CommonAddressLocalized}
     * @memberof PlaceAddress
     */
    fr?: CommonAddressLocalized;
    /**
     * An address in the `de` (German) language.
     * @type {CommonAddressLocalized}
     * @memberof PlaceAddress
     */
    de?: CommonAddressLocalized;
    /**
     * An address in the `en` (English) language.
     * @type {CommonAddressLocalized}
     * @memberof PlaceAddress
     */
    en?: CommonAddressLocalized;
}

/**
 * Check if a given object implements the PlaceAddress interface.
 */
export function instanceOfPlaceAddress(value: object): value is PlaceAddress {
    return true;
}

export function PlaceAddressFromJSON(json: any): PlaceAddress {
    return PlaceAddressFromJSONTyped(json, false);
}

export function PlaceAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'nl': json['nl'] == null ? undefined : CommonAddressLocalizedFromJSON(json['nl']),
        'fr': json['fr'] == null ? undefined : CommonAddressLocalizedFromJSON(json['fr']),
        'de': json['de'] == null ? undefined : CommonAddressLocalizedFromJSON(json['de']),
        'en': json['en'] == null ? undefined : CommonAddressLocalizedFromJSON(json['en']),
    };
}

export function PlaceAddressToJSON(json: any): PlaceAddress {
    return PlaceAddressToJSONTyped(json, false);
}

export function PlaceAddressToJSONTyped(value?: PlaceAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nl': CommonAddressLocalizedToJSON(value['nl']),
        'fr': CommonAddressLocalizedToJSON(value['fr']),
        'de': CommonAddressLocalizedToJSON(value['de']),
        'en': CommonAddressLocalizedToJSON(value['en']),
    };
}

