/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A taxonomy term used to categorize places.
 * 
 * All places require exactly one term of the `eventtype` domain, and can optionally contain other terms.
 * 
 * When reading places, all properties will be available. When creating or updating places only the `id` is required to be included.
 * @export
 * @interface PlaceTermsInner
 */
export interface PlaceTermsInner {
    /**
     * Unique id of the term. For example `0.14.0.0.0`.
     * @type {string}
     * @memberof PlaceTermsInner
     */
    id: string;
    /**
     * Human-readable label of the term. Currently only available in Dutch. For example `Concert`.
     * @type {string}
     * @memberof PlaceTermsInner
     */
    label?: string;
    /**
     * The domain of the term. Can be one of `eventtype` or `facility`.
     * @type {PlaceTermsInnerDomainEnum}
     * @memberof PlaceTermsInner
     */
    domain?: PlaceTermsInnerDomainEnum;
}


/**
 * @export
 */
export const PlaceTermsInnerDomainEnum = {
    Facility: 'facility',
    Eventtype: 'eventtype'
} as const;
export type PlaceTermsInnerDomainEnum = typeof PlaceTermsInnerDomainEnum[keyof typeof PlaceTermsInnerDomainEnum];


/**
 * Check if a given object implements the PlaceTermsInner interface.
 */
export function instanceOfPlaceTermsInner(value: object): value is PlaceTermsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function PlaceTermsInnerFromJSON(json: any): PlaceTermsInner {
    return PlaceTermsInnerFromJSONTyped(json, false);
}

export function PlaceTermsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceTermsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'domain': json['domain'] == null ? undefined : json['domain'],
    };
}

export function PlaceTermsInnerToJSON(json: any): PlaceTermsInner {
    return PlaceTermsInnerToJSONTyped(json, false);
}

export function PlaceTermsInnerToJSONTyped(value?: PlaceTermsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'domain': value['domain'],
    };
}

