/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The human-readable, localized name of the [place](./models/place.json).
 * 
 * Requires at least one value, for the language specified in the [mainLanguage](./models/place-mainLanguage.json) property.
 * @export
 * @interface PlaceName
 */
export interface PlaceName {
    /**
     * A human-readable name in the `nl` (Dutch) language.
     * @type {string}
     * @memberof PlaceName
     */
    nl?: string;
    /**
     * A human-readable name in the `fr` (French) language.
     * @type {string}
     * @memberof PlaceName
     */
    fr?: string;
    /**
     * A human-readable name in the `de` (German) language.
     * @type {string}
     * @memberof PlaceName
     */
    de?: string;
    /**
     * A human-readable name in the `en` (English) language.
     * @type {string}
     * @memberof PlaceName
     */
    en?: string;
}

/**
 * Check if a given object implements the PlaceName interface.
 */
export function instanceOfPlaceName(value: object): value is PlaceName {
    return true;
}

export function PlaceNameFromJSON(json: any): PlaceName {
    return PlaceNameFromJSONTyped(json, false);
}

export function PlaceNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceName {
    if (json == null) {
        return json;
    }
    return {
        
        'nl': json['nl'] == null ? undefined : json['nl'],
        'fr': json['fr'] == null ? undefined : json['fr'],
        'de': json['de'] == null ? undefined : json['de'],
        'en': json['en'] == null ? undefined : json['en'],
    };
}

export function PlaceNameToJSON(json: any): PlaceName {
    return PlaceNameToJSONTyped(json, false);
}

export function PlaceNameToJSONTyped(value?: PlaceName | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nl': value['nl'],
        'fr': value['fr'],
        'de': value['de'],
        'en': value['en'],
    };
}

