/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DownloadLinkResponse,
    DownloadLinkResponseFromJSON,
    DownloadLinkResponseToJSON,
} from '../models/DownloadLinkResponse';
import {
    type EventCardSystem,
    EventCardSystemFromJSON,
    EventCardSystemToJSON,
} from '../models/EventCardSystem';
import {
    type EventSettings,
    EventSettingsFromJSON,
    EventSettingsToJSON,
} from '../models/EventSettings';

export interface GetEventsCardSystemsRequest {
    eventId: string;
}

export interface GetEventsQrCheckincodesDownloadlinkRequest {
    eventId: string;
    format?: GetEventsQrCheckincodesDownloadlinkFormatEnum;
}

export interface GetEventsSettingsRequest {
    eventId: string;
}

export interface PutEventsCardSystemsRequest {
    eventId: string;
    eventCardSystem?: Array<EventCardSystem>;
}

export interface PutEventsSettingsRequest {
    eventId: string;
    eventSettings?: EventSettings;
}

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getEventsCardSystems without sending the request
     */
    async getEventsCardSystemsRequestOpts(requestParameters: GetEventsCardSystemsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getEventsCardSystems().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/events/{eventId}/card-systems`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve social tariff settings specific for this card system and the given postal code.  This caller of this method, identified by client identification, client access token or user access token, does not require any permissions.
     * Get event card systems
     */
    async getEventsCardSystemsRaw(requestParameters: GetEventsCardSystemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EventCardSystem>>> {
        const requestOptions = await this.getEventsCardSystemsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EventCardSystemFromJSON));
    }

    /**
     * Retrieve social tariff settings specific for this card system and the given postal code.  This caller of this method, identified by client identification, client access token or user access token, does not require any permissions.
     * Get event card systems
     */
    async getEventsCardSystems(requestParameters: GetEventsCardSystemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EventCardSystem>> {
        const response = await this.getEventsCardSystemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEventsQrCheckincodesDownloadlink without sending the request
     */
    async getEventsQrCheckincodesDownloadlinkRequestOpts(requestParameters: GetEventsQrCheckincodesDownloadlinkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getEventsQrCheckincodesDownloadlink().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/events/{eventId}/qr-checkincodes/download-link`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a temporary download link to the QR checkin code of the given event.  This endpoint allows you to obtain a short-lived, hassle-free download link for your QR checkin code. After generation, this link remains active for a limited time, enabling direct QR downloads without the need for additional authentication. This is in particular convenient for applications that need to offer this link to users to start the download.   The caller of this request must have `EVENTS_QR_CHECKINCODE` permission for the organizer of this event. 
     * Get event QR checkin code as download link
     */
    async getEventsQrCheckincodesDownloadlinkRaw(requestParameters: GetEventsQrCheckincodesDownloadlinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DownloadLinkResponse>> {
        const requestOptions = await this.getEventsQrCheckincodesDownloadlinkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DownloadLinkResponseFromJSON(jsonValue));
    }

    /**
     * Get a temporary download link to the QR checkin code of the given event.  This endpoint allows you to obtain a short-lived, hassle-free download link for your QR checkin code. After generation, this link remains active for a limited time, enabling direct QR downloads without the need for additional authentication. This is in particular convenient for applications that need to offer this link to users to start the download.   The caller of this request must have `EVENTS_QR_CHECKINCODE` permission for the organizer of this event. 
     * Get event QR checkin code as download link
     */
    async getEventsQrCheckincodesDownloadlink(requestParameters: GetEventsQrCheckincodesDownloadlinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DownloadLinkResponse> {
        const response = await this.getEventsQrCheckincodesDownloadlinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEventsSettings without sending the request
     */
    async getEventsSettingsRequestOpts(requestParameters: GetEventsSettingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getEventsSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/events/{eventId}/settings`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get event settings of the given event.  The caller of this request must have `EVENT_SETTINGS_READ` permission for the organizer of this event. 
     * Get event settings
     */
    async getEventsSettingsRaw(requestParameters: GetEventsSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventSettings>> {
        const requestOptions = await this.getEventsSettingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventSettingsFromJSON(jsonValue));
    }

    /**
     * Get event settings of the given event.  The caller of this request must have `EVENT_SETTINGS_READ` permission for the organizer of this event. 
     * Get event settings
     */
    async getEventsSettings(requestParameters: GetEventsSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventSettings> {
        const response = await this.getEventsSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putEventsCardSystems without sending the request
     */
    async putEventsCardSystemsRequestOpts(requestParameters: PutEventsCardSystemsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling putEventsCardSystems().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/events/{eventId}/card-systems`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['eventCardSystem']!.map(EventCardSystemToJSON),
        };
    }

    /**
     * Update the `EventCardSystem` objects of the given event.  The `EventCardSystem` object specifies that the event is available in this specific card system and optionally what manual distribution keys are enabled.  This update is used to toggle the `enabled` state for specific card systems or distribution keys.  To update the `enabled` state for card systems or distribution keys, you typically retrieve the possible `EventCardSystem` objects first using  `GET /events/{eventId}/card-systems`. You can then reuse the response from the `GET` request,  altering the `enabled` state. Note that you can also omit the name properties.  Only the required fields are used in this update request.  However, in case you know the card system(s) and distribution key(s) in advance, you might also make this `PUT` request without prior `GET` e.g. in case you need to disable all card systems for an event, you can simply put an empty array `[]` to indicate that (missing card systems in the array will be treated the same way as card systems with `enabled: \"false\"`). Also note the implementation of this `PUT` endpoint is robust enough to allow updating card systems before the event is known in UiTPAS. (so even before the `GET` returns a valid HTTP 200 response).   <!-- theme: warning -->  > **This endpoint is only needed for exceptional cases.** In most cases card systems and distribution keys are set automatically on events, so you don\'t need to retrieve or change them.  The caller of this request must have `EVENTS_UPDATE` permission for the organizer of this event or the caller of this request must have \"Aanbod bewerken\" permission in the UiTdatabank for the given event. 
     * Update event card systems
     */
    async putEventsCardSystemsRaw(requestParameters: PutEventsCardSystemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.putEventsCardSystemsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update the `EventCardSystem` objects of the given event.  The `EventCardSystem` object specifies that the event is available in this specific card system and optionally what manual distribution keys are enabled.  This update is used to toggle the `enabled` state for specific card systems or distribution keys.  To update the `enabled` state for card systems or distribution keys, you typically retrieve the possible `EventCardSystem` objects first using  `GET /events/{eventId}/card-systems`. You can then reuse the response from the `GET` request,  altering the `enabled` state. Note that you can also omit the name properties.  Only the required fields are used in this update request.  However, in case you know the card system(s) and distribution key(s) in advance, you might also make this `PUT` request without prior `GET` e.g. in case you need to disable all card systems for an event, you can simply put an empty array `[]` to indicate that (missing card systems in the array will be treated the same way as card systems with `enabled: \"false\"`). Also note the implementation of this `PUT` endpoint is robust enough to allow updating card systems before the event is known in UiTPAS. (so even before the `GET` returns a valid HTTP 200 response).   <!-- theme: warning -->  > **This endpoint is only needed for exceptional cases.** In most cases card systems and distribution keys are set automatically on events, so you don\'t need to retrieve or change them.  The caller of this request must have `EVENTS_UPDATE` permission for the organizer of this event or the caller of this request must have \"Aanbod bewerken\" permission in the UiTdatabank for the given event. 
     * Update event card systems
     */
    async putEventsCardSystems(requestParameters: PutEventsCardSystemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putEventsCardSystemsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for putEventsSettings without sending the request
     */
    async putEventsSettingsRequestOpts(requestParameters: PutEventsSettingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling putEventsSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/events/{eventId}/settings`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EventSettingsToJSON(requestParameters['eventSettings']),
        };
    }

    /**
     * Update the event settings of the given event.  Make sure to perform a `GET events/{eventId}/settings` first, apply your changes and PUT the complete object using this request.  The caller of this request must have `EVENT_SETTINGS_UPDATE` permission for the organizer of this event. 
     * Update event settings
     */
    async putEventsSettingsRaw(requestParameters: PutEventsSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.putEventsSettingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update the event settings of the given event.  Make sure to perform a `GET events/{eventId}/settings` first, apply your changes and PUT the complete object using this request.  The caller of this request must have `EVENT_SETTINGS_UPDATE` permission for the organizer of this event. 
     * Update event settings
     */
    async putEventsSettings(requestParameters: PutEventsSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putEventsSettingsRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const GetEventsQrCheckincodesDownloadlinkFormatEnum = {
    Pdf: 'pdf',
    Zip: 'zip'
} as const;
export type GetEventsQrCheckincodesDownloadlinkFormatEnum = typeof GetEventsQrCheckincodesDownloadlinkFormatEnum[keyof typeof GetEventsQrCheckincodesDownloadlinkFormatEnum];
