/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Grouppass,
    GrouppassFromJSON,
    GrouppassToJSON,
} from '../models/Grouppass';
import {
    type GrouppassesPaginatedResponse,
    GrouppassesPaginatedResponseFromJSON,
    GrouppassesPaginatedResponseToJSON,
} from '../models/GrouppassesPaginatedResponse';

export interface GetGrouppassesRequest {
    uitpasNumber?: string;
    chipNumber?: string;
    start?: number;
    limit?: number;
    sortName?: GetGrouppassesSortNameEnum;
}

export interface GetGrouppassesPassholderIdRequest {
    passholderId: string;
}

/**
 * 
 */
export class GrouppassesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getGrouppasses without sending the request
     */
    async getGrouppassesRequestOpts(requestParameters: GetGrouppassesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['uitpasNumber'] != null) {
            queryParameters['uitpasNumber'] = requestParameters['uitpasNumber'];
        }

        if (requestParameters['chipNumber'] != null) {
            queryParameters['chipNumber'] = requestParameters['chipNumber'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['sortName'] != null) {
            queryParameters['sort[name]'] = requestParameters['sortName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/grouppasses`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve grouppasses based on search parameters.  **Note**: For now this endpoint requires either `uitpasNumber` or `chipNumber`, so this endpoint currently cannot be used to search _all_ grouppasses.  <!-- theme: warning -->  > **Important:** This endpoint might return `grouppass` entities for `BLOCKED` or `DELETED` cards. Clients using this endpoint MUST check `cardStatus` for `ACTIVE` cards before proceeding regular operations with this `grouppass`.  The caller of this request must have `EVENTS_READ` permission for the organizer of this event.  The caller of this request must have `GROUPPASSES_SEARCH` permission.
     * Search grouppasses
     */
    async getGrouppassesRaw(requestParameters: GetGrouppassesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GrouppassesPaginatedResponse>> {
        const requestOptions = await this.getGrouppassesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GrouppassesPaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve grouppasses based on search parameters.  **Note**: For now this endpoint requires either `uitpasNumber` or `chipNumber`, so this endpoint currently cannot be used to search _all_ grouppasses.  <!-- theme: warning -->  > **Important:** This endpoint might return `grouppass` entities for `BLOCKED` or `DELETED` cards. Clients using this endpoint MUST check `cardStatus` for `ACTIVE` cards before proceeding regular operations with this `grouppass`.  The caller of this request must have `EVENTS_READ` permission for the organizer of this event.  The caller of this request must have `GROUPPASSES_SEARCH` permission.
     * Search grouppasses
     */
    async getGrouppasses(requestParameters: GetGrouppassesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GrouppassesPaginatedResponse> {
        const response = await this.getGrouppassesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGrouppassesPassholderId without sending the request
     */
    async getGrouppassesPassholderIdRequestOpts(requestParameters: GetGrouppassesPassholderIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['passholderId'] == null) {
            throw new runtime.RequiredError(
                'passholderId',
                'Required parameter "passholderId" was null or undefined when calling getGrouppassesPassholderId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/grouppasses/{passholderId}`;
        urlPath = urlPath.replace('{passholderId}', encodeURIComponent(String(requestParameters['passholderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a grouppass by ID.  The caller of this request must have `GROUPPASSES_SEARCH` permission. 
     * Retrieve grouppass by ID
     */
    async getGrouppassesPassholderIdRaw(requestParameters: GetGrouppassesPassholderIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Grouppass>> {
        const requestOptions = await this.getGrouppassesPassholderIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GrouppassFromJSON(jsonValue));
    }

    /**
     * Retrieve a grouppass by ID.  The caller of this request must have `GROUPPASSES_SEARCH` permission. 
     * Retrieve grouppass by ID
     */
    async getGrouppassesPassholderId(requestParameters: GetGrouppassesPassholderIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Grouppass> {
        const response = await this.getGrouppassesPassholderIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetGrouppassesSortNameEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetGrouppassesSortNameEnum = typeof GetGrouppassesSortNameEnum[keyof typeof GetGrouppassesSortNameEnum];
