/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetRewardsIdRedeemStatus200Response,
    GetRewardsIdRedeemStatus200ResponseFromJSON,
    GetRewardsIdRedeemStatus200ResponseToJSON,
} from '../models/GetRewardsIdRedeemStatus200Response';
import {
    type PostRewardsRedeemedRequest,
    PostRewardsRedeemedRequestFromJSON,
    PostRewardsRedeemedRequestToJSON,
} from '../models/PostRewardsRedeemedRequest';
import {
    type RedeemedReward,
    RedeemedRewardFromJSON,
    RedeemedRewardToJSON,
} from '../models/RedeemedReward';
import {
    type RedeemedRewardsPaginatedResponse,
    RedeemedRewardsPaginatedResponseFromJSON,
    RedeemedRewardsPaginatedResponseToJSON,
} from '../models/RedeemedRewardsPaginatedResponse';
import {
    type Reward,
    RewardFromJSON,
    RewardToJSON,
} from '../models/Reward';
import {
    type RewardsPaginatedResponse,
    RewardsPaginatedResponseFromJSON,
    RewardsPaginatedResponseToJSON,
} from '../models/RewardsPaginatedResponse';

export interface DeleteRewardsRedeemedRedeemedRewardIdRequest {
    redeemedRewardId: string;
}

export interface GetRewardsRequest {
    start?: number;
    limit?: number;
    organizerId?: Array<string>;
    organizerPostalCode?: Array<string>;
    owningCardSystemId?: Array<string>;
    applicableCardSystemId?: Array<string>;
    type?: GetRewardsTypeEnum;
    text?: string;
    facets?: Array<GetRewardsFacetsEnum>;
    sort?: string;
    sortName?: GetRewardsSortNameEnum;
    sortCreationDate?: GetRewardsSortCreationDateEnum;
    sortRedeemCount?: GetRewardsSortRedeemCountEnum;
    sortFeatured?: GetRewardsSortFeaturedEnum;
    sortPoints?: GetRewardsSortPointsEnum;
    categories?: Array<GetRewardsCategoriesEnum>;
    pointsFrom?: number;
    pointsTo?: number;
    subset?: GetRewardsSubsetEnum;
    sport?: boolean;
    forKids?: boolean;
    featured?: boolean;
    online?: boolean;
    lastChance?: boolean;
    status?: GetRewardsStatusEnum;
    isRedeemableByPassholderId?: string;
    isInterestingForPassholderId?: string;
}

export interface GetRewardsIdRequest {
    rewardId: string;
}

export interface GetRewardsIdRedeemStatusRequest {
    rewardId: string;
    uitpasNumber: string;
}

export interface GetRewardsRedeemedRequest {
    uitpasNumber: string;
    rewardType?: GetRewardsRedeemedRewardTypeEnum;
    start?: number;
    limit?: number;
}

export interface PostRewardsRequest {
    reward?: Omit<Reward, 'id'|'status'|'unitsTaken'|'lastChance'>;
}

export interface PostRewardsRedeemedOperationRequest {
    postRewardsRedeemedRequest?: PostRewardsRedeemedRequest;
}

export interface PutRewardsIdRequest {
    rewardId: string;
    reward?: Omit<Reward, 'id'|'status'|'unitsTaken'|'lastChance'>;
}

/**
 * 
 */
export class RewardsApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteRewardsRedeemedRedeemedRewardId without sending the request
     */
    async deleteRewardsRedeemedRedeemedRewardIdRequestOpts(requestParameters: DeleteRewardsRedeemedRedeemedRewardIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['redeemedRewardId'] == null) {
            throw new runtime.RequiredError(
                'redeemedRewardId',
                'Required parameter "redeemedRewardId" was null or undefined when calling deleteRewardsRedeemedRedeemedRewardId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/rewards/redeemed/{redeemedRewardId}`;
        urlPath = urlPath.replace('{redeemedRewardId}', encodeURIComponent(String(requestParameters['redeemedRewardId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel a previously redeemed reward.  The caller of this request must have `REWARDS_REDEEM` permission for the organizer of the given reward.
     * Cancel a redeemed reward
     */
    async deleteRewardsRedeemedRedeemedRewardIdRaw(requestParameters: DeleteRewardsRedeemedRedeemedRewardIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteRewardsRedeemedRedeemedRewardIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancel a previously redeemed reward.  The caller of this request must have `REWARDS_REDEEM` permission for the organizer of the given reward.
     * Cancel a redeemed reward
     */
    async deleteRewardsRedeemedRedeemedRewardId(requestParameters: DeleteRewardsRedeemedRedeemedRewardIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteRewardsRedeemedRedeemedRewardIdRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getRewards without sending the request
     */
    async getRewardsRequestOpts(requestParameters: GetRewardsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['organizerId'] != null) {
            queryParameters['organizerId'] = requestParameters['organizerId'];
        }

        if (requestParameters['organizerPostalCode'] != null) {
            queryParameters['organizerPostalCode'] = requestParameters['organizerPostalCode'];
        }

        if (requestParameters['owningCardSystemId'] != null) {
            queryParameters['owningCardSystemId'] = requestParameters['owningCardSystemId'];
        }

        if (requestParameters['applicableCardSystemId'] != null) {
            queryParameters['applicableCardSystemId'] = requestParameters['applicableCardSystemId'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['text'] != null) {
            queryParameters['text'] = requestParameters['text'];
        }

        if (requestParameters['facets'] != null) {
            queryParameters['facets'] = requestParameters['facets'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['sortName'] != null) {
            queryParameters['sort[name]'] = requestParameters['sortName'];
        }

        if (requestParameters['sortCreationDate'] != null) {
            queryParameters['sort[creationDate]'] = requestParameters['sortCreationDate'];
        }

        if (requestParameters['sortRedeemCount'] != null) {
            queryParameters['sort[redeemCount]'] = requestParameters['sortRedeemCount'];
        }

        if (requestParameters['sortFeatured'] != null) {
            queryParameters['sort[featured]'] = requestParameters['sortFeatured'];
        }

        if (requestParameters['sortPoints'] != null) {
            queryParameters['sort[points]'] = requestParameters['sortPoints'];
        }

        if (requestParameters['categories'] != null) {
            queryParameters['categories'] = requestParameters['categories'];
        }

        if (requestParameters['pointsFrom'] != null) {
            queryParameters['pointsFrom'] = requestParameters['pointsFrom'];
        }

        if (requestParameters['pointsTo'] != null) {
            queryParameters['pointsTo'] = requestParameters['pointsTo'];
        }

        if (requestParameters['subset'] != null) {
            queryParameters['subset'] = requestParameters['subset'];
        }

        if (requestParameters['sport'] != null) {
            queryParameters['sport'] = requestParameters['sport'];
        }

        if (requestParameters['forKids'] != null) {
            queryParameters['forKids'] = requestParameters['forKids'];
        }

        if (requestParameters['featured'] != null) {
            queryParameters['featured'] = requestParameters['featured'];
        }

        if (requestParameters['online'] != null) {
            queryParameters['online'] = requestParameters['online'];
        }

        if (requestParameters['lastChance'] != null) {
            queryParameters['lastChance'] = requestParameters['lastChance'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['isRedeemableByPassholderId'] != null) {
            queryParameters['isRedeemableByPassholderId'] = requestParameters['isRedeemableByPassholderId'];
        }

        if (requestParameters['isInterestingForPassholderId'] != null) {
            queryParameters['isInterestingForPassholderId'] = requestParameters['isInterestingForPassholderId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-id"] = await this.configuration.apiKey("x-client-id"); // CLIENT_IDENTIFICATION authentication
        }


        let urlPath = `/rewards`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search rewards.  The caller of this request does not need special permissions permission except `REWARDS_PASSHOLDERS_READ` to use the `isRedeemableByPassholderId` and `isInterestingForPassholderId` query parameters.  This endpoint allows authentication with [client identification](/docs/authentication/ZG9jOjExODE5NDY5-client-identification), [client access tokens](/docs/authentication/ZG9jOjExODE5NDY4-client-access-token), and [user access tokens](/docs/authentication/ZG9jOjExODE5NTM5-user-access-token).
     * Search rewards
     */
    async getRewardsRaw(requestParameters: GetRewardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RewardsPaginatedResponse>> {
        const requestOptions = await this.getRewardsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardsPaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Search rewards.  The caller of this request does not need special permissions permission except `REWARDS_PASSHOLDERS_READ` to use the `isRedeemableByPassholderId` and `isInterestingForPassholderId` query parameters.  This endpoint allows authentication with [client identification](/docs/authentication/ZG9jOjExODE5NDY5-client-identification), [client access tokens](/docs/authentication/ZG9jOjExODE5NDY4-client-access-token), and [user access tokens](/docs/authentication/ZG9jOjExODE5NTM5-user-access-token).
     * Search rewards
     */
    async getRewards(requestParameters: GetRewardsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RewardsPaginatedResponse> {
        const response = await this.getRewardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRewardsId without sending the request
     */
    async getRewardsIdRequestOpts(requestParameters: GetRewardsIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['rewardId'] == null) {
            throw new runtime.RequiredError(
                'rewardId',
                'Required parameter "rewardId" was null or undefined when calling getRewardsId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/rewards/{rewardId}`;
        urlPath = urlPath.replace('{rewardId}', encodeURIComponent(String(requestParameters['rewardId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve reward by ID.  The caller of this request must have `REWARDS_READ` permission for the given organizer.
     * Retrieve reward
     */
    async getRewardsIdRaw(requestParameters: GetRewardsIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reward>> {
        const requestOptions = await this.getRewardsIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardFromJSON(jsonValue));
    }

    /**
     * Retrieve reward by ID.  The caller of this request must have `REWARDS_READ` permission for the given organizer.
     * Retrieve reward
     */
    async getRewardsId(requestParameters: GetRewardsIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reward> {
        const response = await this.getRewardsIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRewardsIdRedeemStatus without sending the request
     */
    async getRewardsIdRedeemStatusRequestOpts(requestParameters: GetRewardsIdRedeemStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['rewardId'] == null) {
            throw new runtime.RequiredError(
                'rewardId',
                'Required parameter "rewardId" was null or undefined when calling getRewardsIdRedeemStatus().'
            );
        }

        if (requestParameters['uitpasNumber'] == null) {
            throw new runtime.RequiredError(
                'uitpasNumber',
                'Required parameter "uitpasNumber" was null or undefined when calling getRewardsIdRedeemStatus().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['uitpasNumber'] != null) {
            queryParameters['uitpasNumber'] = requestParameters['uitpasNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/rewards/{rewardId}/redeem-status`;
        urlPath = urlPath.replace('{rewardId}', encodeURIComponent(String(requestParameters['rewardId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check the reward redeem status for a passholder.   The caller of this request must have `REWARDS_REDEEM` permission for the given organizer.
     * Check redeem status of a reward for a passholder
     */
    async getRewardsIdRedeemStatusRaw(requestParameters: GetRewardsIdRedeemStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetRewardsIdRedeemStatus200Response>> {
        const requestOptions = await this.getRewardsIdRedeemStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetRewardsIdRedeemStatus200ResponseFromJSON(jsonValue));
    }

    /**
     * Check the reward redeem status for a passholder.   The caller of this request must have `REWARDS_REDEEM` permission for the given organizer.
     * Check redeem status of a reward for a passholder
     */
    async getRewardsIdRedeemStatus(requestParameters: GetRewardsIdRedeemStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetRewardsIdRedeemStatus200Response> {
        const response = await this.getRewardsIdRedeemStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRewardsRedeemed without sending the request
     */
    async getRewardsRedeemedRequestOpts(requestParameters: GetRewardsRedeemedRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uitpasNumber'] == null) {
            throw new runtime.RequiredError(
                'uitpasNumber',
                'Required parameter "uitpasNumber" was null or undefined when calling getRewardsRedeemed().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['uitpasNumber'] != null) {
            queryParameters['uitpasNumber'] = requestParameters['uitpasNumber'];
        }

        if (requestParameters['rewardType'] != null) {
            queryParameters['rewardType'] = requestParameters['rewardType'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/rewards/redeemed`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve redeemed rewards for a passholder.  The caller of this request must have `REWARDS_READ` permission.
     * Retrieve redeemed rewards
     */
    async getRewardsRedeemedRaw(requestParameters: GetRewardsRedeemedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RedeemedRewardsPaginatedResponse>> {
        const requestOptions = await this.getRewardsRedeemedRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RedeemedRewardsPaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve redeemed rewards for a passholder.  The caller of this request must have `REWARDS_READ` permission.
     * Retrieve redeemed rewards
     */
    async getRewardsRedeemed(requestParameters: GetRewardsRedeemedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RedeemedRewardsPaginatedResponse> {
        const response = await this.getRewardsRedeemedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postRewards without sending the request
     */
    async postRewardsRequestOpts(requestParameters: PostRewardsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/rewards`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RewardToJSON(requestParameters['reward']),
        };
    }

    /**
     * Create a new reward.  The caller of this request must have `REWARDS_WRITE` permission for the given organizer.
     * Create new reward
     */
    async postRewardsRaw(requestParameters: PostRewardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reward>> {
        const requestOptions = await this.postRewardsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardFromJSON(jsonValue));
    }

    /**
     * Create a new reward.  The caller of this request must have `REWARDS_WRITE` permission for the given organizer.
     * Create new reward
     */
    async postRewards(requestParameters: PostRewardsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reward> {
        const response = await this.postRewardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postRewardsRedeemed without sending the request
     */
    async postRewardsRedeemedRequestOpts(requestParameters: PostRewardsRedeemedOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/rewards/redeemed`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostRewardsRedeemedRequestToJSON(requestParameters['postRewardsRedeemedRequest']),
        };
    }

    /**
     * Redeem reward.  The caller of this request must have `REWARDS_REDEEM` permission for the given organizer.
     * Redeem reward
     */
    async postRewardsRedeemedRaw(requestParameters: PostRewardsRedeemedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RedeemedReward>> {
        const requestOptions = await this.postRewardsRedeemedRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RedeemedRewardFromJSON(jsonValue));
    }

    /**
     * Redeem reward.  The caller of this request must have `REWARDS_REDEEM` permission for the given organizer.
     * Redeem reward
     */
    async postRewardsRedeemed(requestParameters: PostRewardsRedeemedOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RedeemedReward> {
        const response = await this.postRewardsRedeemedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putRewardsId without sending the request
     */
    async putRewardsIdRequestOpts(requestParameters: PutRewardsIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['rewardId'] == null) {
            throw new runtime.RequiredError(
                'rewardId',
                'Required parameter "rewardId" was null or undefined when calling putRewardsId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/rewards/{rewardId}`;
        urlPath = urlPath.replace('{rewardId}', encodeURIComponent(String(requestParameters['rewardId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RewardToJSON(requestParameters['reward']),
        };
    }

    /**
     * Update reward. To update a reward correctly, as a client you will typically `GET` the reward first,  make the required changes in the reward json and use this `PUT` request to persist those changes in UiTPAS.  Do note that the following fields are **not editable** after this reward is redeemed by (for POINTS rewards) or granted to (for WELCOME rewards) a passholder: * redeemPeriod.begin * grantingPeriod.begin * points  Attempts to edit such rewards will result in an HTTP 400 error with type `https://api.publiq.be/probs/uitpas/reward-not-editable`  The caller of this request must have `REWARDS_WRITE` permission for the given organizer.
     * Update reward
     */
    async putRewardsIdRaw(requestParameters: PutRewardsIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reward>> {
        const requestOptions = await this.putRewardsIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardFromJSON(jsonValue));
    }

    /**
     * Update reward. To update a reward correctly, as a client you will typically `GET` the reward first,  make the required changes in the reward json and use this `PUT` request to persist those changes in UiTPAS.  Do note that the following fields are **not editable** after this reward is redeemed by (for POINTS rewards) or granted to (for WELCOME rewards) a passholder: * redeemPeriod.begin * grantingPeriod.begin * points  Attempts to edit such rewards will result in an HTTP 400 error with type `https://api.publiq.be/probs/uitpas/reward-not-editable`  The caller of this request must have `REWARDS_WRITE` permission for the given organizer.
     * Update reward
     */
    async putRewardsId(requestParameters: PutRewardsIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reward> {
        const response = await this.putRewardsIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetRewardsTypeEnum = {
    Points: 'POINTS',
    Welcome: 'WELCOME',
    Any: 'ANY'
} as const;
export type GetRewardsTypeEnum = typeof GetRewardsTypeEnum[keyof typeof GetRewardsTypeEnum];
/**
 * @export
 */
export const GetRewardsFacetsEnum = {
    Categories: 'categories',
    ForKids: 'forKids',
    Sport: 'sport',
    Online: 'online',
    LastChance: 'lastChance',
    OwningCardSystemId: 'owningCardSystemId',
    Type: 'type'
} as const;
export type GetRewardsFacetsEnum = typeof GetRewardsFacetsEnum[keyof typeof GetRewardsFacetsEnum];
/**
 * @export
 */
export const GetRewardsSortNameEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetRewardsSortNameEnum = typeof GetRewardsSortNameEnum[keyof typeof GetRewardsSortNameEnum];
/**
 * @export
 */
export const GetRewardsSortCreationDateEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetRewardsSortCreationDateEnum = typeof GetRewardsSortCreationDateEnum[keyof typeof GetRewardsSortCreationDateEnum];
/**
 * @export
 */
export const GetRewardsSortRedeemCountEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetRewardsSortRedeemCountEnum = typeof GetRewardsSortRedeemCountEnum[keyof typeof GetRewardsSortRedeemCountEnum];
/**
 * @export
 */
export const GetRewardsSortFeaturedEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetRewardsSortFeaturedEnum = typeof GetRewardsSortFeaturedEnum[keyof typeof GetRewardsSortFeaturedEnum];
/**
 * @export
 */
export const GetRewardsSortPointsEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetRewardsSortPointsEnum = typeof GetRewardsSortPointsEnum[keyof typeof GetRewardsSortPointsEnum];
/**
 * @export
 */
export const GetRewardsCategoriesEnum = {
    GoedeDoel: 'Goede doel',
    EtenEnDrinken: 'Eten en drinken',
    Doen: 'Doen',
    GadgetOfItem: 'Gadget of item'
} as const;
export type GetRewardsCategoriesEnum = typeof GetRewardsCategoriesEnum[keyof typeof GetRewardsCategoriesEnum];
/**
 * @export
 */
export const GetRewardsSubsetEnum = {
    All: 'ALL',
    Endusers: 'ENDUSERS',
    Redeemable: 'REDEEMABLE',
    RedeemableFuture: 'REDEEMABLE-FUTURE',
    EnduserFuture: 'ENDUSER-FUTURE'
} as const;
export type GetRewardsSubsetEnum = typeof GetRewardsSubsetEnum[keyof typeof GetRewardsSubsetEnum];
/**
 * @export
 */
export const GetRewardsStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE',
    Deleted: 'DELETED'
} as const;
export type GetRewardsStatusEnum = typeof GetRewardsStatusEnum[keyof typeof GetRewardsStatusEnum];
/**
 * @export
 */
export const GetRewardsRedeemedRewardTypeEnum = {
    Points: 'POINTS',
    Welcome: 'WELCOME'
} as const;
export type GetRewardsRedeemedRewardTypeEnum = typeof GetRewardsRedeemedRewardTypeEnum[keyof typeof GetRewardsRedeemedRewardTypeEnum];
