/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Organizer,
    OrganizerFromJSON,
    OrganizerToJSON,
} from '../models/Organizer';

export interface DeletePassholdersSchoolRequest {
    passholderId: string;
}

export interface GetPassholdersSchoolRequest {
    passholderId: string;
}

export interface PutPassholdersSchoolRequest {
    passholderId: string;
    organizer?: Organizer;
}

/**
 * 
 */
export class SchoolsApi extends runtime.BaseAPI {

    /**
     * Creates request options for deletePassholdersSchool without sending the request
     */
    async deletePassholdersSchoolRequestOpts(requestParameters: DeletePassholdersSchoolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['passholderId'] == null) {
            throw new runtime.RequiredError(
                'passholderId',
                'Required parameter "passholderId" was null or undefined when calling deletePassholdersSchool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/passholders/{passholderId}/school`;
        urlPath = urlPath.replace('{passholderId}', encodeURIComponent(String(requestParameters['passholderId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete the passholder\'s school relation.  The user or client performing this request must have `PASSHOLDERS_UPDATE` permission.  <!-- theme: warning -->  > Passholder schools are used to manage passholders in a very specific case. If you are not explicitly working with UiTPAS schools, you will probably **NOT** need this API.   Using [GET](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/get), [PUT](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/put) and [DELETE](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/delete) on this endpoint, the school of a passholder can be retrieved, updated and deleted. All schools are organizers.
     * Delete passholder school
     */
    async deletePassholdersSchoolRaw(requestParameters: DeletePassholdersSchoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deletePassholdersSchoolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete the passholder\'s school relation.  The user or client performing this request must have `PASSHOLDERS_UPDATE` permission.  <!-- theme: warning -->  > Passholder schools are used to manage passholders in a very specific case. If you are not explicitly working with UiTPAS schools, you will probably **NOT** need this API.   Using [GET](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/get), [PUT](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/put) and [DELETE](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/delete) on this endpoint, the school of a passholder can be retrieved, updated and deleted. All schools are organizers.
     * Delete passholder school
     */
    async deletePassholdersSchool(requestParameters: DeletePassholdersSchoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePassholdersSchoolRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getPassholdersSchool without sending the request
     */
    async getPassholdersSchoolRequestOpts(requestParameters: GetPassholdersSchoolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['passholderId'] == null) {
            throw new runtime.RequiredError(
                'passholderId',
                'Required parameter "passholderId" was null or undefined when calling getPassholdersSchool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/passholders/{passholderId}/school`;
        urlPath = urlPath.replace('{passholderId}', encodeURIComponent(String(requestParameters['passholderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve the passholder\'s school.  The caller of this request must have `PASSHOLDERS_SEARCH` permission.  <!-- theme: warning -->  > Passholder schools are used to manage passholders in a very specific case. If you are not explicitly working with UiTPAS schools, you will probably **NOT** need this API.   Using [GET](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/get), [PUT](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/put) and [DELETE](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/delete) on this endpoint, the school of a passholder can be retrieved, updated and deleted. All schools are organizers.
     * Get passholder school
     */
    async getPassholdersSchoolRaw(requestParameters: GetPassholdersSchoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organizer>> {
        const requestOptions = await this.getPassholdersSchoolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizerFromJSON(jsonValue));
    }

    /**
     * Retrieve the passholder\'s school.  The caller of this request must have `PASSHOLDERS_SEARCH` permission.  <!-- theme: warning -->  > Passholder schools are used to manage passholders in a very specific case. If you are not explicitly working with UiTPAS schools, you will probably **NOT** need this API.   Using [GET](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/get), [PUT](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/put) and [DELETE](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/delete) on this endpoint, the school of a passholder can be retrieved, updated and deleted. All schools are organizers.
     * Get passholder school
     */
    async getPassholdersSchool(requestParameters: GetPassholdersSchoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organizer> {
        const response = await this.getPassholdersSchoolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putPassholdersSchool without sending the request
     */
    async putPassholdersSchoolRequestOpts(requestParameters: PutPassholdersSchoolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['passholderId'] == null) {
            throw new runtime.RequiredError(
                'passholderId',
                'Required parameter "passholderId" was null or undefined when calling putPassholdersSchool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/passholders/{passholderId}/school`;
        urlPath = urlPath.replace('{passholderId}', encodeURIComponent(String(requestParameters['passholderId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OrganizerToJSON(requestParameters['organizer']),
        };
    }

    /**
     * Update the passholder\'s school relation.  The caller of this request must have `PASSHOLDERS_UPDATE` permission.  <!-- theme: warning -->  > Passholder schools are used to manage passholders in a very specific case. If you are not explicitly working with UiTPAS schools, you will probably **NOT** need this API.   Using [GET](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/get), [PUT](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/put) and [DELETE](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/delete) on this endpoint, the school of a passholder can be retrieved, updated and deleted. All schools are organizers.
     * Update passholder school
     */
    async putPassholdersSchoolRaw(requestParameters: PutPassholdersSchoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.putPassholdersSchoolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update the passholder\'s school relation.  The caller of this request must have `PASSHOLDERS_UPDATE` permission.  <!-- theme: warning -->  > Passholder schools are used to manage passholders in a very specific case. If you are not explicitly working with UiTPAS schools, you will probably **NOT** need this API.   Using [GET](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/get), [PUT](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/put) and [DELETE](/reference/uitpas.json/paths/~1passholders~1{passholderId}~1school/delete) on this endpoint, the school of a passholder can be retrieved, updated and deleted. All schools are organizers.
     * Update passholder school
     */
    async putPassholdersSchool(requestParameters: PutPassholdersSchoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putPassholdersSchoolRaw(requestParameters, initOverrides);
    }

}
