/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type TariffsResponse,
    TariffsResponseFromJSON,
    TariffsResponseToJSON,
} from '../models/TariffsResponse';
import {
    type TicketSale,
    TicketSaleFromJSON,
    TicketSaleToJSON,
} from '../models/TicketSale';
import {
    type TicketSalesPaginatedResponse,
    TicketSalesPaginatedResponseFromJSON,
    TicketSalesPaginatedResponseToJSON,
} from '../models/TicketSalesPaginatedResponse';

export interface DeleteTicketSalesRequest {
    ticketSaleId: string;
}

export interface GetTariffsRequest {
    regularPrice: number;
    eventId: string;
    uitpasNumber: string;
    type?: GetTariffsTypeEnum;
}

export interface GetTariffsStaticRequest {
    regularPrice: number;
    eventId: string;
}

export interface GetTicketSalesRequest {
    eventId: string;
    start?: number;
    limit?: number;
}

export interface PostTicketSalesRequest {
    ticketSale?: Array<TicketSale>;
}

/**
 * 
 */
export class TicketSalesApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteTicketSales without sending the request
     */
    async deleteTicketSalesRequestOpts(requestParameters: DeleteTicketSalesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ticketSaleId'] == null) {
            throw new runtime.RequiredError(
                'ticketSaleId',
                'Required parameter "ticketSaleId" was null or undefined when calling deleteTicketSales().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ticket-sales/{ticketSaleId}`;
        urlPath = urlPath.replace('{ticketSaleId}', encodeURIComponent(String(requestParameters['ticketSaleId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancels a single ticket sale registration by its id. (Returned in the response of the ticket sale registration request.)  The caller of this request must have `TICKETSALES_REGISTER` permission for the organizer of the event of the ticketsale.
     * Cancel a ticket sale registration
     */
    async deleteTicketSalesRaw(requestParameters: DeleteTicketSalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTicketSalesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancels a single ticket sale registration by its id. (Returned in the response of the ticket sale registration request.)  The caller of this request must have `TICKETSALES_REGISTER` permission for the organizer of the event of the ticketsale.
     * Cancel a ticket sale registration
     */
    async deleteTicketSales(requestParameters: DeleteTicketSalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTicketSalesRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getTariffs without sending the request
     */
    async getTariffsRequestOpts(requestParameters: GetTariffsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['regularPrice'] == null) {
            throw new runtime.RequiredError(
                'regularPrice',
                'Required parameter "regularPrice" was null or undefined when calling getTariffs().'
            );
        }

        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getTariffs().'
            );
        }

        if (requestParameters['uitpasNumber'] == null) {
            throw new runtime.RequiredError(
                'uitpasNumber',
                'Required parameter "uitpasNumber" was null or undefined when calling getTariffs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['regularPrice'] != null) {
            queryParameters['regularPrice'] = requestParameters['regularPrice'];
        }

        if (requestParameters['eventId'] != null) {
            queryParameters['eventId'] = requestParameters['eventId'];
        }

        if (requestParameters['uitpasNumber'] != null) {
            queryParameters['uitpasNumber'] = requestParameters['uitpasNumber'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tariffs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the possible UiTPAS discounted **tariffs for an event and a passholder**.  This UiTPAS tariffs are calculated based on:  - **The regular price** of the ticket. This is the price your user would have to pay for the specific ticket without UiTPAS discount. - **The UiTPAS number** of the passholder. UiTPAS discounts are personal so it\'s important to identify the passholder to retrieve a list of possible tariffs. - **The event id** of the UiTdatabank event. UiTPAS discounts are limited to specific UiTdatabank events, so it\'s important to specify the event id to retrieve a list of possible tariffs.  > ##### Important > The regular price of the ticket should generally be one of the price categories set on the event in UiTdatabank to make financial reporting clearer.  The caller of this request must have `TARIFFS_READ` permission for the organizer of the given event.
     * Get tariffs
     */
    async getTariffsRaw(requestParameters: GetTariffsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TariffsResponse>> {
        const requestOptions = await this.getTariffsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TariffsResponseFromJSON(jsonValue));
    }

    /**
     * Returns the possible UiTPAS discounted **tariffs for an event and a passholder**.  This UiTPAS tariffs are calculated based on:  - **The regular price** of the ticket. This is the price your user would have to pay for the specific ticket without UiTPAS discount. - **The UiTPAS number** of the passholder. UiTPAS discounts are personal so it\'s important to identify the passholder to retrieve a list of possible tariffs. - **The event id** of the UiTdatabank event. UiTPAS discounts are limited to specific UiTdatabank events, so it\'s important to specify the event id to retrieve a list of possible tariffs.  > ##### Important > The regular price of the ticket should generally be one of the price categories set on the event in UiTdatabank to make financial reporting clearer.  The caller of this request must have `TARIFFS_READ` permission for the organizer of the given event.
     * Get tariffs
     */
    async getTariffs(requestParameters: GetTariffsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TariffsResponse> {
        const response = await this.getTariffsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTariffsStatic without sending the request
     */
    async getTariffsStaticRequestOpts(requestParameters: GetTariffsStaticRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['regularPrice'] == null) {
            throw new runtime.RequiredError(
                'regularPrice',
                'Required parameter "regularPrice" was null or undefined when calling getTariffsStatic().'
            );
        }

        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getTariffsStatic().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['regularPrice'] != null) {
            queryParameters['regularPrice'] = requestParameters['regularPrice'];
        }

        if (requestParameters['eventId'] != null) {
            queryParameters['eventId'] = requestParameters['eventId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tariffs/static`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the **static** UiTPAS discounted **tariffs for an event**.      <!-- theme: warning -->      > ##### Important > UiTPAS tariffs are different for each indiviual passholder, but this endpoint does NOT take the passholder into consideration. Use this endpoint only in specific cases, e.g. when listing the UiTPAS tariff before the passholder is known. The actual passholder tariffs might be different than this response. Use [GET /tariffs](/reference/uitpas.json/paths/~1tariffs/get) to retrieve indidivual tariffs for a passholder.     This UiTPAS tariffs are calculated based on:  - **The regular price** of the ticket. This is the price your user would have to pay for the specific ticket without UiTPAS discount. - **The event id** of the UiTdatabank event. UiTPAS discounts are limited to specific UiTdatabank events, so it\'s important to specify the event id to retrieve a list of possible tariffs.  Because the passholder is unknown, UiTPAS will return the tariffs for a passholder with social tariff, who lives in the same region as the event organizer.  The caller of this request must have `TARIFFS_READ` permission for the organizer of the given event.
     * Get static tariffs without passholder
     */
    async getTariffsStaticRaw(requestParameters: GetTariffsStaticRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TariffsResponse>> {
        const requestOptions = await this.getTariffsStaticRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TariffsResponseFromJSON(jsonValue));
    }

    /**
     * Returns the **static** UiTPAS discounted **tariffs for an event**.      <!-- theme: warning -->      > ##### Important > UiTPAS tariffs are different for each indiviual passholder, but this endpoint does NOT take the passholder into consideration. Use this endpoint only in specific cases, e.g. when listing the UiTPAS tariff before the passholder is known. The actual passholder tariffs might be different than this response. Use [GET /tariffs](/reference/uitpas.json/paths/~1tariffs/get) to retrieve indidivual tariffs for a passholder.     This UiTPAS tariffs are calculated based on:  - **The regular price** of the ticket. This is the price your user would have to pay for the specific ticket without UiTPAS discount. - **The event id** of the UiTdatabank event. UiTPAS discounts are limited to specific UiTdatabank events, so it\'s important to specify the event id to retrieve a list of possible tariffs.  Because the passholder is unknown, UiTPAS will return the tariffs for a passholder with social tariff, who lives in the same region as the event organizer.  The caller of this request must have `TARIFFS_READ` permission for the organizer of the given event.
     * Get static tariffs without passholder
     */
    async getTariffsStatic(requestParameters: GetTariffsStaticRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TariffsResponse> {
        const response = await this.getTariffsStaticRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTicketSales without sending the request
     */
    async getTicketSalesRequestOpts(requestParameters: GetTicketSalesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getTicketSales().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['eventId'] != null) {
            queryParameters['eventId'] = requestParameters['eventId'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ticket-sales`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve ticket sales based on search parameters.  The caller of this request must have `TICKETSALES_SEARCH` permission for the organizer of the given event.  The `passholder` is included in the response if applicable (passholder can be empty in some cases, e.g. for group passes), and only if the caller of this request has PASSHOLDERS_SEARCH permission.
     * Retrieve existing ticket sales
     */
    async getTicketSalesRaw(requestParameters: GetTicketSalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketSalesPaginatedResponse>> {
        const requestOptions = await this.getTicketSalesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketSalesPaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve ticket sales based on search parameters.  The caller of this request must have `TICKETSALES_SEARCH` permission for the organizer of the given event.  The `passholder` is included in the response if applicable (passholder can be empty in some cases, e.g. for group passes), and only if the caller of this request has PASSHOLDERS_SEARCH permission.
     * Retrieve existing ticket sales
     */
    async getTicketSales(requestParameters: GetTicketSalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketSalesPaginatedResponse> {
        const response = await this.getTicketSalesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postTicketSales without sending the request
     */
    async postTicketSalesRequestOpts(requestParameters: PostTicketSalesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/ticket-sales`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['ticketSale']!.map(TicketSaleToJSON),
        };
    }

    /**
     * Registers one or more new ticket sales **with a discounted UiTPAS tariff**, so the UiTPAS organiser can get reimbursed for the discount.  Before you can register a discounted ticket sale, you will need to request the possible discounted tariffs from the `GET /tariffs` endpoint and let your end user pick one of the available tariffs. Afterward, you can register a ticket sale using this endpoint.   You will need:  - The `uitpasNumber` of the passholder buying the ticket. - The `eventId` of the UiTdatabank event. - The chosen `tariff` from the `GET /tariffs` request. (only the `id` is required) - The `regularPrice` the passholder would normally have to pay for this ticket  Optionally you can include: - a `regularPriceLabel` describing the regular price if you have multiple price  categories, which can be useful in the financial reporting overview.  If you want to register more than one ticket sale for the same passholder, for the same event, at the same tariff, use multiple `TicketSale` objects in this request. Do note this is only possible if `remaining` was higher than one in the `GET /tariffs` request.  The `passholder` field of `TicketSale` is ignored in the request body. It is included in the response if applicable (passholder can be empty in some cases, e.g. for group passes), but only if the caller of this request has `PASSHOLDERS_SEARCH` permission.  <!-- theme: warning -->  > ##### Error handling > **If one of the ticket sales is invalid** (for example the chosen tariff is incorrect or expired), **none of the ticket sales will be registered**. You will instead get an error response with more details about the problem, and can then retry the registration without the incorrect ticket sales or ask the end user to change the tickets and/or tariffs that they want.  The caller of this request must have `TICKETSALES_REGISTER`  permission for the organizer of the given event. 
     * Register ticket sale(s)
     */
    async postTicketSalesRaw(requestParameters: PostTicketSalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TicketSale>>> {
        const requestOptions = await this.postTicketSalesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TicketSaleFromJSON));
    }

    /**
     * Registers one or more new ticket sales **with a discounted UiTPAS tariff**, so the UiTPAS organiser can get reimbursed for the discount.  Before you can register a discounted ticket sale, you will need to request the possible discounted tariffs from the `GET /tariffs` endpoint and let your end user pick one of the available tariffs. Afterward, you can register a ticket sale using this endpoint.   You will need:  - The `uitpasNumber` of the passholder buying the ticket. - The `eventId` of the UiTdatabank event. - The chosen `tariff` from the `GET /tariffs` request. (only the `id` is required) - The `regularPrice` the passholder would normally have to pay for this ticket  Optionally you can include: - a `regularPriceLabel` describing the regular price if you have multiple price  categories, which can be useful in the financial reporting overview.  If you want to register more than one ticket sale for the same passholder, for the same event, at the same tariff, use multiple `TicketSale` objects in this request. Do note this is only possible if `remaining` was higher than one in the `GET /tariffs` request.  The `passholder` field of `TicketSale` is ignored in the request body. It is included in the response if applicable (passholder can be empty in some cases, e.g. for group passes), but only if the caller of this request has `PASSHOLDERS_SEARCH` permission.  <!-- theme: warning -->  > ##### Error handling > **If one of the ticket sales is invalid** (for example the chosen tariff is incorrect or expired), **none of the ticket sales will be registered**. You will instead get an error response with more details about the problem, and can then retry the registration without the incorrect ticket sales or ask the end user to change the tickets and/or tariffs that they want.  The caller of this request must have `TICKETSALES_REGISTER`  permission for the organizer of the given event. 
     * Register ticket sale(s)
     */
    async postTicketSales(requestParameters: PostTicketSalesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TicketSale>> {
        const response = await this.postTicketSalesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetTariffsTypeEnum = {
    Any: 'ANY',
    Socialtariff: 'SOCIALTARIFF',
    Coupon: 'COUPON'
} as const;
export type GetTariffsTypeEnum = typeof GetTariffsTypeEnum[keyof typeof GetTariffsTypeEnum];
