/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Association
 * @export
 * @interface Association
 */
export interface Association {
    /**
     * ID of the association
     * @type {string}
     * @memberof Association
     */
    id: string;
    /**
     * Name of the association. This field is always available in responses
     * @type {string}
     * @memberof Association
     */
    readonly name?: string;
    /**
     * Indicates how end dates are set for memberships of this association. This field is always available in responses.
     * @type {AssociationEndDateTypeEnum}
     * @memberof Association
     */
    readonly endDateType?: AssociationEndDateTypeEnum;
}


/**
 * @export
 */
export const AssociationEndDateTypeEnum = {
    Custom: 'CUSTOM',
    BasedOnDateOfBirth: 'BASED_ON_DATE_OF_BIRTH',
    BasedOnRegistrationDate: 'BASED_ON_REGISTRATION_DATE'
} as const;
export type AssociationEndDateTypeEnum = typeof AssociationEndDateTypeEnum[keyof typeof AssociationEndDateTypeEnum];


/**
 * Check if a given object implements the Association interface.
 */
export function instanceOfAssociation(value: object): value is Association {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AssociationFromJSON(json: any): Association {
    return AssociationFromJSONTyped(json, false);
}

export function AssociationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Association {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'endDateType': json['endDateType'] == null ? undefined : json['endDateType'],
    };
}

export function AssociationToJSON(json: any): Association {
    return AssociationToJSONTyped(json, false);
}

export function AssociationToJSONTyped(value?: Omit<Association, 'name'|'endDateType'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

