/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * CardSystemCitySettings
 * @export
 * @interface CardSystemCitySettings
 */
export interface CardSystemCitySettings {
    /**
     * These settings apply to this city.
     * @type {string}
     * @memberof CardSystemCitySettings
     */
    city: string;
    /**
     * true if social tariff registration is allowed for passholder with `postalCode`.
     * @type {boolean}
     * @memberof CardSystemCitySettings
     */
    allowsCardlessRegistration: boolean;
    /**
     * Contact email of this card system in the given city.
     * @type {string}
     * @memberof CardSystemCitySettings
     */
    contactEmail: string;
}

/**
 * Check if a given object implements the CardSystemCitySettings interface.
 */
export function instanceOfCardSystemCitySettings(value: object): value is CardSystemCitySettings {
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('allowsCardlessRegistration' in value) || value['allowsCardlessRegistration'] === undefined) return false;
    if (!('contactEmail' in value) || value['contactEmail'] === undefined) return false;
    return true;
}

export function CardSystemCitySettingsFromJSON(json: any): CardSystemCitySettings {
    return CardSystemCitySettingsFromJSONTyped(json, false);
}

export function CardSystemCitySettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardSystemCitySettings {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'],
        'allowsCardlessRegistration': json['allowsCardlessRegistration'],
        'contactEmail': json['contactEmail'],
    };
}

export function CardSystemCitySettingsToJSON(json: any): CardSystemCitySettings {
    return CardSystemCitySettingsToJSONTyped(json, false);
}

export function CardSystemCitySettingsToJSONTyped(value?: CardSystemCitySettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'allowsCardlessRegistration': value['allowsCardlessRegistration'],
        'contactEmail': value['contactEmail'],
    };
}

