/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CardSystem } from './CardSystem';
import {
    CardSystemFromJSON,
    CardSystemFromJSONTyped,
    CardSystemToJSON,
    CardSystemToJSONTyped,
} from './CardSystem';
import type { CardSystemMembershipSocialTariff } from './CardSystemMembershipSocialTariff';
import {
    CardSystemMembershipSocialTariffFromJSON,
    CardSystemMembershipSocialTariffFromJSONTyped,
    CardSystemMembershipSocialTariffToJSON,
    CardSystemMembershipSocialTariffToJSONTyped,
} from './CardSystemMembershipSocialTariff';
import type { CardSystemMembershipCard } from './CardSystemMembershipCard';
import {
    CardSystemMembershipCardFromJSON,
    CardSystemMembershipCardFromJSONTyped,
    CardSystemMembershipCardToJSON,
    CardSystemMembershipCardToJSONTyped,
} from './CardSystemMembershipCard';

/**
 * Membership info of an individual passholder in a specific card system.
 * @export
 * @interface CardSystemMembership
 */
export interface CardSystemMembership {
    /**
     * 
     * @type {CardSystem}
     * @memberof CardSystemMembership
     */
    cardSystem: CardSystem;
    /**
     * This is a convenience propery that contains the uitpasNumber of the `currentCard` if there is a current card and that card is `ACTIVE`.
     * @type {string}
     * @memberof CardSystemMembership
     */
    uitpasNumber?: string;
    /**
     * 
     * @type {CardSystemMembershipCard}
     * @memberof CardSystemMembership
     */
    currentCard?: CardSystemMembershipCard;
    /**
     * Whether the membership is active or blocked.
     * @type {CardSystemMembershipStatusEnum}
     * @memberof CardSystemMembership
     */
    readonly status?: CardSystemMembershipStatusEnum;
    /**
     * 
     * @type {CardSystemMembershipSocialTariff}
     * @memberof CardSystemMembership
     */
    socialTariff?: CardSystemMembershipSocialTariff;
}


/**
 * @export
 */
export const CardSystemMembershipStatusEnum = {
    Active: 'ACTIVE',
    Blocked: 'BLOCKED'
} as const;
export type CardSystemMembershipStatusEnum = typeof CardSystemMembershipStatusEnum[keyof typeof CardSystemMembershipStatusEnum];


/**
 * Check if a given object implements the CardSystemMembership interface.
 */
export function instanceOfCardSystemMembership(value: object): value is CardSystemMembership {
    if (!('cardSystem' in value) || value['cardSystem'] === undefined) return false;
    return true;
}

export function CardSystemMembershipFromJSON(json: any): CardSystemMembership {
    return CardSystemMembershipFromJSONTyped(json, false);
}

export function CardSystemMembershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardSystemMembership {
    if (json == null) {
        return json;
    }
    return {
        
        'cardSystem': CardSystemFromJSON(json['cardSystem']),
        'uitpasNumber': json['uitpasNumber'] == null ? undefined : json['uitpasNumber'],
        'currentCard': json['currentCard'] == null ? undefined : CardSystemMembershipCardFromJSON(json['currentCard']),
        'status': json['status'] == null ? undefined : json['status'],
        'socialTariff': json['socialTariff'] == null ? undefined : CardSystemMembershipSocialTariffFromJSON(json['socialTariff']),
    };
}

export function CardSystemMembershipToJSON(json: any): CardSystemMembership {
    return CardSystemMembershipToJSONTyped(json, false);
}

export function CardSystemMembershipToJSONTyped(value?: Omit<CardSystemMembership, 'status'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cardSystem': CardSystemToJSON(value['cardSystem']),
        'uitpasNumber': value['uitpasNumber'],
        'currentCard': CardSystemMembershipCardToJSON(value['currentCard']),
        'socialTariff': CardSystemMembershipSocialTariffToJSON(value['socialTariff']),
    };
}

