/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CardSystemBranding } from './CardSystemBranding';
import {
    CardSystemBrandingFromJSON,
    CardSystemBrandingFromJSONTyped,
    CardSystemBrandingToJSON,
    CardSystemBrandingToJSONTyped,
} from './CardSystemBranding';
import type { CardSystemLinks } from './CardSystemLinks';
import {
    CardSystemLinksFromJSON,
    CardSystemLinksFromJSONTyped,
    CardSystemLinksToJSON,
    CardSystemLinksToJSONTyped,
} from './CardSystemLinks';
import type { City } from './City';
import {
    CityFromJSON,
    CityFromJSONTyped,
    CityToJSON,
    CityToJSONTyped,
} from './City';

/**
 * A region, usually one or multiple municipalities in Belgium, that uses UiTPAS and provides discounts and/or rewards. For example "Paspartoe" (Brussels), UiTPAS Leuven, UiTPAS Hasselt, UiTPAS Gent, and so on.
 * @export
 * @interface CardSystem
 */
export interface CardSystem {
    /**
     * ID of the card system
     * @type {number}
     * @memberof CardSystem
     */
    id: number;
    /**
     * Name of the card system. This field is always available in responses.
     * @type {string}
     * @memberof CardSystem
     */
    name?: string;
    /**
     * 
     * @type {CardSystemBranding}
     * @memberof CardSystem
     */
    branding?: CardSystemBranding;
    /**
     * 
     * @type {CardSystemLinks}
     * @memberof CardSystem
     */
    links?: CardSystemLinks;
    /**
     * List of cities that are part of this card system
     * @type {Array<City>}
     * @memberof CardSystem
     */
    cities?: Array<City>;
    /**
     * Indicates whether this is a permanent card system
     * @type {boolean}
     * @memberof CardSystem
     */
    permanent?: boolean;
    /**
     * Indicates if cardless registration is enabled
     * @type {boolean}
     * @memberof CardSystem
     */
    allowsCardlessRegistration?: boolean;
    /**
     * Indicates the types of online cardless registrations this cardsystem supports.
     * @type {CardSystemCardlessRegistrationTypeEnum}
     * @memberof CardSystem
     */
    cardlessRegistrationType?: CardSystemCardlessRegistrationTypeEnum;
    /**
     * Optional information about social tariff entitlement in this card system.
     * @type {string}
     * @memberof CardSystem
     */
    socialTariffInfo?: string;
}


/**
 * @export
 */
export const CardSystemCardlessRegistrationTypeEnum = {
    All: 'ALL',
    Regular: 'REGULAR',
    Socialtariff: 'SOCIALTARIFF',
    None: 'NONE'
} as const;
export type CardSystemCardlessRegistrationTypeEnum = typeof CardSystemCardlessRegistrationTypeEnum[keyof typeof CardSystemCardlessRegistrationTypeEnum];


/**
 * Check if a given object implements the CardSystem interface.
 */
export function instanceOfCardSystem(value: object): value is CardSystem {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CardSystemFromJSON(json: any): CardSystem {
    return CardSystemFromJSONTyped(json, false);
}

export function CardSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardSystem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'branding': json['branding'] == null ? undefined : CardSystemBrandingFromJSON(json['branding']),
        'links': json['links'] == null ? undefined : CardSystemLinksFromJSON(json['links']),
        'cities': json['cities'] == null ? undefined : ((json['cities'] as Array<any>).map(CityFromJSON)),
        'permanent': json['permanent'] == null ? undefined : json['permanent'],
        'allowsCardlessRegistration': json['allowsCardlessRegistration'] == null ? undefined : json['allowsCardlessRegistration'],
        'cardlessRegistrationType': json['cardlessRegistrationType'] == null ? undefined : json['cardlessRegistrationType'],
        'socialTariffInfo': json['socialTariffInfo'] == null ? undefined : json['socialTariffInfo'],
    };
}

export function CardSystemToJSON(json: any): CardSystem {
    return CardSystemToJSONTyped(json, false);
}

export function CardSystemToJSONTyped(value?: CardSystem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'branding': CardSystemBrandingToJSON(value['branding']),
        'links': CardSystemLinksToJSON(value['links']),
        'cities': value['cities'] == null ? undefined : ((value['cities'] as Array<any>).map(CityToJSON)),
        'permanent': value['permanent'],
        'allowsCardlessRegistration': value['allowsCardlessRegistration'],
        'cardlessRegistrationType': value['cardlessRegistrationType'],
        'socialTariffInfo': value['socialTariffInfo'],
    };
}

