/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CardSystem } from './CardSystem';
import {
    CardSystemFromJSON,
    CardSystemFromJSONTyped,
    CardSystemToJSON,
    CardSystemToJSONTyped,
} from './CardSystem';

/**
 * Representation of an UiTPAS card.
 * @export
 * @interface Card
 */
export interface Card {
    /**
     * UiTPAS number of this card.
     * @type {string}
     * @memberof Card
     */
    uitpasNumber: string;
    /**
     * 
     * @type {CardSystem}
     * @memberof Card
     */
    cardSystem: CardSystem;
    /**
     * Type of this card.
     * @type {CardCardTypeEnum}
     * @memberof Card
     */
    cardType?: CardCardTypeEnum;
    /**
     * Status of this card.
     * @type {CardStatusEnum}
     * @memberof Card
     */
    status: CardStatusEnum;
    /**
     * Indicated the social tariff status of this card.
     * @type {boolean}
     * @memberof Card
     */
    socialTariff: boolean;
}


/**
 * @export
 */
export const CardCardTypeEnum = {
    NfcCard: 'NFC_CARD',
    Digital: 'DIGITAL'
} as const;
export type CardCardTypeEnum = typeof CardCardTypeEnum[keyof typeof CardCardTypeEnum];

/**
 * @export
 */
export const CardStatusEnum = {
    Provisioned: 'PROVISIONED',
    LocalStock: 'LOCAL_STOCK',
    Active: 'ACTIVE',
    Blocked: 'BLOCKED',
    Deleted: 'DELETED'
} as const;
export type CardStatusEnum = typeof CardStatusEnum[keyof typeof CardStatusEnum];


/**
 * Check if a given object implements the Card interface.
 */
export function instanceOfCard(value: object): value is Card {
    if (!('uitpasNumber' in value) || value['uitpasNumber'] === undefined) return false;
    if (!('cardSystem' in value) || value['cardSystem'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('socialTariff' in value) || value['socialTariff'] === undefined) return false;
    return true;
}

export function CardFromJSON(json: any): Card {
    return CardFromJSONTyped(json, false);
}

export function CardFromJSONTyped(json: any, ignoreDiscriminator: boolean): Card {
    if (json == null) {
        return json;
    }
    return {
        
        'uitpasNumber': json['uitpasNumber'],
        'cardSystem': CardSystemFromJSON(json['cardSystem']),
        'cardType': json['cardType'] == null ? undefined : json['cardType'],
        'status': json['status'],
        'socialTariff': json['socialTariff'],
    };
}

export function CardToJSON(json: any): Card {
    return CardToJSONTyped(json, false);
}

export function CardToJSONTyped(value?: Card | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uitpasNumber': value['uitpasNumber'],
        'cardSystem': CardSystemToJSON(value['cardSystem']),
        'cardType': value['cardType'],
        'status': value['status'],
        'socialTariff': value['socialTariff'],
    };
}

