/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Representation of an UiTPAS card embedded in a CardSystemMembership.
 * @export
 * @interface CardSystemMembershipCard
 */
export interface CardSystemMembershipCard {
    /**
     * UiTPAS number of this card.
     * @type {string}
     * @memberof CardSystemMembershipCard
     */
    uitpasNumber: string;
    /**
     * Type of this card.
     * @type {CardSystemMembershipCardCardTypeEnum}
     * @memberof CardSystemMembershipCard
     */
    cardType?: CardSystemMembershipCardCardTypeEnum;
    /**
     * Status of this card.
     * @type {CardSystemMembershipCardStatusEnum}
     * @memberof CardSystemMembershipCard
     */
    status: CardSystemMembershipCardStatusEnum;
}


/**
 * @export
 */
export const CardSystemMembershipCardCardTypeEnum = {
    NfcCard: 'NFC_CARD',
    Digital: 'DIGITAL'
} as const;
export type CardSystemMembershipCardCardTypeEnum = typeof CardSystemMembershipCardCardTypeEnum[keyof typeof CardSystemMembershipCardCardTypeEnum];

/**
 * @export
 */
export const CardSystemMembershipCardStatusEnum = {
    Active: 'ACTIVE',
    Blocked: 'BLOCKED',
    Deleted: 'DELETED'
} as const;
export type CardSystemMembershipCardStatusEnum = typeof CardSystemMembershipCardStatusEnum[keyof typeof CardSystemMembershipCardStatusEnum];


/**
 * Check if a given object implements the CardSystemMembershipCard interface.
 */
export function instanceOfCardSystemMembershipCard(value: object): value is CardSystemMembershipCard {
    if (!('uitpasNumber' in value) || value['uitpasNumber'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CardSystemMembershipCardFromJSON(json: any): CardSystemMembershipCard {
    return CardSystemMembershipCardFromJSONTyped(json, false);
}

export function CardSystemMembershipCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardSystemMembershipCard {
    if (json == null) {
        return json;
    }
    return {
        
        'uitpasNumber': json['uitpasNumber'],
        'cardType': json['cardType'] == null ? undefined : json['cardType'],
        'status': json['status'],
    };
}

export function CardSystemMembershipCardToJSON(json: any): CardSystemMembershipCard {
    return CardSystemMembershipCardToJSONTyped(json, false);
}

export function CardSystemMembershipCardToJSONTyped(value?: CardSystemMembershipCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uitpasNumber': value['uitpasNumber'],
        'cardType': value['cardType'],
        'status': value['status'],
    };
}

