/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Passholder } from './Passholder';
import {
    PassholderFromJSON,
    PassholderFromJSONTyped,
    PassholderToJSON,
    PassholderToJSONTyped,
} from './Passholder';

/**
 * Model used both for registering and searching checkins.
 * 
 * The `passholder` field is automatically included in responses if you have PASSHOLDERS_SEARCH permission. It is not required for check-in creation.
 * @export
 * @interface Checkin
 */
export interface Checkin {
    /**
     * Unique id of a check-in. Not required for check-in creation.
     * @type {string}
     * @memberof Checkin
     */
    readonly id?: string;
    /**
     * Id of the event where the passholder checked in
     * @type {string}
     * @memberof Checkin
     */
    eventId: string;
    /**
     * The passholder's UiTPAS number used to create the check-in. Note that the uitpasNumber of a passholder might change over time. This field will always contain the uitpasNumber used when creating the check-in. To identify the passholder, use the `passholder` field.
     * @type {string}
     * @memberof Checkin
     */
    uitpasNumber: string;
    /**
     * Points earned by the passholder as a result of this check-in.
     * @type {number}
     * @memberof Checkin
     */
    readonly points?: number;
    /**
     * Full passholder object of this check-in.
     * @type {Passholder}
     * @memberof Checkin
     */
    readonly passholder?: Passholder;
}

/**
 * Check if a given object implements the Checkin interface.
 */
export function instanceOfCheckin(value: object): value is Checkin {
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('uitpasNumber' in value) || value['uitpasNumber'] === undefined) return false;
    return true;
}

export function CheckinFromJSON(json: any): Checkin {
    return CheckinFromJSONTyped(json, false);
}

export function CheckinFromJSONTyped(json: any, ignoreDiscriminator: boolean): Checkin {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'eventId': json['eventId'],
        'uitpasNumber': json['uitpasNumber'],
        'points': json['points'] == null ? undefined : json['points'],
        'passholder': json['passholder'] == null ? undefined : PassholderFromJSON(json['passholder']),
    };
}

export function CheckinToJSON(json: any): Checkin {
    return CheckinToJSONTyped(json, false);
}

export function CheckinToJSONTyped(value?: Omit<Checkin, 'id'|'points'|'passholder'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventId': value['eventId'],
        'uitpasNumber': value['uitpasNumber'],
    };
}

