/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckinStatusEndUserMessage } from './CheckinStatusEndUserMessage';
import {
    CheckinStatusEndUserMessageFromJSON,
    CheckinStatusEndUserMessageFromJSONTyped,
    CheckinStatusEndUserMessageToJSON,
    CheckinStatusEndUserMessageToJSONTyped,
} from './CheckinStatusEndUserMessage';

/**
 * The status of a potential checkin, including an `endUserMessage` when it's not allowed.
 * @export
 * @interface CheckinStatus
 */
export interface CheckinStatus {
    /**
     * Indicates whether a checkin is currently possible.
     * @type {boolean}
     * @memberof CheckinStatus
     */
    allowed?: boolean;
    /**
     * 
     * @type {CheckinStatusEndUserMessage}
     * @memberof CheckinStatus
     */
    endUserMessage?: CheckinStatusEndUserMessage;
}

/**
 * Check if a given object implements the CheckinStatus interface.
 */
export function instanceOfCheckinStatus(value: object): value is CheckinStatus {
    return true;
}

export function CheckinStatusFromJSON(json: any): CheckinStatus {
    return CheckinStatusFromJSONTyped(json, false);
}

export function CheckinStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckinStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'allowed': json['allowed'] == null ? undefined : json['allowed'],
        'endUserMessage': json['endUserMessage'] == null ? undefined : CheckinStatusEndUserMessageFromJSON(json['endUserMessage']),
    };
}

export function CheckinStatusToJSON(json: any): CheckinStatus {
    return CheckinStatusToJSONTyped(json, false);
}

export function CheckinStatusToJSONTyped(value?: CheckinStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowed': value['allowed'],
        'endUserMessage': CheckinStatusEndUserMessageToJSON(value['endUserMessage']),
    };
}

