/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface City
 */
export interface City {
    /**
     * Postalcode of the city
     * @type {string}
     * @memberof City
     */
    postalCode: string;
    /**
     * Name of the city
     * @type {string}
     * @memberof City
     */
    name: string;
}

/**
 * Check if a given object implements the City interface.
 */
export function instanceOfCity(value: object): value is City {
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CityFromJSON(json: any): City {
    return CityFromJSONTyped(json, false);
}

export function CityFromJSONTyped(json: any, ignoreDiscriminator: boolean): City {
    if (json == null) {
        return json;
    }
    return {
        
        'postalCode': json['postalCode'],
        'name': json['name'],
    };
}

export function CityToJSON(json: any): City {
    return CityToJSONTyped(json, false);
}

export function CityToJSONTyped(value?: City | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postalCode': value['postalCode'],
        'name': value['name'],
    };
}

