/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownloadLinkResponse
 */
export interface DownloadLinkResponse {
    /**
     * Download link for the requested file
     * @type {string}
     * @memberof DownloadLinkResponse
     */
    downloadLink: string;
}

/**
 * Check if a given object implements the DownloadLinkResponse interface.
 */
export function instanceOfDownloadLinkResponse(value: object): value is DownloadLinkResponse {
    if (!('downloadLink' in value) || value['downloadLink'] === undefined) return false;
    return true;
}

export function DownloadLinkResponseFromJSON(json: any): DownloadLinkResponse {
    return DownloadLinkResponseFromJSONTyped(json, false);
}

export function DownloadLinkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadLinkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadLink': json['downloadLink'],
    };
}

export function DownloadLinkResponseToJSON(json: any): DownloadLinkResponse {
    return DownloadLinkResponseToJSONTyped(json, false);
}

export function DownloadLinkResponseToJSONTyped(value?: DownloadLinkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'downloadLink': value['downloadLink'],
    };
}

