/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PeriodLimit } from './PeriodLimit';
import {
    PeriodLimitFromJSON,
    PeriodLimitFromJSONTyped,
    PeriodLimitToJSON,
    PeriodLimitToJSONTyped,
} from './PeriodLimit';

/**
 * Event setting within UiTPAS
 * @export
 * @interface EventSettings
 */
export interface EventSettings {
    /**
     * ID of the event
     * @type {string}
     * @memberof EventSettings
     */
    id: string;
    /**
     * 
     * @type {PeriodLimit}
     * @memberof EventSettings
     */
    passholderTicketLimit?: PeriodLimit;
    /**
     * 
     * @type {PeriodLimit}
     * @memberof EventSettings
     */
    checkinLimit?: PeriodLimit;
    /**
     * Points earned after a checkin for this event
     * @type {number}
     * @memberof EventSettings
     */
    checkinPoints: number;
}

/**
 * Check if a given object implements the EventSettings interface.
 */
export function instanceOfEventSettings(value: object): value is EventSettings {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('checkinPoints' in value) || value['checkinPoints'] === undefined) return false;
    return true;
}

export function EventSettingsFromJSON(json: any): EventSettings {
    return EventSettingsFromJSONTyped(json, false);
}

export function EventSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'passholderTicketLimit': json['passholderTicketLimit'] == null ? undefined : PeriodLimitFromJSON(json['passholderTicketLimit']),
        'checkinLimit': json['checkinLimit'] == null ? undefined : PeriodLimitFromJSON(json['checkinLimit']),
        'checkinPoints': json['checkinPoints'],
    };
}

export function EventSettingsToJSON(json: any): EventSettings {
    return EventSettingsToJSONTyped(json, false);
}

export function EventSettingsToJSONTyped(value?: EventSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'passholderTicketLimit': PeriodLimitToJSON(value['passholderTicketLimit']),
        'checkinLimit': PeriodLimitToJSON(value['checkinLimit']),
        'checkinPoints': value['checkinPoints'],
    };
}

