/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetPasses400ResponseEndUserMessage } from './GetPasses400ResponseEndUserMessage';
import {
    GetPasses400ResponseEndUserMessageFromJSON,
    GetPasses400ResponseEndUserMessageFromJSONTyped,
    GetPasses400ResponseEndUserMessageToJSON,
    GetPasses400ResponseEndUserMessageToJSONTyped,
} from './GetPasses400ResponseEndUserMessage';
import type { GetPasses400ResponseSchemaErrorsInner } from './GetPasses400ResponseSchemaErrorsInner';
import {
    GetPasses400ResponseSchemaErrorsInnerFromJSON,
    GetPasses400ResponseSchemaErrorsInnerFromJSONTyped,
    GetPasses400ResponseSchemaErrorsInnerToJSON,
    GetPasses400ResponseSchemaErrorsInnerToJSONTyped,
} from './GetPasses400ResponseSchemaErrorsInner';

/**
 * 
 * @export
 * @interface GetPasses400Response
 */
export interface GetPasses400Response {
    /**
     * A URI reference that identifies the problem type. Can be used to recognize specific errors in your application code by comparing the complete URI.
     * @type {string}
     * @memberof GetPasses400Response
     */
    type?: string;
    /**
     * A short, human-readable summary of the problem type (for developers).
     * @type {string}
     * @memberof GetPasses400Response
     */
    title?: string;
    /**
     * The HTTP status code.
     * @type {number}
     * @memberof GetPasses400Response
     */
    status?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem (for developers). 
     * @type {string}
     * @memberof GetPasses400Response
     */
    detail?: string;
    /**
     * 
     * @type {GetPasses400ResponseEndUserMessage}
     * @memberof GetPasses400Response
     */
    endUserMessage?: GetPasses400ResponseEndUserMessage;
    /**
     * A list of one or more schema validation errors (usually used for error type https://api.publiq.be/probs/body/invalid-data).
     * @type {Array<GetPasses400ResponseSchemaErrorsInner>}
     * @memberof GetPasses400Response
     */
    schemaErrors?: Array<GetPasses400ResponseSchemaErrorsInner>;
    /**
     * If type is `invalid-card-status` this property contains the actual status of the card.
     * @type {string}
     * @memberof GetPasses400Response
     */
    cardStatus?: string;
    /**
     * If `cardStatus` is `BLOCKED` or `DELETED`, this property cosntain the passholderId of this pass.
     * @type {string}
     * @memberof GetPasses400Response
     */
    passholderId?: string;
    /**
     * Indicates whether this pass belongs to an individual passholder or a group (Grouppas)
     * @type {GetPasses400ResponsePassTypeEnum}
     * @memberof GetPasses400Response
     */
    passType?: GetPasses400ResponsePassTypeEnum;
}


/**
 * @export
 */
export const GetPasses400ResponsePassTypeEnum = {
    Individual: 'INDIVIDUAL',
    Group: 'GROUP'
} as const;
export type GetPasses400ResponsePassTypeEnum = typeof GetPasses400ResponsePassTypeEnum[keyof typeof GetPasses400ResponsePassTypeEnum];


/**
 * Check if a given object implements the GetPasses400Response interface.
 */
export function instanceOfGetPasses400Response(value: object): value is GetPasses400Response {
    return true;
}

export function GetPasses400ResponseFromJSON(json: any): GetPasses400Response {
    return GetPasses400ResponseFromJSONTyped(json, false);
}

export function GetPasses400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPasses400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'title': json['title'] == null ? undefined : json['title'],
        'status': json['status'] == null ? undefined : json['status'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'endUserMessage': json['endUserMessage'] == null ? undefined : GetPasses400ResponseEndUserMessageFromJSON(json['endUserMessage']),
        'schemaErrors': json['schemaErrors'] == null ? undefined : ((json['schemaErrors'] as Array<any>).map(GetPasses400ResponseSchemaErrorsInnerFromJSON)),
        'cardStatus': json['cardStatus'] == null ? undefined : json['cardStatus'],
        'passholderId': json['passholderId'] == null ? undefined : json['passholderId'],
        'passType': json['passType'] == null ? undefined : json['passType'],
    };
}

export function GetPasses400ResponseToJSON(json: any): GetPasses400Response {
    return GetPasses400ResponseToJSONTyped(json, false);
}

export function GetPasses400ResponseToJSONTyped(value?: GetPasses400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
        'status': value['status'],
        'detail': value['detail'],
        'endUserMessage': GetPasses400ResponseEndUserMessageToJSON(value['endUserMessage']),
        'schemaErrors': value['schemaErrors'] == null ? undefined : ((value['schemaErrors'] as Array<any>).map(GetPasses400ResponseSchemaErrorsInnerToJSON)),
        'cardStatus': value['cardStatus'],
        'passholderId': value['passholderId'],
        'passType': value['passType'],
    };
}

