/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUitidPassholderRegistrationToken200Response
 */
export interface GetUitidPassholderRegistrationToken200Response {
    /**
     * UiTPAS number of the validated passholder
     * @type {string}
     * @memberof GetUitidPassholderRegistrationToken200Response
     */
    token: string;
}

/**
 * Check if a given object implements the GetUitidPassholderRegistrationToken200Response interface.
 */
export function instanceOfGetUitidPassholderRegistrationToken200Response(value: object): value is GetUitidPassholderRegistrationToken200Response {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function GetUitidPassholderRegistrationToken200ResponseFromJSON(json: any): GetUitidPassholderRegistrationToken200Response {
    return GetUitidPassholderRegistrationToken200ResponseFromJSONTyped(json, false);
}

export function GetUitidPassholderRegistrationToken200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUitidPassholderRegistrationToken200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function GetUitidPassholderRegistrationToken200ResponseToJSON(json: any): GetUitidPassholderRegistrationToken200Response {
    return GetUitidPassholderRegistrationToken200ResponseToJSONTyped(json, false);
}

export function GetUitidPassholderRegistrationToken200ResponseToJSONTyped(value?: GetUitidPassholderRegistrationToken200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

