/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Address of the grouppass. Always present in responses.
 * @export
 * @interface GrouppassAddress
 */
export interface GrouppassAddress {
    /**
     * Full street name, number and box of the grouppass
     * @type {string}
     * @memberof GrouppassAddress
     */
    street?: string;
    /**
     * Postal code of the municipality.
     * @type {string}
     * @memberof GrouppassAddress
     */
    postalCode: string;
    /**
     * Human-readable name of the municipality.
     * @type {string}
     * @memberof GrouppassAddress
     */
    city: string;
    /**
     * ISO 3166-1 alpha-2 country code.
     * @type {string}
     * @memberof GrouppassAddress
     */
    country?: string;
}

/**
 * Check if a given object implements the GrouppassAddress interface.
 */
export function instanceOfGrouppassAddress(value: object): value is GrouppassAddress {
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    return true;
}

export function GrouppassAddressFromJSON(json: any): GrouppassAddress {
    return GrouppassAddressFromJSONTyped(json, false);
}

export function GrouppassAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrouppassAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'street': json['street'] == null ? undefined : json['street'],
        'postalCode': json['postalCode'],
        'city': json['city'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function GrouppassAddressToJSON(json: any): GrouppassAddress {
    return GrouppassAddressToJSONTyped(json, false);
}

export function GrouppassAddressToJSONTyped(value?: GrouppassAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'street': value['street'],
        'postalCode': value['postalCode'],
        'city': value['city'],
        'country': value['country'],
    };
}

