/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Model to configure the kiosk event
 * @export
 * @interface KioskDeviceEventRequest
 */
export interface KioskDeviceEventRequest {
    /**
     * ID of the event
     * @type {string}
     * @memberof KioskDeviceEventRequest
     */
    id: string;
}

/**
 * Check if a given object implements the KioskDeviceEventRequest interface.
 */
export function instanceOfKioskDeviceEventRequest(value: object): value is KioskDeviceEventRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function KioskDeviceEventRequestFromJSON(json: any): KioskDeviceEventRequest {
    return KioskDeviceEventRequestFromJSONTyped(json, false);
}

export function KioskDeviceEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KioskDeviceEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function KioskDeviceEventRequestToJSON(json: any): KioskDeviceEventRequest {
    return KioskDeviceEventRequestToJSONTyped(json, false);
}

export function KioskDeviceEventRequestToJSONTyped(value?: KioskDeviceEventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

