/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pass information
 * @export
 * @interface KioskPass
 */
export interface KioskPass {
    /**
     * Total points of the passholder
     * @type {number}
     * @memberof KioskPass
     */
    totalPoints: number;
}

/**
 * Check if a given object implements the KioskPass interface.
 */
export function instanceOfKioskPass(value: object): value is KioskPass {
    if (!('totalPoints' in value) || value['totalPoints'] === undefined) return false;
    return true;
}

export function KioskPassFromJSON(json: any): KioskPass {
    return KioskPassFromJSONTyped(json, false);
}

export function KioskPassFromJSONTyped(json: any, ignoreDiscriminator: boolean): KioskPass {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPoints': json['totalPoints'],
    };
}

export function KioskPassToJSON(json: any): KioskPass {
    return KioskPassToJSONTyped(json, false);
}

export function KioskPassToJSONTyped(value?: KioskPass | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPoints': value['totalPoints'],
    };
}

