/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Checkin via kiosk response
 * @export
 * @interface KioskDeviceCheckinResponse
 */
export interface KioskDeviceCheckinResponse {
    /**
     * New points as a result of this checkin
     * @type {number}
     * @memberof KioskDeviceCheckinResponse
     */
    newPoints: number;
    /**
     * Total points of the passholder after this checkin
     * @type {number}
     * @memberof KioskDeviceCheckinResponse
     */
    totalPoints: number;
}

/**
 * Check if a given object implements the KioskDeviceCheckinResponse interface.
 */
export function instanceOfKioskDeviceCheckinResponse(value: object): value is KioskDeviceCheckinResponse {
    if (!('newPoints' in value) || value['newPoints'] === undefined) return false;
    if (!('totalPoints' in value) || value['totalPoints'] === undefined) return false;
    return true;
}

export function KioskDeviceCheckinResponseFromJSON(json: any): KioskDeviceCheckinResponse {
    return KioskDeviceCheckinResponseFromJSONTyped(json, false);
}

export function KioskDeviceCheckinResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KioskDeviceCheckinResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'newPoints': json['newPoints'],
        'totalPoints': json['totalPoints'],
    };
}

export function KioskDeviceCheckinResponseToJSON(json: any): KioskDeviceCheckinResponse {
    return KioskDeviceCheckinResponseToJSONTyped(json, false);
}

export function KioskDeviceCheckinResponseToJSONTyped(value?: KioskDeviceCheckinResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newPoints': value['newPoints'],
        'totalPoints': value['totalPoints'],
    };
}

