/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Organizer } from './Organizer';
import {
    OrganizerFromJSON,
    OrganizerFromJSONTyped,
    OrganizerToJSON,
    OrganizerToJSONTyped,
} from './Organizer';
import type { PermissionDetail } from './PermissionDetail';
import {
    PermissionDetailFromJSON,
    PermissionDetailFromJSONTyped,
    PermissionDetailToJSON,
    PermissionDetailToJSONTyped,
} from './PermissionDetail';

/**
 * Combination of organizer and its permissions, specifically targetted to be used when linked to another organizer.
 * @export
 * @interface LinkedOrganizerPermissions
 */
export interface LinkedOrganizerPermissions {
    /**
     * 
     * @type {Organizer}
     * @memberof LinkedOrganizerPermissions
     */
    organizer: Organizer;
    /**
     * Permissions of the calling client for this organizer.
     * @type {Array<PermissionDetail>}
     * @memberof LinkedOrganizerPermissions
     */
    permissionDetails?: Array<PermissionDetail>;
}

/**
 * Check if a given object implements the LinkedOrganizerPermissions interface.
 */
export function instanceOfLinkedOrganizerPermissions(value: object): value is LinkedOrganizerPermissions {
    if (!('organizer' in value) || value['organizer'] === undefined) return false;
    return true;
}

export function LinkedOrganizerPermissionsFromJSON(json: any): LinkedOrganizerPermissions {
    return LinkedOrganizerPermissionsFromJSONTyped(json, false);
}

export function LinkedOrganizerPermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkedOrganizerPermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'organizer': OrganizerFromJSON(json['organizer']),
        'permissionDetails': json['permissionDetails'] == null ? undefined : ((json['permissionDetails'] as Array<any>).map(PermissionDetailFromJSON)),
    };
}

export function LinkedOrganizerPermissionsToJSON(json: any): LinkedOrganizerPermissions {
    return LinkedOrganizerPermissionsToJSONTyped(json, false);
}

export function LinkedOrganizerPermissionsToJSONTyped(value?: LinkedOrganizerPermissions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organizer': OrganizerToJSON(value['organizer']),
        'permissionDetails': value['permissionDetails'] == null ? undefined : ((value['permissionDetails'] as Array<any>).map(PermissionDetailToJSON)),
    };
}

