/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CardSystem } from './CardSystem';
import {
    CardSystemFromJSON,
    CardSystemFromJSONTyped,
    CardSystemToJSON,
    CardSystemToJSONTyped,
} from './CardSystem';

/**
 * An organisation that partners with UiTPAS to provide discounts and/or rewards, and/or allows points to be collected at their events.
 * @export
 * @interface Organizer
 */
export interface Organizer {
    /**
     * Unique ID of an UiTPAS organizer. (Same as its ID in UiTdatabank)
     * @type {string}
     * @memberof Organizer
     */
    id: string;
    /**
     * Human-readable name of an UiTPAS organizer.
     * @type {string}
     * @memberof Organizer
     */
    name?: string;
    /**
     * Card systems linked to this organizer
     * @type {Array<CardSystem>}
     * @memberof Organizer
     */
    cardSystems?: Array<CardSystem>;
}

/**
 * Check if a given object implements the Organizer interface.
 */
export function instanceOfOrganizer(value: object): value is Organizer {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function OrganizerFromJSON(json: any): Organizer {
    return OrganizerFromJSONTyped(json, false);
}

export function OrganizerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Organizer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'cardSystems': json['cardSystems'] == null ? undefined : ((json['cardSystems'] as Array<any>).map(CardSystemFromJSON)),
    };
}

export function OrganizerToJSON(json: any): Organizer {
    return OrganizerToJSONTyped(json, false);
}

export function OrganizerToJSONTyped(value?: Organizer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'cardSystems': value['cardSystems'] == null ? undefined : ((value['cardSystems'] as Array<any>).map(CardSystemToJSON)),
    };
}

