/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An admin user for an organizer.
 * @export
 * @interface OrganizerAdmin
 */
export interface OrganizerAdmin {
    /**
     * UiTiD user ID of this organizer admin. This field is always available in responses.
     * @type {string}
     * @memberof OrganizerAdmin
     */
    userId?: string;
    /**
     * Email of the organizer admin. 
     * @type {string}
     * @memberof OrganizerAdmin
     */
    email: string;
    /**
     * Type of the organizer admin.
     * @type {OrganizerAdminTypeEnum}
     * @memberof OrganizerAdmin
     */
    type: OrganizerAdminTypeEnum;
}


/**
 * @export
 */
export const OrganizerAdminTypeEnum = {
    Member: 'MEMBER',
    Admin: 'ADMIN'
} as const;
export type OrganizerAdminTypeEnum = typeof OrganizerAdminTypeEnum[keyof typeof OrganizerAdminTypeEnum];


/**
 * Check if a given object implements the OrganizerAdmin interface.
 */
export function instanceOfOrganizerAdmin(value: object): value is OrganizerAdmin {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function OrganizerAdminFromJSON(json: any): OrganizerAdmin {
    return OrganizerAdminFromJSONTyped(json, false);
}

export function OrganizerAdminFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerAdmin {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'email': json['email'],
        'type': json['type'],
    };
}

export function OrganizerAdminToJSON(json: any): OrganizerAdmin {
    return OrganizerAdminToJSONTyped(json, false);
}

export function OrganizerAdminToJSONTyped(value?: OrganizerAdmin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'email': value['email'],
        'type': value['type'],
    };
}

