/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CardSystemMembership } from './CardSystemMembership';
import {
    CardSystemMembershipFromJSON,
    CardSystemMembershipFromJSONTyped,
    CardSystemMembershipToJSON,
    CardSystemMembershipToJSONTyped,
} from './CardSystemMembership';
import type { Organizer } from './Organizer';
import {
    OrganizerFromJSON,
    OrganizerFromJSONTyped,
    OrganizerToJSON,
    OrganizerToJSONTyped,
} from './Organizer';
import type { PassholderAddress } from './PassholderAddress';
import {
    PassholderAddressFromJSON,
    PassholderAddressFromJSONTyped,
    PassholderAddressToJSON,
    PassholderAddressToJSONTyped,
} from './PassholderAddress';
import type { PassholderOptInPreferences } from './PassholderOptInPreferences';
import {
    PassholderOptInPreferencesFromJSON,
    PassholderOptInPreferencesFromJSONTyped,
    PassholderOptInPreferencesToJSON,
    PassholderOptInPreferencesToJSONTyped,
} from './PassholderOptInPreferences';

/**
 * Person who holds an UiTPAS, the end-user of an UiTPAS. 
 * 
 * A `Passholder` can be identified by its `id`. However, there are cases where the passholder identifies using one of its UiTPAS numbers. That number is CardSystem specific, so it can be found under `cardSystemMemberships`. Every passholder should have at least one cardsystem membership.
 * @export
 * @interface Passholder
 */
export interface Passholder {
    /**
     * This field is always available in responses and ignored in create and update operations.
     * @type {string}
     * @memberof Passholder
     */
    readonly id?: string;
    /**
     * Last name of the passholder.
     * @type {string}
     * @memberof Passholder
     */
    name: string;
    /**
     * First name of the passholder.
     * @type {string}
     * @memberof Passholder
     */
    firstName: string;
    /**
     * Unique national (Belgian) INSZ number of an individual passholder to look up.
     * @type {string}
     * @memberof Passholder
     */
    inszNumber?: string;
    /**
     * The UiTPAS number of this passholder. This field contains the UiTPAS number of the oldest, still active cardsystem membership, that has an active card. This field is always available in responses and ignored in create and update operations.
     * @type {string}
     * @memberof Passholder
     */
    uitpasNumber?: string;
    /**
     * This field is always available in responses and ignored in create and update operations.
     * @type {Array<CardSystemMembership>}
     * @memberof Passholder
     */
    readonly cardSystemMemberships?: Array<CardSystemMembership>;
    /**
     * Contact email address of the passholder. Not present for every passholder. Multiple passholders can have the same email address.
     * @type {string}
     * @memberof Passholder
     */
    email?: string;
    /**
     * This field is always available in responses and ignored in create and update operations.
     * @type {Date}
     * @memberof Passholder
     */
    readonly creationDate?: Date;
    /**
     * Date that the passholder was born.
     * @type {Date}
     * @memberof Passholder
     */
    dateOfBirth: Date;
    /**
     * Gender of the passholder.
     * @type {PassholderGenderEnum}
     * @memberof Passholder
     */
    gender?: PassholderGenderEnum;
    /**
     * 
     * @type {Organizer}
     * @memberof Passholder
     */
    registrationOrganizer?: Organizer;
    /**
     * Amount of points the passholder has currently saved (and not used).This field is always available in responses and ignored in create and update operations.
     * @type {number}
     * @memberof Passholder
     */
    readonly points?: number;
    /**
     * Whether or not the passholder has a an UiTiD registered. This field is always available in responses and ignored in create and update operations.
     * @type {PassholderUitidStatusEnum}
     * @memberof Passholder
     */
    readonly uitidStatus?: PassholderUitidStatusEnum;
    /**
     * 
     * @type {PassholderAddress}
     * @memberof Passholder
     */
    address: PassholderAddress;
    /**
     * Postal code of the municipality that the passholder lives in. Deprecated in favor of `address.postalCode`
     * @type {string}
     * @memberof Passholder
     * @deprecated
     */
    readonly postalCode?: string;
    /**
     * Name of the municipality that the passholder lives in. Deprecated in favor of `address.city`.
     * @type {string}
     * @memberof Passholder
     * @deprecated
     */
    readonly city?: string;
    /**
     * Phone number that the passholder has registered, for example for SMS alerts.
     * @type {string}
     * @memberof Passholder
     */
    phoneNumber?: string;
    /**
     * 
     * @type {PassholderOptInPreferences}
     * @memberof Passholder
     */
    optInPreferences?: PassholderOptInPreferences;
    /**
     * Human-readable name of the passholder's nationality.
     * @type {string}
     * @memberof Passholder
     */
    nationality?: string;
    /**
     * Only used in passholder creation and updates. Set to true for under-aged passholder that have parental consent.
     * @type {boolean}
     * @memberof Passholder
     */
    parentalConsent?: boolean;
    /**
     * Only used in passholder creation and updates. Set to true for passholders that received legal terms on paper.
     * @type {boolean}
     * @memberof Passholder
     */
    legalTermsPaper?: boolean;
    /**
     * Only used in passholder creation and updates. Set to true for passholders that received legal terms digitally.
     * @type {boolean}
     * @memberof Passholder
     */
    legalTermsDigital?: boolean;
    /**
     * Only used in passholder creation. Set to the id of the card system of which the passholder has to become a member.
     * @type {number}
     * @memberof Passholder
     */
    registrationCardSystemId?: number;
    /**
     * Only used in passholder creation when the ser has a price reduction voucher.
     * @type {string}
     * @memberof Passholder
     */
    registrationVoucher?: string;
    /**
     * Only used and mandatory in passholder c
     * @type {PassholderRegistrationCardTypeEnum}
     * @memberof Passholder
     */
    registrationCardType?: PassholderRegistrationCardTypeEnum;
    /**
     * Only used in passholder creation using a physical card.
     * @type {string}
     * @memberof Passholder
     */
    registrationUitpasNumber?: string;
    /**
     * Only used in passholder creation using a `registrationUitpasNumber` with social tariff. Or when updating a passholder with social tariff. During registration, if no `registrationSocialTariffEndDate` is specified and `registrationUitpasNumber` has social tariff, a default date of April 30 of next year is used.
     * @type {Date}
     * @memberof Passholder
     */
    registrationSocialTariffEndDate?: Date;
}


/**
 * @export
 */
export const PassholderGenderEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    X: 'X'
} as const;
export type PassholderGenderEnum = typeof PassholderGenderEnum[keyof typeof PassholderGenderEnum];

/**
 * @export
 */
export const PassholderUitidStatusEnum = {
    Registered: 'REGISTERED',
    Unregistered: 'UNREGISTERED'
} as const;
export type PassholderUitidStatusEnum = typeof PassholderUitidStatusEnum[keyof typeof PassholderUitidStatusEnum];

/**
 * @export
 */
export const PassholderRegistrationCardTypeEnum = {
    Digital: 'DIGITAL',
    NfcCard: 'NFC_CARD'
} as const;
export type PassholderRegistrationCardTypeEnum = typeof PassholderRegistrationCardTypeEnum[keyof typeof PassholderRegistrationCardTypeEnum];


/**
 * Check if a given object implements the Passholder interface.
 */
export function instanceOfPassholder(value: object): value is Passholder {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('dateOfBirth' in value) || value['dateOfBirth'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function PassholderFromJSON(json: any): Passholder {
    return PassholderFromJSONTyped(json, false);
}

export function PassholderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Passholder {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'firstName': json['firstName'],
        'inszNumber': json['inszNumber'] == null ? undefined : json['inszNumber'],
        'uitpasNumber': json['uitpasNumber'] == null ? undefined : json['uitpasNumber'],
        'cardSystemMemberships': json['cardSystemMemberships'] == null ? undefined : ((json['cardSystemMemberships'] as Array<any>).map(CardSystemMembershipFromJSON)),
        'email': json['email'] == null ? undefined : json['email'],
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
        'dateOfBirth': (new Date(json['dateOfBirth'])),
        'gender': json['gender'] == null ? undefined : json['gender'],
        'registrationOrganizer': json['registrationOrganizer'] == null ? undefined : OrganizerFromJSON(json['registrationOrganizer']),
        'points': json['points'] == null ? undefined : json['points'],
        'uitidStatus': json['uitidStatus'] == null ? undefined : json['uitidStatus'],
        'address': PassholderAddressFromJSON(json['address']),
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'city': json['city'] == null ? undefined : json['city'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'optInPreferences': json['optInPreferences'] == null ? undefined : PassholderOptInPreferencesFromJSON(json['optInPreferences']),
        'nationality': json['nationality'] == null ? undefined : json['nationality'],
        'parentalConsent': json['parentalConsent'] == null ? undefined : json['parentalConsent'],
        'legalTermsPaper': json['legalTermsPaper'] == null ? undefined : json['legalTermsPaper'],
        'legalTermsDigital': json['legalTermsDigital'] == null ? undefined : json['legalTermsDigital'],
        'registrationCardSystemId': json['registrationCardSystemId'] == null ? undefined : json['registrationCardSystemId'],
        'registrationVoucher': json['registrationVoucher'] == null ? undefined : json['registrationVoucher'],
        'registrationCardType': json['registrationCardType'] == null ? undefined : json['registrationCardType'],
        'registrationUitpasNumber': json['registrationUitpasNumber'] == null ? undefined : json['registrationUitpasNumber'],
        'registrationSocialTariffEndDate': json['registrationSocialTariffEndDate'] == null ? undefined : (new Date(json['registrationSocialTariffEndDate'])),
    };
}

export function PassholderToJSON(json: any): Passholder {
    return PassholderToJSONTyped(json, false);
}

export function PassholderToJSONTyped(value?: Omit<Passholder, 'id'|'cardSystemMemberships'|'creationDate'|'points'|'uitidStatus'|'postalCode'|'city'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'firstName': value['firstName'],
        'inszNumber': value['inszNumber'],
        'uitpasNumber': value['uitpasNumber'],
        'email': value['email'],
        'dateOfBirth': value['dateOfBirth'].toISOString().substring(0,10),
        'gender': value['gender'],
        'registrationOrganizer': OrganizerToJSON(value['registrationOrganizer']),
        'address': PassholderAddressToJSON(value['address']),
        'phoneNumber': value['phoneNumber'],
        'optInPreferences': PassholderOptInPreferencesToJSON(value['optInPreferences']),
        'nationality': value['nationality'],
        'parentalConsent': value['parentalConsent'],
        'legalTermsPaper': value['legalTermsPaper'],
        'legalTermsDigital': value['legalTermsDigital'],
        'registrationCardSystemId': value['registrationCardSystemId'],
        'registrationVoucher': value['registrationVoucher'],
        'registrationCardType': value['registrationCardType'],
        'registrationUitpasNumber': value['registrationUitpasNumber'],
        'registrationSocialTariffEndDate': value['registrationSocialTariffEndDate'] == null ? value['registrationSocialTariffEndDate'] : value['registrationSocialTariffEndDate'].toISOString().substring(0,10),
    };
}

