/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PassholderPicture
 */
export interface PassholderPicture {
    /**
     * URL of the picture of the passholder.
     * @type {string}
     * @memberof PassholderPicture
     */
    pictureUrl: string;
}

/**
 * Check if a given object implements the PassholderPicture interface.
 */
export function instanceOfPassholderPicture(value: object): value is PassholderPicture {
    if (!('pictureUrl' in value) || value['pictureUrl'] === undefined) return false;
    return true;
}

export function PassholderPictureFromJSON(json: any): PassholderPicture {
    return PassholderPictureFromJSONTyped(json, false);
}

export function PassholderPictureFromJSONTyped(json: any, ignoreDiscriminator: boolean): PassholderPicture {
    if (json == null) {
        return json;
    }
    return {
        
        'pictureUrl': json['pictureUrl'],
    };
}

export function PassholderPictureToJSON(json: any): PassholderPicture {
    return PassholderPictureToJSONTyped(json, false);
}

export function PassholderPictureToJSONTyped(value?: PassholderPicture | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pictureUrl': value['pictureUrl'],
    };
}

