/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional request for social tariff
 * @export
 * @interface PassholderRegistrationRegistrationSocialTariff
 */
export interface PassholderRegistrationRegistrationSocialTariff {
    /**
     * `true` if social tariff is requested for this registration. Always available in responses if `registrationSocialTariff` exists.
     * @type {boolean}
     * @memberof PassholderRegistrationRegistrationSocialTariff
     */
    readonly requested?: boolean;
    /**
     * The Social Tariff Validation ID token of the user. Use the [social tariff validation flow](/reference/uitpas.json/paths/~1social-tariff-validation~1start/get) to obtain such ID tokens. If specified, this token must be valid, contain `hasSocialTariff:true` and the identity fields must match the fields in this registration. In all other cases an error is returned.
     * @type {string}
     * @memberof PassholderRegistrationRegistrationSocialTariff
     */
    idToken?: string;
}

/**
 * Check if a given object implements the PassholderRegistrationRegistrationSocialTariff interface.
 */
export function instanceOfPassholderRegistrationRegistrationSocialTariff(value: object): value is PassholderRegistrationRegistrationSocialTariff {
    return true;
}

export function PassholderRegistrationRegistrationSocialTariffFromJSON(json: any): PassholderRegistrationRegistrationSocialTariff {
    return PassholderRegistrationRegistrationSocialTariffFromJSONTyped(json, false);
}

export function PassholderRegistrationRegistrationSocialTariffFromJSONTyped(json: any, ignoreDiscriminator: boolean): PassholderRegistrationRegistrationSocialTariff {
    if (json == null) {
        return json;
    }
    return {
        
        'requested': json['requested'] == null ? undefined : json['requested'],
        'idToken': json['idToken'] == null ? undefined : json['idToken'],
    };
}

export function PassholderRegistrationRegistrationSocialTariffToJSON(json: any): PassholderRegistrationRegistrationSocialTariff {
    return PassholderRegistrationRegistrationSocialTariffToJSONTyped(json, false);
}

export function PassholderRegistrationRegistrationSocialTariffToJSONTyped(value?: Omit<PassholderRegistrationRegistrationSocialTariff, 'requested'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idToken': value['idToken'],
    };
}

