/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Address that the passholder lives at. Always present in responses. Passholders living outside of Belgium (usually near the border) will only have a `postalCode` and `city` in their address.
 * @export
 * @interface PassholderAddress
 */
export interface PassholderAddress {
    /**
     * Street name, number and optional box number of the address.
     * @type {string}
     * @memberof PassholderAddress
     */
    street?: string;
    /**
     * House number. This field is deprecated and will be empty. The house number is part of the `street` property.
     * @type {string}
     * @memberof PassholderAddress
     * @deprecated
     */
    number?: string;
    /**
     * Postal box number. This field is deprecated and will be empty. The box number is part of the `street` property.
     * @type {string}
     * @memberof PassholderAddress
     * @deprecated
     */
    box?: string;
    /**
     * Postal code of the municipality.
     * @type {string}
     * @memberof PassholderAddress
     */
    postalCode: string;
    /**
     * Human-readable name of the municipality.
     * @type {string}
     * @memberof PassholderAddress
     */
    city: string;
    /**
     * ISO 3166-1 alpha-2 country code.
     * @type {string}
     * @memberof PassholderAddress
     */
    country?: string;
}

/**
 * Check if a given object implements the PassholderAddress interface.
 */
export function instanceOfPassholderAddress(value: object): value is PassholderAddress {
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    return true;
}

export function PassholderAddressFromJSON(json: any): PassholderAddress {
    return PassholderAddressFromJSONTyped(json, false);
}

export function PassholderAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): PassholderAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'street': json['street'] == null ? undefined : json['street'],
        'number': json['number'] == null ? undefined : json['number'],
        'box': json['box'] == null ? undefined : json['box'],
        'postalCode': json['postalCode'],
        'city': json['city'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function PassholderAddressToJSON(json: any): PassholderAddress {
    return PassholderAddressToJSONTyped(json, false);
}

export function PassholderAddressToJSONTyped(value?: PassholderAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'street': value['street'],
        'number': value['number'],
        'box': value['box'],
        'postalCode': value['postalCode'],
        'city': value['city'],
        'country': value['country'],
    };
}

