/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Period entity with a begin and optional end date.
 * @export
 * @interface Period
 */
export interface Period {
    /**
     * Start date of the period (inclusive).
     * @type {Date}
     * @memberof Period
     */
    begin: Date;
    /**
     * End date of the period (inclusive).
     * @type {Date}
     * @memberof Period
     */
    end?: Date;
}

/**
 * Check if a given object implements the Period interface.
 */
export function instanceOfPeriod(value: object): value is Period {
    if (!('begin' in value) || value['begin'] === undefined) return false;
    return true;
}

export function PeriodFromJSON(json: any): Period {
    return PeriodFromJSONTyped(json, false);
}

export function PeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): Period {
    if (json == null) {
        return json;
    }
    return {
        
        'begin': (new Date(json['begin'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
    };
}

export function PeriodToJSON(json: any): Period {
    return PeriodToJSONTyped(json, false);
}

export function PeriodToJSONTyped(value?: Period | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'begin': value['begin'].toISOString(),
        'end': value['end'] == null ? value['end'] : value['end'].toISOString(),
    };
}

