/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Human-readable label of the permission
 * @export
 * @interface PermissionDetailLabel
 */
export interface PermissionDetailLabel {
    /**
     * Human-readable label of the permission in Dutch
     * @type {string}
     * @memberof PermissionDetailLabel
     */
    nl: string;
    /**
     * Human-readable label of the permission in English
     * @type {string}
     * @memberof PermissionDetailLabel
     */
    en?: string;
}

/**
 * Check if a given object implements the PermissionDetailLabel interface.
 */
export function instanceOfPermissionDetailLabel(value: object): value is PermissionDetailLabel {
    if (!('nl' in value) || value['nl'] === undefined) return false;
    return true;
}

export function PermissionDetailLabelFromJSON(json: any): PermissionDetailLabel {
    return PermissionDetailLabelFromJSONTyped(json, false);
}

export function PermissionDetailLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionDetailLabel {
    if (json == null) {
        return json;
    }
    return {
        
        'nl': json['nl'],
        'en': json['en'] == null ? undefined : json['en'],
    };
}

export function PermissionDetailLabelToJSON(json: any): PermissionDetailLabel {
    return PermissionDetailLabelToJSONTyped(json, false);
}

export function PermissionDetailLabelToJSONTyped(value?: PermissionDetailLabel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nl': value['nl'],
        'en': value['en'],
    };
}

