/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionDetailLabel } from './PermissionDetailLabel';
import {
    PermissionDetailLabelFromJSON,
    PermissionDetailLabelFromJSONTyped,
    PermissionDetailLabelToJSON,
    PermissionDetailLabelToJSONTyped,
} from './PermissionDetailLabel';
import type { Permission } from './Permission';
import {
    PermissionFromJSON,
    PermissionFromJSONTyped,
    PermissionToJSON,
    PermissionToJSONTyped,
} from './Permission';

/**
 * Permission details
 * @export
 * @interface PermissionDetail
 */
export interface PermissionDetail {
    /**
     * 
     * @type {Permission}
     * @memberof PermissionDetail
     */
    id: Permission;
    /**
     * 
     * @type {PermissionDetailLabel}
     * @memberof PermissionDetail
     */
    label?: PermissionDetailLabel;
}



/**
 * Check if a given object implements the PermissionDetail interface.
 */
export function instanceOfPermissionDetail(value: object): value is PermissionDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function PermissionDetailFromJSON(json: any): PermissionDetail {
    return PermissionDetailFromJSONTyped(json, false);
}

export function PermissionDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': PermissionFromJSON(json['id']),
        'label': json['label'] == null ? undefined : PermissionDetailLabelFromJSON(json['label']),
    };
}

export function PermissionDetailToJSON(json: any): PermissionDetail {
    return PermissionDetailToJSONTyped(json, false);
}

export function PermissionDetailToJSONTyped(value?: PermissionDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': PermissionToJSON(value['id']),
        'label': PermissionDetailLabelToJSON(value['label']),
    };
}

