/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPassholdersPassholderIdCheckin201Response
 */
export interface PostPassholdersPassholderIdCheckin201Response {
    /**
     * Newly added points as a result of this check-in
     * @type {number}
     * @memberof PostPassholdersPassholderIdCheckin201Response
     */
    addedPoints: number;
    /**
     * Total points of the passholder after this check-in
     * @type {number}
     * @memberof PostPassholdersPassholderIdCheckin201Response
     */
    totalPoints: number;
}

/**
 * Check if a given object implements the PostPassholdersPassholderIdCheckin201Response interface.
 */
export function instanceOfPostPassholdersPassholderIdCheckin201Response(value: object): value is PostPassholdersPassholderIdCheckin201Response {
    if (!('addedPoints' in value) || value['addedPoints'] === undefined) return false;
    if (!('totalPoints' in value) || value['totalPoints'] === undefined) return false;
    return true;
}

export function PostPassholdersPassholderIdCheckin201ResponseFromJSON(json: any): PostPassholdersPassholderIdCheckin201Response {
    return PostPassholdersPassholderIdCheckin201ResponseFromJSONTyped(json, false);
}

export function PostPassholdersPassholderIdCheckin201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPassholdersPassholderIdCheckin201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'addedPoints': json['addedPoints'],
        'totalPoints': json['totalPoints'],
    };
}

export function PostPassholdersPassholderIdCheckin201ResponseToJSON(json: any): PostPassholdersPassholderIdCheckin201Response {
    return PostPassholdersPassholderIdCheckin201ResponseToJSONTyped(json, false);
}

export function PostPassholdersPassholderIdCheckin201ResponseToJSONTyped(value?: PostPassholdersPassholderIdCheckin201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addedPoints': value['addedPoints'],
        'totalPoints': value['totalPoints'],
    };
}

