/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RewardsPaginatedResponseFacet } from './RewardsPaginatedResponseFacet';
import {
    RewardsPaginatedResponseFacetFromJSON,
    RewardsPaginatedResponseFacetFromJSONTyped,
    RewardsPaginatedResponseFacetToJSON,
    RewardsPaginatedResponseFacetToJSONTyped,
} from './RewardsPaginatedResponseFacet';
import type { Reward } from './Reward';
import {
    RewardFromJSON,
    RewardFromJSONTyped,
    RewardToJSON,
    RewardToJSONTyped,
} from './Reward';

/**
 * Paginated response object for rewards
 * @export
 * @interface RewardsPaginatedResponse
 */
export interface RewardsPaginatedResponse {
    /**
     * Total number of reward results (can be more than the amount of results in the response).
     * @type {number}
     * @memberof RewardsPaginatedResponse
     */
    totalItems?: number;
    /**
     * List of reward results for this specific (paginated) request.
     * @type {Array<Reward>}
     * @memberof RewardsPaginatedResponse
     */
    member?: Array<Reward>;
    /**
     * 
     * @type {RewardsPaginatedResponseFacet}
     * @memberof RewardsPaginatedResponse
     */
    facet?: RewardsPaginatedResponseFacet;
}

/**
 * Check if a given object implements the RewardsPaginatedResponse interface.
 */
export function instanceOfRewardsPaginatedResponse(value: object): value is RewardsPaginatedResponse {
    return true;
}

export function RewardsPaginatedResponseFromJSON(json: any): RewardsPaginatedResponse {
    return RewardsPaginatedResponseFromJSONTyped(json, false);
}

export function RewardsPaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RewardsPaginatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'member': json['member'] == null ? undefined : ((json['member'] as Array<any>).map(RewardFromJSON)),
        'facet': json['facet'] == null ? undefined : RewardsPaginatedResponseFacetFromJSON(json['facet']),
    };
}

export function RewardsPaginatedResponseToJSON(json: any): RewardsPaginatedResponse {
    return RewardsPaginatedResponseToJSONTyped(json, false);
}

export function RewardsPaginatedResponseToJSONTyped(value?: RewardsPaginatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalItems': value['totalItems'],
        'member': value['member'] == null ? undefined : ((value['member'] as Array<any>).map(RewardToJSON)),
        'facet': RewardsPaginatedResponseFacetToJSON(value['facet']),
    };
}

