/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * SocialTariffValidationTokenRequest
 * @export
 * @interface SocialTariffValidationTokenResponse
 */
export interface SocialTariffValidationTokenResponse {
    /**
     * code from step 2 in the authentication process
     * @type {string}
     * @memberof SocialTariffValidationTokenResponse
     */
    token: string;
}

/**
 * Check if a given object implements the SocialTariffValidationTokenResponse interface.
 */
export function instanceOfSocialTariffValidationTokenResponse(value: object): value is SocialTariffValidationTokenResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function SocialTariffValidationTokenResponseFromJSON(json: any): SocialTariffValidationTokenResponse {
    return SocialTariffValidationTokenResponseFromJSONTyped(json, false);
}

export function SocialTariffValidationTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialTariffValidationTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function SocialTariffValidationTokenResponseToJSON(json: any): SocialTariffValidationTokenResponse {
    return SocialTariffValidationTokenResponseToJSONTyped(json, false);
}

export function SocialTariffValidationTokenResponseToJSONTyped(value?: SocialTariffValidationTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

