/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional property that, if provided, contains information for the end-user about potentially unavailable tariffs (while the end user might expect otherwise). e.g. if no tariff of type `SOCIALTARIFF` is available, while the passholder has a valid social tariff, this field can contain a human-readable explanation of the problem, specifically for end-users, in one or more languages. An `nl` value is always provided, other languages may be provided. When this property is included, it is strongly encouraged to show this to the end-user. It is also important to note that this message is context-aware: e.g. when filtering tariffs on `type=SOCIALTARIFF`, this message won't include information about coupons. Furthermore keep in mind this 'end user message' does not necessarily contain a fatal error. A message might be relevant to show while there are still other tariffs available.
 * @export
 * @interface TariffsResponseEndUserMessage
 */
export interface TariffsResponseEndUserMessage {
    /**
     * A human-readable explanation of the problem, specifically for end-users, localized in Dutch.
     * @type {string}
     * @memberof TariffsResponseEndUserMessage
     */
    nl: string;
    /**
     * A human-readable explanation of the problem, specifically for end-users, localized in French.
     * @type {string}
     * @memberof TariffsResponseEndUserMessage
     */
    fr?: string;
    /**
     * A human-readable explanation of the problem, specifically for end-users, localized in German.
     * @type {string}
     * @memberof TariffsResponseEndUserMessage
     */
    de?: string;
    /**
     * A human-readable explanation of the problem, specifically for end-users, localized in English.
     * @type {string}
     * @memberof TariffsResponseEndUserMessage
     */
    en?: string;
}

/**
 * Check if a given object implements the TariffsResponseEndUserMessage interface.
 */
export function instanceOfTariffsResponseEndUserMessage(value: object): value is TariffsResponseEndUserMessage {
    if (!('nl' in value) || value['nl'] === undefined) return false;
    return true;
}

export function TariffsResponseEndUserMessageFromJSON(json: any): TariffsResponseEndUserMessage {
    return TariffsResponseEndUserMessageFromJSONTyped(json, false);
}

export function TariffsResponseEndUserMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TariffsResponseEndUserMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'nl': json['nl'],
        'fr': json['fr'] == null ? undefined : json['fr'],
        'de': json['de'] == null ? undefined : json['de'],
        'en': json['en'] == null ? undefined : json['en'],
    };
}

export function TariffsResponseEndUserMessageToJSON(json: any): TariffsResponseEndUserMessage {
    return TariffsResponseEndUserMessageToJSONTyped(json, false);
}

export function TariffsResponseEndUserMessageToJSONTyped(value?: TariffsResponseEndUserMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nl': value['nl'],
        'fr': value['fr'],
        'de': value['de'],
        'en': value['en'],
    };
}

