/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
    TransactionToJSONTyped,
} from './Transaction';

/**
 * Paginated response object for transactions
 * @export
 * @interface TransactionsPaginatedCollection
 */
export interface TransactionsPaginatedCollection {
    /**
     * Total number of card system results (can be more than the amount of results in the response).
     * @type {number}
     * @memberof TransactionsPaginatedCollection
     */
    totalItems?: number;
    /**
     * List of card system results for this specific (paginated) request.
     * @type {Array<Transaction>}
     * @memberof TransactionsPaginatedCollection
     */
    member?: Array<Transaction>;
}

/**
 * Check if a given object implements the TransactionsPaginatedCollection interface.
 */
export function instanceOfTransactionsPaginatedCollection(value: object): value is TransactionsPaginatedCollection {
    return true;
}

export function TransactionsPaginatedCollectionFromJSON(json: any): TransactionsPaginatedCollection {
    return TransactionsPaginatedCollectionFromJSONTyped(json, false);
}

export function TransactionsPaginatedCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsPaginatedCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'member': json['member'] == null ? undefined : ((json['member'] as Array<any>).map(TransactionFromJSON)),
    };
}

export function TransactionsPaginatedCollectionToJSON(json: any): TransactionsPaginatedCollection {
    return TransactionsPaginatedCollectionToJSONTyped(json, false);
}

export function TransactionsPaginatedCollectionToJSONTyped(value?: TransactionsPaginatedCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalItems': value['totalItems'],
        'member': value['member'] == null ? undefined : ((value['member'] as Array<any>).map(TransactionToJSON)),
    };
}

