/* tslint:disable */
/* eslint-disable */
/**
 * UiTPAS API
 * With UiTPAS API 4.0 you can retrieve ticket prices and register ticket sales for passholders. You can also save UiTPAS points and exchange them for rewards for a passholder, and much more.
 *
 * The version of the OpenAPI document: 4.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Transaction
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * Title of the transaction
     * @type {string}
     * @memberof Transaction
     */
    readonly title: string;
    /**
     * Location of the transaction
     * @type {string}
     * @memberof Transaction
     */
    readonly location: string;
    /**
     * Creationdate of the transaction
     * @type {Date}
     * @memberof Transaction
     */
    readonly creationDate: Date;
    /**
     * Points of the transaction. Extra points (e.g. at check-in) are positive numbers. Used points (e.g. redeeming a reward) are negative numbers.
     * @type {number}
     * @memberof Transaction
     */
    readonly points: number;
}

/**
 * Check if a given object implements the Transaction interface.
 */
export function instanceOfTransaction(value: object): value is Transaction {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    if (!('points' in value) || value['points'] === undefined) return false;
    return true;
}

export function TransactionFromJSON(json: any): Transaction {
    return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'location': json['location'],
        'creationDate': (new Date(json['creationDate'])),
        'points': json['points'],
    };
}

export function TransactionToJSON(json: any): Transaction {
    return TransactionToJSONTyped(json, false);
}

export function TransactionToJSONTyped(value?: Omit<Transaction, 'title'|'location'|'creationDate'|'points'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

