/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A taxonomy term used to categorize events.
 * 
 * All events require exactly one term of the `eventtype` domain, and can optionally contain other terms.
 * 
 * When reading events, all properties will be available. When creating or updating events only the `id` is required to be included.
 * @export
 * @interface EventTermsInner
 */
export interface EventTermsInner {
    /**
     * Unique id of the term. For example `0.50.4.0.0`.
     * @type {string}
     * @memberof EventTermsInner
     */
    id: string;
    /**
     * Human-readable label of the term. Currently only available in Dutch. For example `Concert`.
     * @type {string}
     * @memberof EventTermsInner
     */
    label?: string;
    /**
     * The domain of the term. Can be one of `eventtype`, `theme`, or `facility`.
     * @type {EventTermsInnerDomainEnum}
     * @memberof EventTermsInner
     */
    domain?: EventTermsInnerDomainEnum;
}


/**
 * @export
 */
export const EventTermsInnerDomainEnum = {
    Eventtype: 'eventtype',
    Theme: 'theme',
    Facility: 'facility'
} as const;
export type EventTermsInnerDomainEnum = typeof EventTermsInnerDomainEnum[keyof typeof EventTermsInnerDomainEnum];


/**
 * Check if a given object implements the EventTermsInner interface.
 */
export function instanceOfEventTermsInner(value: object): value is EventTermsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function EventTermsInnerFromJSON(json: any): EventTermsInner {
    return EventTermsInnerFromJSONTyped(json, false);
}

export function EventTermsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventTermsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'domain': json['domain'] == null ? undefined : json['domain'],
    };
}

export function EventTermsInnerToJSON(json: any): EventTermsInner {
    return EventTermsInnerToJSONTyped(json, false);
}

export function EventTermsInnerToJSONTyped(value?: EventTermsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'domain': value['domain'],
    };
}

