/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonBookingAvailabilityType } from './CommonBookingAvailabilityType';
import {
    CommonBookingAvailabilityTypeFromJSON,
    CommonBookingAvailabilityTypeFromJSONTyped,
    CommonBookingAvailabilityTypeToJSON,
    CommonBookingAvailabilityTypeToJSONTyped,
} from './CommonBookingAvailabilityType';

/**
 * Indicates whether the event still has tickets or reservations available. Currently contains a `type` that can be `Available` or `Unavailable`, and can optionally include capacity information.
 * @export
 * @interface EventBookingAvailability
 */
export interface EventBookingAvailability {
    /**
     * 
     * @type {CommonBookingAvailabilityType}
     * @memberof EventBookingAvailability
     */
    type: CommonBookingAvailabilityType;
    /**
     * Total number of seats or tickets.
     * @type {number}
     * @memberof EventBookingAvailability
     */
    capacity?: number;
}



/**
 * Check if a given object implements the EventBookingAvailability interface.
 */
export function instanceOfEventBookingAvailability(value: object): value is EventBookingAvailability {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function EventBookingAvailabilityFromJSON(json: any): EventBookingAvailability {
    return EventBookingAvailabilityFromJSONTyped(json, false);
}

export function EventBookingAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventBookingAvailability {
    if (json == null) {
        return json;
    }
    return {
        
        'type': CommonBookingAvailabilityTypeFromJSON(json['type']),
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
    };
}

export function EventBookingAvailabilityToJSON(json: any): EventBookingAvailability {
    return EventBookingAvailabilityToJSONTyped(json, false);
}

export function EventBookingAvailabilityToJSONTyped(value?: EventBookingAvailability | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': CommonBookingAvailabilityTypeToJSON(value['type']),
        'capacity': value['capacity'],
    };
}

