/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventBookingInfo } from './EventBookingInfo';
import {
    EventBookingInfoFromJSON,
    EventBookingInfoFromJSONTyped,
    EventBookingInfoToJSON,
    EventBookingInfoToJSONTyped,
} from './EventBookingInfo';
import type { EventSubEventChildcare } from './EventSubEventChildcare';
import {
    EventSubEventChildcareFromJSON,
    EventSubEventChildcareFromJSONTyped,
    EventSubEventChildcareToJSON,
    EventSubEventChildcareToJSONTyped,
} from './EventSubEventChildcare';
import type { EventSubEventPatchInnerBookingAvailability } from './EventSubEventPatchInnerBookingAvailability';
import {
    EventSubEventPatchInnerBookingAvailabilityFromJSON,
    EventSubEventPatchInnerBookingAvailabilityFromJSONTyped,
    EventSubEventPatchInnerBookingAvailabilityToJSON,
    EventSubEventPatchInnerBookingAvailabilityToJSONTyped,
} from './EventSubEventPatchInnerBookingAvailability';
import type { EventSubEventPatchInnerStatus } from './EventSubEventPatchInnerStatus';
import {
    EventSubEventPatchInnerStatusFromJSON,
    EventSubEventPatchInnerStatusFromJSONTyped,
    EventSubEventPatchInnerStatusToJSON,
    EventSubEventPatchInnerStatusToJSONTyped,
} from './EventSubEventPatchInnerStatus';

/**
 * 
 * @export
 * @interface EventSubEventPatchInner
 */
export interface EventSubEventPatchInner {
    /**
     * Index of the subEvent to update on the parent event. `0` for the first subEvent, `1` for the second event, and so on.
     * @type {number}
     * @memberof EventSubEventPatchInner
     */
    id: number;
    /**
     * The date & time that the subEvent starts.
     * @type {Date}
     * @memberof EventSubEventPatchInner
     */
    startDate?: Date;
    /**
     * The date & time that the subEvent ends.
     * @type {Date}
     * @memberof EventSubEventPatchInner
     */
    endDate?: Date;
    /**
     * Childcare information for this sub event. If this property is omitted entirely, the existing childcare data will not be altered. If included, each property present is set and each property omitted is cleared. Send an empty object (`{}`) to clear both `start` and `end`.
     * @type {EventSubEventChildcare}
     * @memberof EventSubEventPatchInner
     */
    childcare?: EventSubEventChildcare;
    /**
     * 
     * @type {EventSubEventPatchInnerStatus}
     * @memberof EventSubEventPatchInner
     */
    status?: EventSubEventPatchInnerStatus;
    /**
     * 
     * @type {EventSubEventPatchInnerBookingAvailability}
     * @memberof EventSubEventPatchInner
     */
    bookingAvailability?: EventSubEventPatchInnerBookingAvailability | null;
    /**
     * 
     * @type {EventBookingInfo}
     * @memberof EventSubEventPatchInner
     */
    bookingInfo?: EventBookingInfo;
    /**
     * Indicates whether this occurrence involves an overnight stay. Only accepted when the event has a term with id `0.57.0.0.0` ("Kamp of vakantie"). Defaults to `false` when omitted. Automatically reset to `false` when term `0.57.0.0.0` is removed from the event.
     * @type {boolean}
     * @memberof EventSubEventPatchInner
     */
    overnight?: boolean;
}

/**
 * Check if a given object implements the EventSubEventPatchInner interface.
 */
export function instanceOfEventSubEventPatchInner(value: object): value is EventSubEventPatchInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function EventSubEventPatchInnerFromJSON(json: any): EventSubEventPatchInner {
    return EventSubEventPatchInnerFromJSONTyped(json, false);
}

export function EventSubEventPatchInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventSubEventPatchInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'childcare': json['childcare'] == null ? undefined : EventSubEventChildcareFromJSON(json['childcare']),
        'status': json['status'] == null ? undefined : EventSubEventPatchInnerStatusFromJSON(json['status']),
        'bookingAvailability': json['bookingAvailability'] == null ? undefined : EventSubEventPatchInnerBookingAvailabilityFromJSON(json['bookingAvailability']),
        'bookingInfo': json['bookingInfo'] == null ? undefined : EventBookingInfoFromJSON(json['bookingInfo']),
        'overnight': json['overnight'] == null ? undefined : json['overnight'],
    };
}

export function EventSubEventPatchInnerToJSON(json: any): EventSubEventPatchInner {
    return EventSubEventPatchInnerToJSONTyped(json, false);
}

export function EventSubEventPatchInnerToJSONTyped(value?: EventSubEventPatchInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'childcare': EventSubEventChildcareToJSON(value['childcare']),
        'status': EventSubEventPatchInnerStatusToJSON(value['status']),
        'bookingAvailability': EventSubEventPatchInnerBookingAvailabilityToJSON(value['bookingAvailability']),
        'bookingInfo': EventBookingInfoToJSON(value['bookingInfo']),
        'overnight': value['overnight'],
    };
}

