/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventPost201Response
 */
export interface EventPost201Response {
    /**
     * UUID of the created event to use in subsequent requests or to store as a reference in your application.
     * @type {string}
     * @memberof EventPost201Response
     */
    id: string;
    /**
     * Deprecated, use `id` instead.
     * @type {string}
     * @memberof EventPost201Response
     * @deprecated
     */
    eventId: string;
    /**
     * URL of the created event to use in subsequent requests or to store as a reference in your application.
     * @type {string}
     * @memberof EventPost201Response
     */
    url: string;
    /**
     * ID of the last internal command that was dispatched for this operation. Will be removed in the future.
     * @type {string}
     * @memberof EventPost201Response
     * @deprecated
     */
    commandId?: string;
}

/**
 * Check if a given object implements the EventPost201Response interface.
 */
export function instanceOfEventPost201Response(value: object): value is EventPost201Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function EventPost201ResponseFromJSON(json: any): EventPost201Response {
    return EventPost201ResponseFromJSONTyped(json, false);
}

export function EventPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'eventId': json['eventId'],
        'url': json['url'],
        'commandId': json['commandId'] == null ? undefined : json['commandId'],
    };
}

export function EventPost201ResponseToJSON(json: any): EventPost201Response {
    return EventPost201ResponseToJSONTyped(json, false);
}

export function EventPost201ResponseToJSONTyped(value?: EventPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'eventId': value['eventId'],
        'url': value['url'],
        'commandId': value['commandId'],
    };
}

