/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The production that the [event](./models/event.json) belongs to.
 * 
 * A production is a group of events that share the same subject but are taking place in different locations and/or are organized by different organizers.
 * 
 * For example a theatre show that is scheduled to be performed at different locations, or a movie that will be screened at different cinema's.
 * @export
 * @interface EventProduction
 */
export interface EventProduction {
    /**
     * The unique id of the production, formatted as UUID. For example `10ce7cb1-7bc9-4ce4-a256-460f56c49965`.
     * @type {string}
     * @memberof EventProduction
     */
    id: string;
    /**
     * The human-readable name of the production. Not localized but in the original language of the events. Automatically added by UiTdatabank.
     * @type {string}
     * @memberof EventProduction
     */
    title: string;
    /**
     * A list of globally unique URIs of other events that are part of this production. See also [@id](./event-@id.json). Automatically added by UiTdatabank.
     * @type {Array<string>}
     * @memberof EventProduction
     */
    otherEvents: Array<string>;
}

/**
 * Check if a given object implements the EventProduction interface.
 */
export function instanceOfEventProduction(value: object): value is EventProduction {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('otherEvents' in value) || value['otherEvents'] === undefined) return false;
    return true;
}

export function EventProductionFromJSON(json: any): EventProduction {
    return EventProductionFromJSONTyped(json, false);
}

export function EventProductionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventProduction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'otherEvents': json['otherEvents'],
    };
}

export function EventProductionToJSON(json: any): EventProduction {
    return EventProductionToJSONTyped(json, false);
}

export function EventProductionToJSONTyped(value?: EventProduction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'otherEvents': value['otherEvents'],
    };
}

