/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The main language that the [event](./models/event.json) is described in. All localized properties like [name](./models/event-name.json) and [description](./models/event-description.json) will be required to have at least a value for this language.
 * 
 * Can be one of `nl`, `fr`, `de`, or `en`.
 * @export
 */
export const EventMainLanguage = {
    Nl: 'nl',
    Fr: 'fr',
    De: 'de',
    En: 'en'
} as const;
export type EventMainLanguage = typeof EventMainLanguage[keyof typeof EventMainLanguage];


export function instanceOfEventMainLanguage(value: any): boolean {
    for (const key in EventMainLanguage) {
        if (Object.prototype.hasOwnProperty.call(EventMainLanguage, key)) {
            if (EventMainLanguage[key as keyof typeof EventMainLanguage] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EventMainLanguageFromJSON(json: any): EventMainLanguage {
    return EventMainLanguageFromJSONTyped(json, false);
}

export function EventMainLanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventMainLanguage {
    return json as EventMainLanguage;
}

export function EventMainLanguageToJSON(value?: EventMainLanguage | null): any {
    return value as any;
}

export function EventMainLanguageToJSONTyped(value: any, ignoreDiscriminator: boolean): EventMainLanguage {
    return value as EventMainLanguage;
}

