/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventAttendanceMode } from './EventAttendanceMode';
import {
    EventAttendanceModeFromJSON,
    EventAttendanceModeFromJSONTyped,
    EventAttendanceModeToJSON,
    EventAttendanceModeToJSONTyped,
} from './EventAttendanceMode';

/**
 * 
 * @export
 * @interface EventAttendanceModePut
 */
export interface EventAttendanceModePut {
    /**
     * 
     * @type {EventAttendanceMode}
     * @memberof EventAttendanceModePut
     */
    attendanceMode: EventAttendanceMode;
    /**
     * A unique URI that acts as globally unique ID for the [place](./models/place.json). Based on (JSON-LD node identifiers)[https://www.w3.org/TR/json-ld/#node-identifiers].
     * @type {string}
     * @memberof EventAttendanceModePut
     */
    location?: string;
}



/**
 * Check if a given object implements the EventAttendanceModePut interface.
 */
export function instanceOfEventAttendanceModePut(value: object): value is EventAttendanceModePut {
    if (!('attendanceMode' in value) || value['attendanceMode'] === undefined) return false;
    return true;
}

export function EventAttendanceModePutFromJSON(json: any): EventAttendanceModePut {
    return EventAttendanceModePutFromJSONTyped(json, false);
}

export function EventAttendanceModePutFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventAttendanceModePut {
    if (json == null) {
        return json;
    }
    return {
        
        'attendanceMode': EventAttendanceModeFromJSON(json['attendanceMode']),
        'location': json['location'] == null ? undefined : json['location'],
    };
}

export function EventAttendanceModePutToJSON(json: any): EventAttendanceModePut {
    return EventAttendanceModePutToJSONTyped(json, false);
}

export function EventAttendanceModePutToJSONTyped(value?: EventAttendanceModePut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attendanceMode': EventAttendanceModeToJSON(value['attendanceMode']),
        'location': value['location'],
    };
}

