/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventWorkflowStatus } from './EventWorkflowStatus';
import {
    EventWorkflowStatusFromJSON,
    EventWorkflowStatusFromJSONTyped,
    EventWorkflowStatusToJSON,
    EventWorkflowStatusToJSONTyped,
} from './EventWorkflowStatus';

/**
 * 
 * @export
 * @interface EventWorkflowStatusPut
 */
export interface EventWorkflowStatusPut {
    /**
     * 
     * @type {EventWorkflowStatus}
     * @memberof EventWorkflowStatusPut
     */
    workflowStatus: EventWorkflowStatus;
    /**
     * Can be set when changing the workflowStatus to `READY_FOR_VALIDATION`. The first date & time that the [event](./models/event.json) is allowed to be visible on publication channels. If omitted when changing the workflowStatus to `READY_FOR_VALIDATION`, the current datetime will be used. Must be formatted as an ISO-8601 datetime.
     * @type {Date}
     * @memberof EventWorkflowStatusPut
     */
    availableFrom?: Date;
    /**
     * Required when setting the workflowStatus to `REJECTED` (only possible with permission to moderate events). The reason why the event was rejected.
     * @type {string}
     * @memberof EventWorkflowStatusPut
     */
    reason?: string;
}



/**
 * Check if a given object implements the EventWorkflowStatusPut interface.
 */
export function instanceOfEventWorkflowStatusPut(value: object): value is EventWorkflowStatusPut {
    if (!('workflowStatus' in value) || value['workflowStatus'] === undefined) return false;
    return true;
}

export function EventWorkflowStatusPutFromJSON(json: any): EventWorkflowStatusPut {
    return EventWorkflowStatusPutFromJSONTyped(json, false);
}

export function EventWorkflowStatusPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventWorkflowStatusPut {
    if (json == null) {
        return json;
    }
    return {
        
        'workflowStatus': EventWorkflowStatusFromJSON(json['workflowStatus']),
        'availableFrom': json['availableFrom'] == null ? undefined : (new Date(json['availableFrom'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function EventWorkflowStatusPutToJSON(json: any): EventWorkflowStatusPut {
    return EventWorkflowStatusPutToJSONTyped(json, false);
}

export function EventWorkflowStatusPutToJSONTyped(value?: EventWorkflowStatusPut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workflowStatus': EventWorkflowStatusToJSON(value['workflowStatus']),
        'availableFrom': value['availableFrom'] == null ? value['availableFrom'] : value['availableFrom'].toISOString(),
        'reason': value['reason'],
    };
}

