/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The reason of the status on the event, as a localized human-readable text.
 * @export
 * @interface EventSubEventPatchInnerStatusReason
 */
export interface EventSubEventPatchInnerStatusReason {
    /**
     * Dutch reason
     * @type {string}
     * @memberof EventSubEventPatchInnerStatusReason
     */
    nl?: string;
    /**
     * French reason
     * @type {string}
     * @memberof EventSubEventPatchInnerStatusReason
     */
    fr?: string;
    /**
     * German reason
     * @type {string}
     * @memberof EventSubEventPatchInnerStatusReason
     */
    de?: string;
    /**
     * English reason
     * @type {string}
     * @memberof EventSubEventPatchInnerStatusReason
     */
    en?: string;
}

/**
 * Check if a given object implements the EventSubEventPatchInnerStatusReason interface.
 */
export function instanceOfEventSubEventPatchInnerStatusReason(value: object): value is EventSubEventPatchInnerStatusReason {
    return true;
}

export function EventSubEventPatchInnerStatusReasonFromJSON(json: any): EventSubEventPatchInnerStatusReason {
    return EventSubEventPatchInnerStatusReasonFromJSONTyped(json, false);
}

export function EventSubEventPatchInnerStatusReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventSubEventPatchInnerStatusReason {
    if (json == null) {
        return json;
    }
    return {
        
        'nl': json['nl'] == null ? undefined : json['nl'],
        'fr': json['fr'] == null ? undefined : json['fr'],
        'de': json['de'] == null ? undefined : json['de'],
        'en': json['en'] == null ? undefined : json['en'],
    };
}

export function EventSubEventPatchInnerStatusReasonToJSON(json: any): EventSubEventPatchInnerStatusReason {
    return EventSubEventPatchInnerStatusReasonToJSONTyped(json, false);
}

export function EventSubEventPatchInnerStatusReasonToJSONTyped(value?: EventSubEventPatchInnerStatusReason | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nl': value['nl'],
        'fr': value['fr'],
        'de': value['de'],
        'en': value['en'],
    };
}

