/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * HTML represenation of the date of the event / place
 * @export
 * @interface OfferCalendarSummaryDetailHtml
 */
export interface OfferCalendarSummaryDetailHtml {
    /**
     * Extra date label in HTML
     * @type {string}
     * @memberof OfferCalendarSummaryDetailHtml
     */
    xs?: string;
    /**
     * Small date in HTML
     * @type {string}
     * @memberof OfferCalendarSummaryDetailHtml
     */
    sm?: string;
    /**
     * Medium date in HTML
     * @type {string}
     * @memberof OfferCalendarSummaryDetailHtml
     */
    md?: string;
    /**
     * Large date in HTML
     * @type {string}
     * @memberof OfferCalendarSummaryDetailHtml
     */
    lg?: string;
}

/**
 * Check if a given object implements the OfferCalendarSummaryDetailHtml interface.
 */
export function instanceOfOfferCalendarSummaryDetailHtml(value: object): value is OfferCalendarSummaryDetailHtml {
    return true;
}

export function OfferCalendarSummaryDetailHtmlFromJSON(json: any): OfferCalendarSummaryDetailHtml {
    return OfferCalendarSummaryDetailHtmlFromJSONTyped(json, false);
}

export function OfferCalendarSummaryDetailHtmlFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfferCalendarSummaryDetailHtml {
    if (json == null) {
        return json;
    }
    return {
        
        'xs': json['xs'] == null ? undefined : json['xs'],
        'sm': json['sm'] == null ? undefined : json['sm'],
        'md': json['md'] == null ? undefined : json['md'],
        'lg': json['lg'] == null ? undefined : json['lg'],
    };
}

export function OfferCalendarSummaryDetailHtmlToJSON(json: any): OfferCalendarSummaryDetailHtml {
    return OfferCalendarSummaryDetailHtmlToJSONTyped(json, false);
}

export function OfferCalendarSummaryDetailHtmlToJSONTyped(value?: OfferCalendarSummaryDetailHtml | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'xs': value['xs'],
        'sm': value['sm'],
        'md': value['md'],
        'lg': value['lg'],
    };
}

