/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of the [organizer](./models/organizer.json) in the moderation workflow.
 * 
 * Can be one of two values:
 * 
 * - `ACTIVE`: The organizer is created and can be used.
 * - `DELETED`: The organizer was deleted and should not be visible on any publication channels.
 * @export
 */
export const OrganizerWorkflowStatus = {
    Active: 'ACTIVE',
    Deleted: 'DELETED'
} as const;
export type OrganizerWorkflowStatus = typeof OrganizerWorkflowStatus[keyof typeof OrganizerWorkflowStatus];


export function instanceOfOrganizerWorkflowStatus(value: any): boolean {
    for (const key in OrganizerWorkflowStatus) {
        if (Object.prototype.hasOwnProperty.call(OrganizerWorkflowStatus, key)) {
            if (OrganizerWorkflowStatus[key as keyof typeof OrganizerWorkflowStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OrganizerWorkflowStatusFromJSON(json: any): OrganizerWorkflowStatus {
    return OrganizerWorkflowStatusFromJSONTyped(json, false);
}

export function OrganizerWorkflowStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerWorkflowStatus {
    return json as OrganizerWorkflowStatus;
}

export function OrganizerWorkflowStatusToJSON(value?: OrganizerWorkflowStatus | null): any {
    return value as any;
}

export function OrganizerWorkflowStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): OrganizerWorkflowStatus {
    return value as OrganizerWorkflowStatus;
}

