/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A list of labels that can be used to categorize the [organizer](./models/organizer.json).
 * @export
 * @interface OrganizerLabelsPut
 */
export interface OrganizerLabelsPut {
    /**
     * A list of multiple labels, can be left empty.
     * @type {Array<string>}
     * @memberof OrganizerLabelsPut
     */
    labels: Array<string>;
}

/**
 * Check if a given object implements the OrganizerLabelsPut interface.
 */
export function instanceOfOrganizerLabelsPut(value: object): value is OrganizerLabelsPut {
    if (!('labels' in value) || value['labels'] === undefined) return false;
    return true;
}

export function OrganizerLabelsPutFromJSON(json: any): OrganizerLabelsPut {
    return OrganizerLabelsPutFromJSONTyped(json, false);
}

export function OrganizerLabelsPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerLabelsPut {
    if (json == null) {
        return json;
    }
    return {
        
        'labels': json['labels'],
    };
}

export function OrganizerLabelsPutToJSON(json: any): OrganizerLabelsPut {
    return OrganizerLabelsPutToJSONTyped(json, false);
}

export function OrganizerLabelsPutToJSONTyped(value?: OrganizerLabelsPut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'labels': value['labels'],
    };
}

