/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizerImagesPatchInner
 */
export interface OrganizerImagesPatchInner {
    /**
     * The unique id (generated by UiTdatabank) of the image. 
     * @type {string}
     * @memberof OrganizerImagesPatchInner
     */
    id: string;
    /**
     * The language of the image or description.
     * Can be one of `nl`, `fr`, `de`, or `en`.
     * @type {OrganizerImagesPatchInnerLanguageEnum}
     * @memberof OrganizerImagesPatchInner
     */
    language?: OrganizerImagesPatchInnerLanguageEnum;
    /**
     * The copyright holder of the image.
     * @type {string}
     * @memberof OrganizerImagesPatchInner
     */
    copyrightHolder?: string;
    /**
     * Description of the image object, in the language used in the `language` property of the image object.
     * @type {string}
     * @memberof OrganizerImagesPatchInner
     */
    description?: string;
}


/**
 * @export
 */
export const OrganizerImagesPatchInnerLanguageEnum = {
    Nl: 'nl',
    Fr: 'fr',
    De: 'de',
    En: 'en'
} as const;
export type OrganizerImagesPatchInnerLanguageEnum = typeof OrganizerImagesPatchInnerLanguageEnum[keyof typeof OrganizerImagesPatchInnerLanguageEnum];


/**
 * Check if a given object implements the OrganizerImagesPatchInner interface.
 */
export function instanceOfOrganizerImagesPatchInner(value: object): value is OrganizerImagesPatchInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function OrganizerImagesPatchInnerFromJSON(json: any): OrganizerImagesPatchInner {
    return OrganizerImagesPatchInnerFromJSONTyped(json, false);
}

export function OrganizerImagesPatchInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerImagesPatchInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'language': json['language'] == null ? undefined : json['language'],
        'copyrightHolder': json['copyrightHolder'] == null ? undefined : json['copyrightHolder'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function OrganizerImagesPatchInnerToJSON(json: any): OrganizerImagesPatchInner {
    return OrganizerImagesPatchInnerToJSONTyped(json, false);
}

export function OrganizerImagesPatchInnerToJSONTyped(value?: OrganizerImagesPatchInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'language': value['language'],
        'copyrightHolder': value['copyrightHolder'],
        'description': value['description'],
    };
}

