/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaceWorkflowStatus } from './PlaceWorkflowStatus';
import {
    PlaceWorkflowStatusFromJSON,
    PlaceWorkflowStatusFromJSONTyped,
    PlaceWorkflowStatusToJSON,
    PlaceWorkflowStatusToJSONTyped,
} from './PlaceWorkflowStatus';

/**
 * 
 * @export
 * @interface PlaceWorkflowStatusPut
 */
export interface PlaceWorkflowStatusPut {
    /**
     * 
     * @type {PlaceWorkflowStatus}
     * @memberof PlaceWorkflowStatusPut
     */
    workflowStatus: PlaceWorkflowStatus;
    /**
     * Can be set when changing the workflowStatus to `READY_FOR_VALIDATION`. The first date & time that the [place](./models/place.json) is allowed to be visible on publication channels. If omitted when changing the workflowStatus to `READY_FOR_VALIDATION`, the current datetime will be used. Must be formatted as an ISO-8601 datetime.
     * @type {Date}
     * @memberof PlaceWorkflowStatusPut
     */
    availableFrom?: Date;
    /**
     * Required when setting the workflowStatus to `REJECTED` (only possible with permission to moderate events). The reason why the event was rejected.
     * @type {string}
     * @memberof PlaceWorkflowStatusPut
     */
    reason?: string;
}



/**
 * Check if a given object implements the PlaceWorkflowStatusPut interface.
 */
export function instanceOfPlaceWorkflowStatusPut(value: object): value is PlaceWorkflowStatusPut {
    if (!('workflowStatus' in value) || value['workflowStatus'] === undefined) return false;
    return true;
}

export function PlaceWorkflowStatusPutFromJSON(json: any): PlaceWorkflowStatusPut {
    return PlaceWorkflowStatusPutFromJSONTyped(json, false);
}

export function PlaceWorkflowStatusPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceWorkflowStatusPut {
    if (json == null) {
        return json;
    }
    return {
        
        'workflowStatus': PlaceWorkflowStatusFromJSON(json['workflowStatus']),
        'availableFrom': json['availableFrom'] == null ? undefined : (new Date(json['availableFrom'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function PlaceWorkflowStatusPutToJSON(json: any): PlaceWorkflowStatusPut {
    return PlaceWorkflowStatusPutToJSONTyped(json, false);
}

export function PlaceWorkflowStatusPutToJSONTyped(value?: PlaceWorkflowStatusPut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workflowStatus': PlaceWorkflowStatusToJSON(value['workflowStatus']),
        'availableFrom': value['availableFrom'] == null ? value['availableFrom'] : value['availableFrom'].toISOString(),
        'reason': value['reason'],
    };
}

