/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Geographic coordinates corresponding to the [address](./models/place-address.json) the place is located at. Calculated automatically by UiTdatabank.
 * @export
 * @interface PlaceGeo
 */
export interface PlaceGeo {
    /**
     * A geographic coordinate that specifies the north–south position of a point on the Earth's surface from the equator to one of the poles.
     * @type {number}
     * @memberof PlaceGeo
     */
    latitude: number;
    /**
     * A geographic coordinate that specifies the east–west position of a point on the Earth's surface from Greenwich, England.
     * @type {number}
     * @memberof PlaceGeo
     */
    longitude: number;
}

/**
 * Check if a given object implements the PlaceGeo interface.
 */
export function instanceOfPlaceGeo(value: object): value is PlaceGeo {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function PlaceGeoFromJSON(json: any): PlaceGeo {
    return PlaceGeoFromJSONTyped(json, false);
}

export function PlaceGeoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceGeo {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
    };
}

export function PlaceGeoToJSON(json: any): PlaceGeo {
    return PlaceGeoToJSONTyped(json, false);
}

export function PlaceGeoToJSONTyped(value?: PlaceGeo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

