/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaceCalendarType } from './PlaceCalendarType';
import {
    PlaceCalendarTypeFromJSON,
    PlaceCalendarTypeFromJSONTyped,
    PlaceCalendarTypeToJSON,
    PlaceCalendarTypeToJSONTyped,
} from './PlaceCalendarType';
import type { EventPriceInfoInner } from './EventPriceInfoInner';
import {
    EventPriceInfoInnerFromJSON,
    EventPriceInfoInnerFromJSONTyped,
    EventPriceInfoInnerToJSON,
    EventPriceInfoInnerToJSONTyped,
} from './EventPriceInfoInner';
import type { PlaceDescription } from './PlaceDescription';
import {
    PlaceDescriptionFromJSON,
    PlaceDescriptionFromJSONTyped,
    PlaceDescriptionToJSON,
    PlaceDescriptionToJSONTyped,
} from './PlaceDescription';
import type { CommonAddressLocalized } from './CommonAddressLocalized';
import {
    CommonAddressLocalizedFromJSON,
    CommonAddressLocalizedFromJSONTyped,
    CommonAddressLocalizedToJSON,
    CommonAddressLocalizedToJSONTyped,
} from './CommonAddressLocalized';
import type { PlaceStatus } from './PlaceStatus';
import {
    PlaceStatusFromJSON,
    PlaceStatusFromJSONTyped,
    PlaceStatusToJSON,
    PlaceStatusToJSONTyped,
} from './PlaceStatus';
import type { PlaceTermsInner } from './PlaceTermsInner';
import {
    PlaceTermsInnerFromJSON,
    PlaceTermsInnerFromJSONTyped,
    PlaceTermsInnerToJSON,
    PlaceTermsInnerToJSONTyped,
} from './PlaceTermsInner';
import type { PlaceWorkflowStatus } from './PlaceWorkflowStatus';
import {
    PlaceWorkflowStatusFromJSON,
    PlaceWorkflowStatusFromJSONTyped,
    PlaceWorkflowStatusToJSON,
    PlaceWorkflowStatusToJSONTyped,
} from './PlaceWorkflowStatus';
import type { EventVideosInner } from './EventVideosInner';
import {
    EventVideosInnerFromJSON,
    EventVideosInnerFromJSONTyped,
    EventVideosInnerToJSON,
    EventVideosInnerToJSONTyped,
} from './EventVideosInner';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
    ImageToJSONTyped,
} from './Image';
import type { PlaceBookingAvailability } from './PlaceBookingAvailability';
import {
    PlaceBookingAvailabilityFromJSON,
    PlaceBookingAvailabilityFromJSONTyped,
    PlaceBookingAvailabilityToJSON,
    PlaceBookingAvailabilityToJSONTyped,
} from './PlaceBookingAvailability';
import type { CommonOpeningHoursInner } from './CommonOpeningHoursInner';
import {
    CommonOpeningHoursInnerFromJSON,
    CommonOpeningHoursInnerFromJSONTyped,
    CommonOpeningHoursInnerToJSON,
    CommonOpeningHoursInnerToJSONTyped,
} from './CommonOpeningHoursInner';
import type { PlaceGeo } from './PlaceGeo';
import {
    PlaceGeoFromJSON,
    PlaceGeoFromJSONTyped,
    PlaceGeoToJSON,
    PlaceGeoToJSONTyped,
} from './PlaceGeo';
import type { PlaceContactPoint } from './PlaceContactPoint';
import {
    PlaceContactPointFromJSON,
    PlaceContactPointFromJSONTyped,
    PlaceContactPointToJSON,
    PlaceContactPointToJSONTyped,
} from './PlaceContactPoint';
import type { PlacePostDeprecated } from './PlacePostDeprecated';
import {
    PlacePostDeprecatedFromJSON,
    PlacePostDeprecatedFromJSONTyped,
    PlacePostDeprecatedToJSON,
    PlacePostDeprecatedToJSONTyped,
} from './PlacePostDeprecated';
import type { PlaceOpeningHoursAdjustedDays } from './PlaceOpeningHoursAdjustedDays';
import {
    PlaceOpeningHoursAdjustedDaysFromJSON,
    PlaceOpeningHoursAdjustedDaysFromJSONTyped,
    PlaceOpeningHoursAdjustedDaysToJSON,
    PlaceOpeningHoursAdjustedDaysToJSONTyped,
} from './PlaceOpeningHoursAdjustedDays';
import type { PlaceCalendarSummary } from './PlaceCalendarSummary';
import {
    PlaceCalendarSummaryFromJSON,
    PlaceCalendarSummaryFromJSONTyped,
    PlaceCalendarSummaryToJSON,
    PlaceCalendarSummaryToJSONTyped,
} from './PlaceCalendarSummary';
import type { PlaceOrganizer } from './PlaceOrganizer';
import {
    PlaceOrganizerFromJSON,
    PlaceOrganizerFromJSONTyped,
    PlaceOrganizerToJSON,
    PlaceOrganizerToJSONTyped,
} from './PlaceOrganizer';
import type { PlacePostDeprecatedType } from './PlacePostDeprecatedType';
import {
    PlacePostDeprecatedTypeFromJSON,
    PlacePostDeprecatedTypeFromJSONTyped,
    PlacePostDeprecatedTypeToJSON,
    PlacePostDeprecatedTypeToJSONTyped,
} from './PlacePostDeprecatedType';
import type { PlaceCalendarPut } from './PlaceCalendarPut';
import {
    PlaceCalendarPutFromJSON,
    PlaceCalendarPutFromJSONTyped,
    PlaceCalendarPutToJSON,
    PlaceCalendarPutToJSONTyped,
} from './PlaceCalendarPut';
import type { PlaceBookingInfo } from './PlaceBookingInfo';
import {
    PlaceBookingInfoFromJSON,
    PlaceBookingInfoFromJSONTyped,
    PlaceBookingInfoToJSON,
    PlaceBookingInfoToJSONTyped,
} from './PlaceBookingInfo';
import type { PlaceMainLanguage } from './PlaceMainLanguage';
import {
    PlaceMainLanguageFromJSON,
    PlaceMainLanguageFromJSONTyped,
    PlaceMainLanguageToJSON,
    PlaceMainLanguageToJSONTyped,
} from './PlaceMainLanguage';
import type { Place } from './Place';
import {
    PlaceFromJSON,
    PlaceFromJSONTyped,
    PlaceToJSON,
    PlaceToJSONTyped,
} from './Place';
import type { CommonOpeningHoursClosedDaysInner } from './CommonOpeningHoursClosedDaysInner';
import {
    CommonOpeningHoursClosedDaysInnerFromJSON,
    CommonOpeningHoursClosedDaysInnerFromJSONTyped,
    CommonOpeningHoursClosedDaysInnerToJSON,
    CommonOpeningHoursClosedDaysInnerToJSONTyped,
} from './CommonOpeningHoursClosedDaysInner';

/**
 * 
 * @export
 * @interface PlacePost
 */
export interface PlacePost {
    /**
     * A unique URI that acts as globally unique ID for the [place](./models/place.json). Based on (JSON-LD node identifiers)[https://www.w3.org/TR/json-ld/#node-identifiers].
     * @type {string}
     * @memberof PlacePost
     */
    id?: string;
    /**
     * 
     * @type {PlaceMainLanguage}
     * @memberof PlacePost
     */
    mainLanguage: PlaceMainLanguage;
    /**
     * The name of the place.
     * @type {string}
     * @memberof PlacePost
     */
    name: string;
    /**
     * A list of taxonomy terms used to categorize the [place](./models/place.json).
     * 
     * Terms are pre-defined and can be found using our [guide about taxonomy terms](../docs/taxonomy-api/terms.md).
     * 
     * A place requires at least one term, to define its type. (For example a museum, monument, ...)
     * @type {Array<PlaceTermsInner>}
     * @memberof PlacePost
     */
    terms: Array<PlaceTermsInner>;
    /**
     * 
     * @type {PlaceCalendarType}
     * @memberof PlacePost
     */
    calendarType: PlaceCalendarType;
    /**
     * The address of the place in the main language.
     * @type {CommonAddressLocalized}
     * @memberof PlacePost
     */
    address: CommonAddressLocalized;
    /**
     * 
     * @type {PlaceGeo}
     * @memberof PlacePost
     */
    geo?: PlaceGeo;
    /**
     * 
     * @type {PlaceOrganizer}
     * @memberof PlacePost
     */
    organizer?: PlaceOrganizer;
    /**
     * The date & time that the [place](./models/place.json) starts when using the `periodic` [calendarType](./models/place-calendarType.json), as an ISO-8601 date.
     * 
     * For example `2021-05-17T22:00:00+00:00`.
     * @type {Date}
     * @memberof PlacePost
     */
    startDate?: Date;
    /**
     * The date & time that the [place](./models/place.json) ends when using the `periodic` [calendarType](./models/place-calendarType.json), as an ISO-8601 date.
     * 
     * For example `2021-05-17T22:00:00+00:00`.
     * @type {Date}
     * @memberof PlacePost
     */
    endDate?: Date;
    /**
     * 
     * @type {PlaceStatus}
     * @memberof PlacePost
     */
    status?: PlaceStatus;
    /**
     * A list of multiple open/closed times and weekdays indicating when the [place](./models/place.json) is open.
     * @type {Array<CommonOpeningHoursInner>}
     * @memberof PlacePost
     */
    openingHours?: Array<CommonOpeningHoursInner>;
    /**
     * List of specific date ranges during which the event or place is considered closed, overriding the default opening hours. Only applicable for calendarType `periodic` and `permanent`. An empty array clears all previously set closed days.
     * @type {Array<CommonOpeningHoursClosedDaysInner>}
     * @memberof PlacePost
     */
    openingHoursClosedDays?: Array<CommonOpeningHoursClosedDaysInner>;
    /**
     * 
     * @type {PlaceOpeningHoursAdjustedDays}
     * @memberof PlacePost
     */
    openingHoursAdjustedDays?: PlaceOpeningHoursAdjustedDays;
    /**
     * The first date & time that the [place](./models/place.json) is allowed to be visible on publication channels.
     * 
     * Formatted as an ISO-8601 datetime. For example `2021-05-17T22:00:00+00:00`.
     * @type {Date}
     * @memberof PlacePost
     */
    availableFrom?: Date;
    /**
     * The last date & time that the [place](./models/place.json) is allowed to be visible on publication channels.
     * 
     * Added automatically by UiTdatabank based on either the [startDate](./models/place-startDate) or [endDate](./models/place-endDate.json) depending on the [event type](./models/place-terms.json).
     * 
     * Formatted as an ISO-8601 datetime. For example `2021-05-17T22:00:00+00:00`.
     * @type {Date}
     * @memberof PlacePost
     */
    readonly availableTo?: Date;
    /**
     * 
     * @type {PlaceWorkflowStatus}
     * @memberof PlacePost
     */
    workflowStatus?: PlaceWorkflowStatus;
    /**
     * List of languages that the [place](./models/place.json) is available in. (Not all localizable properties may contain every language though)
     * 
     * Added automatically by UiTdatabank based on the languages present in localized properties.
     * 
     * See also [completedLanguages](./models/place-completedLanguages.json).
     * @type {Array<PlacePostLanguagesEnum>}
     * @memberof PlacePost
     */
    readonly languages?: Array<PlacePostLanguagesEnum>;
    /**
     * List of languages that _every_ localizable property on the [place](./models/place.json) is available in.
     * 
     * Added automatically by UiTdatabank based on the languages present in localized properties.
     * 
     * See also [languages](./models/place-languages.json).
     * @type {Array<PlacePostCompletedLanguagesEnum>}
     * @memberof PlacePost
     */
    readonly completedLanguages?: Array<PlacePostCompletedLanguagesEnum>;
    /**
     * Indicates the minimum and maximum age to visit the [place](./models/place.json). For example `6-12`, `0-12`, `-12`, or `6-`.
     * @type {string}
     * @memberof PlacePost
     */
    typicalAgeRange?: string;
    /**
     * 
     * @type {PlaceDescription}
     * @memberof PlacePost
     */
    description?: PlaceDescription;
    /**
     * A list of tariffs available for tickets/reservations to visit the [place](./models/place.json).
     * @type {Array<EventPriceInfoInner>}
     * @memberof PlacePost
     */
    priceInfo?: Array<EventPriceInfoInner>;
    /**
     * 
     * @type {PlaceContactPoint}
     * @memberof PlacePost
     */
    contactPoint?: PlaceContactPoint;
    /**
     * 
     * @type {PlaceBookingInfo}
     * @memberof PlacePost
     */
    bookingInfo?: PlaceBookingInfo;
    /**
     * A list of media objects related to the [place](./models/place.json), in reality always images but called mediaObject for backward compatibility. The main image of the place will always be set to the first image in this list when creating/updating a place with multiple images.
     * @type {Array<Image>}
     * @memberof PlacePost
     */
    mediaObject?: Array<Image>;
    /**
     * URL to the main image of the [place](./models/place.json). Will be automatically be set by UiTdatabank to the URL of the first image in `mediaObject`.
     * @type {string}
     * @memberof PlacePost
     */
    readonly image?: string;
    /**
     * Describes an array of video objects that are linked to a place.
     * @type {Array<EventVideosInner>}
     * @memberof PlacePost
     */
    videos?: Array<EventVideosInner>;
    /**
     * One or more labels that categorize the [place](./models/place.json). Compared to [terms](./models/place-terms.json), labels do not have a defined set of possible values or a hierarchy.
     * 
     * Labels are allowed to be visible for end users on publication channels.
     * 
     * See [hiddenLabels](./models/place-hiddenLabels.json) for labels that should not be visible on publication channels.
     * @type {Array<string>}
     * @memberof PlacePost
     */
    labels?: Array<string>;
    /**
     * Same as [labels](./models/place-labels.json), but for labels that should not be visible for end users on publication channels and should instead only be used for filtering or other processing.
     * @type {Array<string>}
     * @memberof PlacePost
     */
    hiddenLabels?: Array<string>;
    /**
     * 
     * @type {PlaceBookingAvailability}
     * @memberof PlacePost
     */
    bookingAvailability?: PlaceBookingAvailability;
    /**
     * The unique identifier of the creator of the [place](./models/place.json). Usually a UUID, but can historally be an e-mail address.
     * 
     * Added automatically by UiTdatabank based on the authentication credentials used to create the place.
     * @type {string}
     * @memberof PlacePost
     */
    readonly creator?: string;
    /**
     * Date formatted as an ISO-8601 datetime, added automatically by UiTdatabank based on the date & time the [place](./models/place.json) was created at.
     * 
     * For example `2021-05-17T22:00:00+00:00`.
     * @type {Date}
     * @memberof PlacePost
     */
    readonly created?: Date;
    /**
     * Date formatted as an ISO-8601 datetime, added automatically by UiTdatabank based on the date & time the [place](./models/place.json) was last modified.
     * 
     * For example `2021-05-17T22:00:00+00:00`.
     * @type {Date}
     * @memberof PlacePost
     */
    readonly modified?: Date;
    /**
     * One or more URIs that represent the same [place](./models/place.json) on another API or website, not necessarily in JSON-LD format.
     * 
     * Added automatically by UiTdatabank based on info from other systems.
     * 
     * For example `http://www.uitinvlaanderen.be/agenda/p/test-place/85b04295-479c-40f5-b3dd-469dfb4387b3`.
     * @type {Array<string>}
     * @memberof PlacePost
     */
    readonly sameAs?: Array<string>;
    /**
     * List of contributors on a [place](./models/place.json). Only included if you request the place with an authenticated user who has the "Aanbod bewerken" permission on the place. [Here is a detailed guide](./entry-api/shared/contributors) with more information.
     * @type {Array<string>}
     * @memberof PlacePost
     */
    readonly contributors?: Array<string>;
    /**
     * The completeness score is a number between 0 and 100 that indicates how complete the information of an event, place or organizer is.
     * @type {number}
     * @memberof PlacePost
     */
    readonly completeness?: number;
    /**
     * 
     * @type {PlaceCalendarSummary}
     * @memberof PlacePost
     */
    calendarSummary?: PlaceCalendarSummary;
    /**
     * 
     * @type {PlacePostDeprecatedType}
     * @memberof PlacePost
     */
    type: PlacePostDeprecatedType;
    /**
     * Calendar info for the place.
     * @type {PlaceCalendarPut}
     * @memberof PlacePost
     */
    calendar: PlaceCalendarPut;
}


/**
 * @export
 */
export const PlacePostLanguagesEnum = {
    Nl: 'nl',
    Fr: 'fr',
    De: 'de',
    En: 'en'
} as const;
export type PlacePostLanguagesEnum = typeof PlacePostLanguagesEnum[keyof typeof PlacePostLanguagesEnum];

/**
 * @export
 */
export const PlacePostCompletedLanguagesEnum = {
    Nl: 'nl',
    Fr: 'fr',
    De: 'de',
    En: 'en'
} as const;
export type PlacePostCompletedLanguagesEnum = typeof PlacePostCompletedLanguagesEnum[keyof typeof PlacePostCompletedLanguagesEnum];


/**
 * Check if a given object implements the PlacePost interface.
 */
export function instanceOfPlacePost(value: object): value is PlacePost {
    if (!('mainLanguage' in value) || value['mainLanguage'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('terms' in value) || value['terms'] === undefined) return false;
    if (!('calendarType' in value) || value['calendarType'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('calendar' in value) || value['calendar'] === undefined) return false;
    return true;
}

export function PlacePostFromJSON(json: any): PlacePost {
    return PlacePostFromJSONTyped(json, false);
}

export function PlacePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlacePost {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['@id'] == null ? undefined : json['@id'],
        'mainLanguage': PlaceMainLanguageFromJSON(json['mainLanguage']),
        'name': json['name'],
        'terms': ((json['terms'] as Array<any>).map(PlaceTermsInnerFromJSON)),
        'calendarType': PlaceCalendarTypeFromJSON(json['calendarType']),
        'address': CommonAddressLocalizedFromJSON(json['address']),
        'geo': json['geo'] == null ? undefined : PlaceGeoFromJSON(json['geo']),
        'organizer': json['organizer'] == null ? undefined : PlaceOrganizerFromJSON(json['organizer']),
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'status': json['status'] == null ? undefined : PlaceStatusFromJSON(json['status']),
        'openingHours': json['openingHours'] == null ? undefined : ((json['openingHours'] as Array<any>).map(CommonOpeningHoursInnerFromJSON)),
        'openingHoursClosedDays': json['openingHoursClosedDays'] == null ? undefined : ((json['openingHoursClosedDays'] as Array<any>).map(CommonOpeningHoursClosedDaysInnerFromJSON)),
        'openingHoursAdjustedDays': json['openingHoursAdjustedDays'] == null ? undefined : PlaceOpeningHoursAdjustedDaysFromJSON(json['openingHoursAdjustedDays']),
        'availableFrom': json['availableFrom'] == null ? undefined : (new Date(json['availableFrom'])),
        'availableTo': json['availableTo'] == null ? undefined : (new Date(json['availableTo'])),
        'workflowStatus': json['workflowStatus'] == null ? undefined : PlaceWorkflowStatusFromJSON(json['workflowStatus']),
        'languages': json['languages'] == null ? undefined : json['languages'],
        'completedLanguages': json['completedLanguages'] == null ? undefined : json['completedLanguages'],
        'typicalAgeRange': json['typicalAgeRange'] == null ? undefined : json['typicalAgeRange'],
        'description': json['description'] == null ? undefined : PlaceDescriptionFromJSON(json['description']),
        'priceInfo': json['priceInfo'] == null ? undefined : ((json['priceInfo'] as Array<any>).map(EventPriceInfoInnerFromJSON)),
        'contactPoint': json['contactPoint'] == null ? undefined : PlaceContactPointFromJSON(json['contactPoint']),
        'bookingInfo': json['bookingInfo'] == null ? undefined : PlaceBookingInfoFromJSON(json['bookingInfo']),
        'mediaObject': json['mediaObject'] == null ? undefined : ((json['mediaObject'] as Array<any>).map(ImageFromJSON)),
        'image': json['image'] == null ? undefined : json['image'],
        'videos': json['videos'] == null ? undefined : ((json['videos'] as Array<any>).map(EventVideosInnerFromJSON)),
        'labels': json['labels'] == null ? undefined : json['labels'],
        'hiddenLabels': json['hiddenLabels'] == null ? undefined : json['hiddenLabels'],
        'bookingAvailability': json['bookingAvailability'] == null ? undefined : PlaceBookingAvailabilityFromJSON(json['bookingAvailability']),
        'creator': json['creator'] == null ? undefined : json['creator'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'modified': json['modified'] == null ? undefined : (new Date(json['modified'])),
        'sameAs': json['sameAs'] == null ? undefined : json['sameAs'],
        'contributors': json['contributors'] == null ? undefined : json['contributors'],
        'completeness': json['completeness'] == null ? undefined : json['completeness'],
        'calendarSummary': json['calendarSummary'] == null ? undefined : PlaceCalendarSummaryFromJSON(json['calendarSummary']),
        'type': PlacePostDeprecatedTypeFromJSON(json['type']),
        'calendar': PlaceCalendarPutFromJSON(json['calendar']),
    };
}

export function PlacePostToJSON(json: any): PlacePost {
    return PlacePostToJSONTyped(json, false);
}

export function PlacePostToJSONTyped(value?: Omit<PlacePost, 'availableTo'|'languages'|'completedLanguages'|'image'|'creator'|'created'|'modified'|'sameAs'|'contributors'|'completeness'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@id': value['id'],
        'mainLanguage': PlaceMainLanguageToJSON(value['mainLanguage']),
        'name': value['name'],
        'terms': ((value['terms'] as Array<any>).map(PlaceTermsInnerToJSON)),
        'calendarType': PlaceCalendarTypeToJSON(value['calendarType']),
        'address': CommonAddressLocalizedToJSON(value['address']),
        'geo': PlaceGeoToJSON(value['geo']),
        'organizer': PlaceOrganizerToJSON(value['organizer']),
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'status': PlaceStatusToJSON(value['status']),
        'openingHours': value['openingHours'] == null ? undefined : ((value['openingHours'] as Array<any>).map(CommonOpeningHoursInnerToJSON)),
        'openingHoursClosedDays': value['openingHoursClosedDays'] == null ? undefined : ((value['openingHoursClosedDays'] as Array<any>).map(CommonOpeningHoursClosedDaysInnerToJSON)),
        'openingHoursAdjustedDays': PlaceOpeningHoursAdjustedDaysToJSON(value['openingHoursAdjustedDays']),
        'availableFrom': value['availableFrom'] == null ? value['availableFrom'] : value['availableFrom'].toISOString(),
        'workflowStatus': PlaceWorkflowStatusToJSON(value['workflowStatus']),
        'typicalAgeRange': value['typicalAgeRange'],
        'description': PlaceDescriptionToJSON(value['description']),
        'priceInfo': value['priceInfo'] == null ? undefined : ((value['priceInfo'] as Array<any>).map(EventPriceInfoInnerToJSON)),
        'contactPoint': PlaceContactPointToJSON(value['contactPoint']),
        'bookingInfo': PlaceBookingInfoToJSON(value['bookingInfo']),
        'mediaObject': value['mediaObject'] == null ? undefined : ((value['mediaObject'] as Array<any>).map(ImageToJSON)),
        'videos': value['videos'] == null ? undefined : ((value['videos'] as Array<any>).map(EventVideosInnerToJSON)),
        'labels': value['labels'],
        'hiddenLabels': value['hiddenLabels'],
        'bookingAvailability': PlaceBookingAvailabilityToJSON(value['bookingAvailability']),
        'calendarSummary': PlaceCalendarSummaryToJSON(value['calendarSummary']),
        'type': PlacePostDeprecatedTypeToJSON(value['type']),
        'calendar': PlaceCalendarPutToJSON(value['calendar']),
    };
}

