/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * With UiTdatabank\'s Search API you can search events, places and organizers.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonName } from './CommonName';
import {
    CommonNameFromJSON,
    CommonNameFromJSONTyped,
    CommonNameToJSON,
    CommonNameToJSONTyped,
} from './CommonName';

/**
 * A single facet for a specific filter. Every facet has a human-readable name and total count to show to end-users to drill down search results.
 * @export
 * @interface CommonFacet
 */
export interface CommonFacet {
    /**
     * 
     * @type {CommonName}
     * @memberof CommonFacet
     */
    name: CommonName;
    /**
     * Total results if the filter is applied with this value (= the key referencing this object).
     * @type {number}
     * @memberof CommonFacet
     */
    count: number;
    /**
     * Children facets, in the case of filters with a hierarchy.
     * @type {{ [key: string]: CommonFacet; }}
     * @memberof CommonFacet
     */
    children?: { [key: string]: CommonFacet; };
}

/**
 * Check if a given object implements the CommonFacet interface.
 */
export function instanceOfCommonFacet(value: object): value is CommonFacet {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function CommonFacetFromJSON(json: any): CommonFacet {
    return CommonFacetFromJSONTyped(json, false);
}

export function CommonFacetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonFacet {
    if (json == null) {
        return json;
    }
    return {
        
        'name': CommonNameFromJSON(json['name']),
        'count': json['count'],
        'children': json['children'] == null ? undefined : (mapValues(json['children'], CommonFacetFromJSON)),
    };
}

export function CommonFacetToJSON(json: any): CommonFacet {
    return CommonFacetToJSONTyped(json, false);
}

export function CommonFacetToJSONTyped(value?: CommonFacet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': CommonNameToJSON(value['name']),
        'count': value['count'],
        'children': value['children'] == null ? undefined : (mapValues(value['children'], CommonFacetToJSON)),
    };
}

