/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * With UiTdatabank\'s Search API you can search events, places and organizers.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorSchemaErrorsInner
 */
export interface ErrorSchemaErrorsInner {
    /**
     * RFC6901 compliant pointer that indicates what property/value was invalid.
     * @type {string}
     * @memberof ErrorSchemaErrorsInner
     */
    jsonPointer: string;
    /**
     * A human-readable (but often technical) reason why the property was invalid.
     * @type {string}
     * @memberof ErrorSchemaErrorsInner
     */
    error: string;
}

/**
 * Check if a given object implements the ErrorSchemaErrorsInner interface.
 */
export function instanceOfErrorSchemaErrorsInner(value: object): value is ErrorSchemaErrorsInner {
    if (!('jsonPointer' in value) || value['jsonPointer'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ErrorSchemaErrorsInnerFromJSON(json: any): ErrorSchemaErrorsInner {
    return ErrorSchemaErrorsInnerFromJSONTyped(json, false);
}

export function ErrorSchemaErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorSchemaErrorsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonPointer': json['jsonPointer'],
        'error': json['error'],
    };
}

export function ErrorSchemaErrorsInnerToJSON(json: any): ErrorSchemaErrorsInner {
    return ErrorSchemaErrorsInnerToJSONTyped(json, false);
}

export function ErrorSchemaErrorsInnerToJSONTyped(value?: ErrorSchemaErrorsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonPointer': value['jsonPointer'],
        'error': value['error'],
    };
}

