/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * With UiTdatabank\'s Search API you can search events, places and organizers.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Indicates the intended audience of the [event](./models/event.json).
 * @export
 * @interface EventAudience
 */
export interface EventAudience {
    /**
     * Indicates whether the event or place is accessible to `everyone`, `members` only, `education` only or `childrenOnly` without parents or guardians.
     * @type {EventAudienceAudienceTypeEnum}
     * @memberof EventAudience
     */
    audienceType: EventAudienceAudienceTypeEnum;
}


/**
 * @export
 */
export const EventAudienceAudienceTypeEnum = {
    Everyone: 'everyone',
    Members: 'members',
    Education: 'education',
    ChildrenOnly: 'childrenOnly'
} as const;
export type EventAudienceAudienceTypeEnum = typeof EventAudienceAudienceTypeEnum[keyof typeof EventAudienceAudienceTypeEnum];


/**
 * Check if a given object implements the EventAudience interface.
 */
export function instanceOfEventAudience(value: object): value is EventAudience {
    if (!('audienceType' in value) || value['audienceType'] === undefined) return false;
    return true;
}

export function EventAudienceFromJSON(json: any): EventAudience {
    return EventAudienceFromJSONTyped(json, false);
}

export function EventAudienceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventAudience {
    if (json == null) {
        return json;
    }
    return {
        
        'audienceType': json['audienceType'],
    };
}

export function EventAudienceToJSON(json: any): EventAudience {
    return EventAudienceToJSONTyped(json, false);
}

export function EventAudienceToJSONTyped(value?: EventAudience | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audienceType': value['audienceType'],
    };
}

