/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * With UiTdatabank\'s Search API you can search events, places and organizers.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventPriceInfoInner } from './EventPriceInfoInner';
import {
    EventPriceInfoInnerFromJSON,
    EventPriceInfoInnerFromJSONTyped,
    EventPriceInfoInnerToJSON,
    EventPriceInfoInnerToJSONTyped,
} from './EventPriceInfoInner';
import type { EventBookingInfo } from './EventBookingInfo';
import {
    EventBookingInfoFromJSON,
    EventBookingInfoFromJSONTyped,
    EventBookingInfoToJSON,
    EventBookingInfoToJSONTyped,
} from './EventBookingInfo';
import type { EventMainLanguage } from './EventMainLanguage';
import {
    EventMainLanguageFromJSON,
    EventMainLanguageFromJSONTyped,
    EventMainLanguageToJSON,
    EventMainLanguageToJSONTyped,
} from './EventMainLanguage';
import type { EventProduction } from './EventProduction';
import {
    EventProductionFromJSON,
    EventProductionFromJSONTyped,
    EventProductionToJSON,
    EventProductionToJSONTyped,
} from './EventProduction';
import type { EventContactPoint } from './EventContactPoint';
import {
    EventContactPointFromJSON,
    EventContactPointFromJSONTyped,
    EventContactPointToJSON,
    EventContactPointToJSONTyped,
} from './EventContactPoint';
import type { EventStatus } from './EventStatus';
import {
    EventStatusFromJSON,
    EventStatusFromJSONTyped,
    EventStatusToJSON,
    EventStatusToJSONTyped,
} from './EventStatus';
import type { EventTermsInner } from './EventTermsInner';
import {
    EventTermsInnerFromJSON,
    EventTermsInnerFromJSONTyped,
    EventTermsInnerToJSON,
    EventTermsInnerToJSONTyped,
} from './EventTermsInner';
import type { EventVideosInner } from './EventVideosInner';
import {
    EventVideosInnerFromJSON,
    EventVideosInnerFromJSONTyped,
    EventVideosInnerToJSON,
    EventVideosInnerToJSONTyped,
} from './EventVideosInner';
import type { EventOpeningHours } from './EventOpeningHours';
import {
    EventOpeningHoursFromJSON,
    EventOpeningHoursFromJSONTyped,
    EventOpeningHoursToJSON,
    EventOpeningHoursToJSONTyped,
} from './EventOpeningHours';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
    ImageToJSONTyped,
} from './Image';
import type { EventSubEventInner } from './EventSubEventInner';
import {
    EventSubEventInnerFromJSON,
    EventSubEventInnerFromJSONTyped,
    EventSubEventInnerToJSON,
    EventSubEventInnerToJSONTyped,
} from './EventSubEventInner';
import type { EventWorkflowStatus } from './EventWorkflowStatus';
import {
    EventWorkflowStatusFromJSON,
    EventWorkflowStatusFromJSONTyped,
    EventWorkflowStatusToJSON,
    EventWorkflowStatusToJSONTyped,
} from './EventWorkflowStatus';
import type { EventOrganizer } from './EventOrganizer';
import {
    EventOrganizerFromJSON,
    EventOrganizerFromJSONTyped,
    EventOrganizerToJSON,
    EventOrganizerToJSONTyped,
} from './EventOrganizer';
import type { EventAttendanceMode } from './EventAttendanceMode';
import {
    EventAttendanceModeFromJSON,
    EventAttendanceModeFromJSONTyped,
    EventAttendanceModeToJSON,
    EventAttendanceModeToJSONTyped,
} from './EventAttendanceMode';
import type { EventBirthdateRange } from './EventBirthdateRange';
import {
    EventBirthdateRangeFromJSON,
    EventBirthdateRangeFromJSONTyped,
    EventBirthdateRangeToJSON,
    EventBirthdateRangeToJSONTyped,
} from './EventBirthdateRange';
import type { EventDeparturePlaces } from './EventDeparturePlaces';
import {
    EventDeparturePlacesFromJSON,
    EventDeparturePlacesFromJSONTyped,
    EventDeparturePlacesToJSON,
    EventDeparturePlacesToJSONTyped,
} from './EventDeparturePlaces';
import type { EventAudience } from './EventAudience';
import {
    EventAudienceFromJSON,
    EventAudienceFromJSONTyped,
    EventAudienceToJSON,
    EventAudienceToJSONTyped,
} from './EventAudience';
import type { EventOpeningHoursAdjustedDays } from './EventOpeningHoursAdjustedDays';
import {
    EventOpeningHoursAdjustedDaysFromJSON,
    EventOpeningHoursAdjustedDaysFromJSONTyped,
    EventOpeningHoursAdjustedDaysToJSON,
    EventOpeningHoursAdjustedDaysToJSONTyped,
} from './EventOpeningHoursAdjustedDays';
import type { EventLocation } from './EventLocation';
import {
    EventLocationFromJSON,
    EventLocationFromJSONTyped,
    EventLocationToJSON,
    EventLocationToJSONTyped,
} from './EventLocation';
import type { EventCalendarSummary } from './EventCalendarSummary';
import {
    EventCalendarSummaryFromJSON,
    EventCalendarSummaryFromJSONTyped,
    EventCalendarSummaryToJSON,
    EventCalendarSummaryToJSONTyped,
} from './EventCalendarSummary';
import type { EventName } from './EventName';
import {
    EventNameFromJSON,
    EventNameFromJSONTyped,
    EventNameToJSON,
    EventNameToJSONTyped,
} from './EventName';
import type { Faq } from './Faq';
import {
    FaqFromJSON,
    FaqFromJSONTyped,
    FaqToJSON,
    FaqToJSONTyped,
} from './Faq';
import type { EventCalendarType } from './EventCalendarType';
import {
    EventCalendarTypeFromJSON,
    EventCalendarTypeFromJSONTyped,
    EventCalendarTypeToJSON,
    EventCalendarTypeToJSONTyped,
} from './EventCalendarType';
import type { EventDescription } from './EventDescription';
import {
    EventDescriptionFromJSON,
    EventDescriptionFromJSONTyped,
    EventDescriptionToJSON,
    EventDescriptionToJSONTyped,
} from './EventDescription';
import type { EventBookingAvailability } from './EventBookingAvailability';
import {
    EventBookingAvailabilityFromJSON,
    EventBookingAvailabilityFromJSONTyped,
    EventBookingAvailabilityToJSON,
    EventBookingAvailabilityToJSONTyped,
} from './EventBookingAvailability';
import type { CommonOpeningHoursClosedDaysInner } from './CommonOpeningHoursClosedDaysInner';
import {
    CommonOpeningHoursClosedDaysInnerFromJSON,
    CommonOpeningHoursClosedDaysInnerFromJSONTyped,
    CommonOpeningHoursClosedDaysInnerToJSON,
    CommonOpeningHoursClosedDaysInnerToJSONTyped,
} from './CommonOpeningHoursClosedDaysInner';

/**
 * A cultural, sport, or pastime activity.
 * 
 * For more information: <a href="https://docs.publiq.be/docs/uitdatabank/entry-api/events/what-are-events">What are events?</a>
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * A unique URI that acts as globally unique ID for the [event](./models/event.json). Based on [JSON-LD node identifiers](https://www.w3.org/TR/json-ld/#node-identifiers).
     * @type {string}
     * @memberof Event
     */
    id?: string;
    /**
     * 
     * @type {EventMainLanguage}
     * @memberof Event
     */
    mainLanguage: EventMainLanguage;
    /**
     * 
     * @type {EventName}
     * @memberof Event
     */
    name: EventName;
    /**
     * A list of taxonomy terms used to categorize the [event](./models/event.json).
     * 
     * Terms are pre-defined and can be found using our [guide about taxonomy terms](../docs/taxonomy-api/terms.md).
     * 
     * An event requires at least one term, to define its type. (For example a concert, theater show, ...)
     * @type {Set<EventTermsInner>}
     * @memberof Event
     */
    terms: Set<EventTermsInner>;
    /**
     * 
     * @type {EventLocation}
     * @memberof Event
     */
    location: EventLocation;
    /**
     * 
     * @type {EventCalendarType}
     * @memberof Event
     */
    calendarType: EventCalendarType;
    /**
     * The date & time that the [event](./models/event.json) or [subEvent](./models/event-subEvent.json) starts, as an ISO-8601 date. For example `2021-05-17T22:00:00+00:00`.
     * 
     * Required on events when using one of the following calendarTypes:
     * 
     * - `single`
     * - `multiple`
     * - `periodic`
     * 
     * Always required on subEvents.
     * @type {Date}
     * @memberof Event
     */
    startDate?: Date;
    /**
     * The date & time that the [event](./models/event.json) or [subEvent](./models/event-subEvent.json) ends, as an ISO-8601 date. For example `2021-05-17T22:00:00+00:00`.
     * 
     * Required on events when using one of the following calendarTypes:
     * 
     * - `single`
     * - `multiple`
     * - `periodic`
     * 
     * Always required on subEvents.
     * @type {Date}
     * @memberof Event
     */
    endDate?: Date;
    /**
     * 
     * @type {EventAttendanceMode}
     * @memberof Event
     */
    attendanceMode?: EventAttendanceMode;
    /**
     * The url to follow the [event](./models/event.json) online.
     * @type {string}
     * @memberof Event
     */
    onlineUrl?: string;
    /**
     * 
     * @type {EventStatus}
     * @memberof Event
     */
    status?: EventStatus;
    /**
     * A list of occurrences of the [event](./models/event.json) when using the `single` or `multiple` [calendarType](./models/event-calendarType.json).
     * @type {Array<EventSubEventInner>}
     * @memberof Event
     */
    subEvent?: Array<EventSubEventInner>;
    /**
     * 
     * @type {EventOpeningHours}
     * @memberof Event
     */
    openingHours?: EventOpeningHours;
    /**
     * List of specific date ranges during which the event or place is considered closed, overriding the default opening hours. Only applicable for calendarType `periodic` and `permanent`. An empty array clears all previously set closed days.
     * @type {Array<CommonOpeningHoursClosedDaysInner>}
     * @memberof Event
     */
    openingHoursClosedDays?: Array<CommonOpeningHoursClosedDaysInner>;
    /**
     * 
     * @type {EventOpeningHoursAdjustedDays}
     * @memberof Event
     */
    openingHoursAdjustedDays?: EventOpeningHoursAdjustedDays;
    /**
     * The first date & time that the [event](./models/event.json) is allowed to be visible on publication channels.
     * 
     * Formatted as an ISO-8601 datetime. For example `2021-05-17T22:00:00+00:00`.
     * @type {Date}
     * @memberof Event
     */
    availableFrom?: Date;
    /**
     * The last date & time that the [event](./models/event.json) is allowed to be visible on publication channels.
     * 
     * Added automatically by UiTdatabank based on either the [startDate](./models/event-startDate.json) or [endDate](./models/event-endDate.json) depending on the [event type](./models/event-terms.json).
     * 
     * Formatted as an ISO-8601 datetime. For example `2021-05-17T22:00:00+00:00`.
     * @type {Date}
     * @memberof Event
     */
    readonly availableTo?: Date;
    /**
     * 
     * @type {EventOrganizer}
     * @memberof Event
     */
    organizer?: EventOrganizer;
    /**
     * One or more URIs that represent the same [event](./models/event.json) on another API or website, not necessarily in JSON-LD format.
     * 
     * Added automatically by UiTdatabank based on info from other systems.
     * 
     * For example `http://www.uitinvlaanderen.be/agenda/e/test-event/85b04295-479c-40f5-b3dd-469dfb4387b3`.
     * @type {Set<string>}
     * @memberof Event
     */
    readonly sameAs?: Set<string>;
    /**
     * 
     * @type {EventWorkflowStatus}
     * @memberof Event
     */
    workflowStatus?: EventWorkflowStatus;
    /**
     * 
     * @type {EventAudience}
     * @memberof Event
     */
    audience?: EventAudience;
    /**
     * List of languages that the [event](./models/event.json) is available in. (Not all localizable properties may contain every language though)
     * 
     * Added automatically by UiTdatabank based on the languages present in localized properties.
     * 
     * See also [completedLanguages](./models/event-completedLanguages.json).
     * @type {Array<EventLanguagesEnum>}
     * @memberof Event
     */
    readonly languages?: Array<EventLanguagesEnum>;
    /**
     * List of languages that _every_ localizable property on the [event](./models/event.json) is available in.
     * 
     * Added automatically by UiTdatabank based on the languages present in localized properties.
     * 
     * See also [languages](./models/event-languages.json).
     * @type {Array<EventCompletedLanguagesEnum>}
     * @memberof Event
     */
    readonly completedLanguages?: Array<EventCompletedLanguagesEnum>;
    /**
     * Indicates the minimum and maximum age to attend the [event](./models/event.json). For example `6-12`, `0-12`, `-12`, or `6-`.
     * @type {string}
     * @memberof Event
     */
    typicalAgeRange?: string;
    /**
     * 
     * @type {EventBirthdateRange}
     * @memberof Event
     */
    birthdateRange?: EventBirthdateRange;
    /**
     * 
     * @type {EventDescription}
     * @memberof Event
     */
    description?: EventDescription;
    /**
     * A list of tariffs available for tickets/reservations to attend the [event](./models/event.json).
     * @type {Array<EventPriceInfoInner>}
     * @memberof Event
     */
    priceInfo?: Array<EventPriceInfoInner>;
    /**
     * 
     * @type {EventContactPoint}
     * @memberof Event
     */
    contactPoint?: EventContactPoint;
    /**
     * 
     * @type {EventBookingInfo}
     * @memberof Event
     */
    bookingInfo?: EventBookingInfo;
    /**
     * A list of media objects related to the [event](./models/event.json), in reality always images but called mediaObject for backward compatibility. The main image of the event will always be set to the first image in this list when creating/updating an event with multiple images.
     * @type {Array<Image>}
     * @memberof Event
     */
    mediaObject?: Array<Image>;
    /**
     * URL to the main image of the [event](./models/event.json). Will be automatically be set by UiTdatabank to the URL of the first image in `mediaObject`.
     * @type {string}
     * @memberof Event
     */
    readonly image?: string;
    /**
     * Describes an array of video objects that are linked to an event.
     * @type {Array<EventVideosInner>}
     * @memberof Event
     */
    videos?: Array<EventVideosInner>;
    /**
     * One or more labels that categorize the [event](./models/event.json). Compared to [terms](./models/event-terms.json), labels do not have a defined set of possible values or a hierarchy.
     * 
     * Labels are allowed to be visible for end users on publication channels.
     * 
     * See [hiddenLabels](./models/event-hiddenLabels.json) for labels that should not be visible on publication channels.
     * @type {Set<string>}
     * @memberof Event
     */
    labels?: Set<string>;
    /**
     * Same as [labels](./models/event-labels.json), but for labels that should not be visible for end users on publication channels and should instead only be used for filtering or other processing.
     * @type {Set<string>}
     * @memberof Event
     */
    hiddenLabels?: Set<string>;
    /**
     * 
     * @type {EventProduction}
     * @memberof Event
     */
    production?: EventProduction;
    /**
     * 
     * @type {EventBookingAvailability}
     * @memberof Event
     */
    bookingAvailability?: EventBookingAvailability;
    /**
     * Date formatted as an ISO-8601 datetime, added automatically by UiTdatabank based on the date & time the [event](./models/event.json) was created at.
     * 
     * For example `2021-05-17T22:00:00+00:00`.
     * @type {Date}
     * @memberof Event
     */
    readonly created?: Date;
    /**
     * Date formatted as an ISO-8601 datetime, added automatically by UiTdatabank based on the date & time the [event](./models/event.json) was last modified.
     * 
     * For example `2021-05-17T22:00:00+00:00`.
     * @type {Date}
     * @memberof Event
     */
    readonly modified?: Date;
    /**
     * The unique identifier of the creator of the [event](./models/event.json). Usually a UUID, but can historally be an e-mail address.
     * 
     * Added automatically by UiTdatabank based on the authentication credentials used to create the event.
     * @type {string}
     * @memberof Event
     */
    readonly creator?: string;
    /**
     * List of contributors on an [event](./models/event.json). Only included if you request the event with an authenticated user who has the "Aanbod bewerken" permission on the event. [Here is a detailed guide](./entry-api/shared/contributors) with more information.
     * @type {Set<string>}
     * @memberof Event
     */
    readonly contributors?: Set<string>;
    /**
     * The completeness score is a number between 0 and 100 that indicates how complete the information of an event, place or organizer is.
     * @type {number}
     * @memberof Event
     */
    readonly completeness?: number;
    /**
     * 
     * @type {EventCalendarSummary}
     * @memberof Event
     */
    calendarSummary?: EventCalendarSummary;
    /**
     * A list of several FAQ items in various languages
     * @type {Array<Faq>}
     * @memberof Event
     */
    faqs?: Array<Faq>;
    /**
     * 
     * @type {EventDeparturePlaces}
     * @memberof Event
     */
    departurePlaces?: EventDeparturePlaces;
}


/**
 * @export
 */
export const EventLanguagesEnum = {
    Nl: 'nl',
    Fr: 'fr',
    De: 'de',
    En: 'en'
} as const;
export type EventLanguagesEnum = typeof EventLanguagesEnum[keyof typeof EventLanguagesEnum];

/**
 * @export
 */
export const EventCompletedLanguagesEnum = {
    Nl: 'nl',
    Fr: 'fr',
    De: 'de',
    En: 'en'
} as const;
export type EventCompletedLanguagesEnum = typeof EventCompletedLanguagesEnum[keyof typeof EventCompletedLanguagesEnum];


/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
    if (!('mainLanguage' in value) || value['mainLanguage'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('terms' in value) || value['terms'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('calendarType' in value) || value['calendarType'] === undefined) return false;
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['@id'] == null ? undefined : json['@id'],
        'mainLanguage': EventMainLanguageFromJSON(json['mainLanguage']),
        'name': EventNameFromJSON(json['name']),
        'terms': (new Set((json['terms'] as Array<any>).map(EventTermsInnerFromJSON))),
        'location': EventLocationFromJSON(json['location']),
        'calendarType': EventCalendarTypeFromJSON(json['calendarType']),
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'attendanceMode': json['attendanceMode'] == null ? undefined : EventAttendanceModeFromJSON(json['attendanceMode']),
        'onlineUrl': json['onlineUrl'] == null ? undefined : json['onlineUrl'],
        'status': json['status'] == null ? undefined : EventStatusFromJSON(json['status']),
        'subEvent': json['subEvent'] == null ? undefined : ((json['subEvent'] as Array<any>).map(EventSubEventInnerFromJSON)),
        'openingHours': json['openingHours'] == null ? undefined : EventOpeningHoursFromJSON(json['openingHours']),
        'openingHoursClosedDays': json['openingHoursClosedDays'] == null ? undefined : ((json['openingHoursClosedDays'] as Array<any>).map(CommonOpeningHoursClosedDaysInnerFromJSON)),
        'openingHoursAdjustedDays': json['openingHoursAdjustedDays'] == null ? undefined : EventOpeningHoursAdjustedDaysFromJSON(json['openingHoursAdjustedDays']),
        'availableFrom': json['availableFrom'] == null ? undefined : (new Date(json['availableFrom'])),
        'availableTo': json['availableTo'] == null ? undefined : (new Date(json['availableTo'])),
        'organizer': json['organizer'] == null ? undefined : EventOrganizerFromJSON(json['organizer']),
        'sameAs': json['sameAs'] == null ? undefined : new Set(json['sameAs']),
        'workflowStatus': json['workflowStatus'] == null ? undefined : EventWorkflowStatusFromJSON(json['workflowStatus']),
        'audience': json['audience'] == null ? undefined : EventAudienceFromJSON(json['audience']),
        'languages': json['languages'] == null ? undefined : json['languages'],
        'completedLanguages': json['completedLanguages'] == null ? undefined : json['completedLanguages'],
        'typicalAgeRange': json['typicalAgeRange'] == null ? undefined : json['typicalAgeRange'],
        'birthdateRange': json['birthdateRange'] == null ? undefined : EventBirthdateRangeFromJSON(json['birthdateRange']),
        'description': json['description'] == null ? undefined : EventDescriptionFromJSON(json['description']),
        'priceInfo': json['priceInfo'] == null ? undefined : ((json['priceInfo'] as Array<any>).map(EventPriceInfoInnerFromJSON)),
        'contactPoint': json['contactPoint'] == null ? undefined : EventContactPointFromJSON(json['contactPoint']),
        'bookingInfo': json['bookingInfo'] == null ? undefined : EventBookingInfoFromJSON(json['bookingInfo']),
        'mediaObject': json['mediaObject'] == null ? undefined : ((json['mediaObject'] as Array<any>).map(ImageFromJSON)),
        'image': json['image'] == null ? undefined : json['image'],
        'videos': json['videos'] == null ? undefined : ((json['videos'] as Array<any>).map(EventVideosInnerFromJSON)),
        'labels': json['labels'] == null ? undefined : new Set(json['labels']),
        'hiddenLabels': json['hiddenLabels'] == null ? undefined : new Set(json['hiddenLabels']),
        'production': json['production'] == null ? undefined : EventProductionFromJSON(json['production']),
        'bookingAvailability': json['bookingAvailability'] == null ? undefined : EventBookingAvailabilityFromJSON(json['bookingAvailability']),
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'modified': json['modified'] == null ? undefined : (new Date(json['modified'])),
        'creator': json['creator'] == null ? undefined : json['creator'],
        'contributors': json['contributors'] == null ? undefined : new Set(json['contributors']),
        'completeness': json['completeness'] == null ? undefined : json['completeness'],
        'calendarSummary': json['calendarSummary'] == null ? undefined : EventCalendarSummaryFromJSON(json['calendarSummary']),
        'faqs': json['faqs'] == null ? undefined : ((json['faqs'] as Array<any>).map(FaqFromJSON)),
        'departurePlaces': json['departurePlaces'] == null ? undefined : EventDeparturePlacesFromJSON(json['departurePlaces']),
    };
}

export function EventToJSON(json: any): Event {
    return EventToJSONTyped(json, false);
}

export function EventToJSONTyped(value?: Omit<Event, 'availableTo'|'sameAs'|'languages'|'completedLanguages'|'image'|'created'|'modified'|'creator'|'contributors'|'completeness'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@id': value['id'],
        'mainLanguage': EventMainLanguageToJSON(value['mainLanguage']),
        'name': EventNameToJSON(value['name']),
        'terms': (Array.from(value['terms'] as Set<any>).map(EventTermsInnerToJSON)),
        'location': EventLocationToJSON(value['location']),
        'calendarType': EventCalendarTypeToJSON(value['calendarType']),
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'attendanceMode': EventAttendanceModeToJSON(value['attendanceMode']),
        'onlineUrl': value['onlineUrl'],
        'status': EventStatusToJSON(value['status']),
        'subEvent': value['subEvent'] == null ? undefined : ((value['subEvent'] as Array<any>).map(EventSubEventInnerToJSON)),
        'openingHours': EventOpeningHoursToJSON(value['openingHours']),
        'openingHoursClosedDays': value['openingHoursClosedDays'] == null ? undefined : ((value['openingHoursClosedDays'] as Array<any>).map(CommonOpeningHoursClosedDaysInnerToJSON)),
        'openingHoursAdjustedDays': EventOpeningHoursAdjustedDaysToJSON(value['openingHoursAdjustedDays']),
        'availableFrom': value['availableFrom'] == null ? value['availableFrom'] : value['availableFrom'].toISOString(),
        'organizer': EventOrganizerToJSON(value['organizer']),
        'workflowStatus': EventWorkflowStatusToJSON(value['workflowStatus']),
        'audience': EventAudienceToJSON(value['audience']),
        'typicalAgeRange': value['typicalAgeRange'],
        'birthdateRange': EventBirthdateRangeToJSON(value['birthdateRange']),
        'description': EventDescriptionToJSON(value['description']),
        'priceInfo': value['priceInfo'] == null ? undefined : ((value['priceInfo'] as Array<any>).map(EventPriceInfoInnerToJSON)),
        'contactPoint': EventContactPointToJSON(value['contactPoint']),
        'bookingInfo': EventBookingInfoToJSON(value['bookingInfo']),
        'mediaObject': value['mediaObject'] == null ? undefined : ((value['mediaObject'] as Array<any>).map(ImageToJSON)),
        'videos': value['videos'] == null ? undefined : ((value['videos'] as Array<any>).map(EventVideosInnerToJSON)),
        'labels': value['labels'] == null ? undefined : Array.from(value['labels'] as Set<any>),
        'hiddenLabels': value['hiddenLabels'] == null ? undefined : Array.from(value['hiddenLabels'] as Set<any>),
        'production': EventProductionToJSON(value['production']),
        'bookingAvailability': EventBookingAvailabilityToJSON(value['bookingAvailability']),
        'calendarSummary': EventCalendarSummaryToJSON(value['calendarSummary']),
        'faqs': value['faqs'] == null ? undefined : ((value['faqs'] as Array<any>).map(FaqToJSON)),
        'departurePlaces': EventDeparturePlacesToJSON(value['departurePlaces']),
    };
}

