/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * With UiTdatabank\'s Search API you can search events, places and organizers.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The Dutch translation of the FAQ item.
 * @export
 * @interface FaqNl
 */
export interface FaqNl {
    /**
     * The question in Dutch.
     * @type {string}
     * @memberof FaqNl
     */
    question: string;
    /**
     * The answer in Dutch.
     * @type {string}
     * @memberof FaqNl
     */
    answer: string;
}

/**
 * Check if a given object implements the FaqNl interface.
 */
export function instanceOfFaqNl(value: object): value is FaqNl {
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('answer' in value) || value['answer'] === undefined) return false;
    return true;
}

export function FaqNlFromJSON(json: any): FaqNl {
    return FaqNlFromJSONTyped(json, false);
}

export function FaqNlFromJSONTyped(json: any, ignoreDiscriminator: boolean): FaqNl {
    if (json == null) {
        return json;
    }
    return {
        
        'question': json['question'],
        'answer': json['answer'],
    };
}

export function FaqNlToJSON(json: any): FaqNl {
    return FaqNlToJSONTyped(json, false);
}

export function FaqNlToJSONTyped(value?: FaqNl | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'question': value['question'],
        'answer': value['answer'],
    };
}

