/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * With UiTdatabank\'s Search API you can search events, places and organizers.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEvents200ResponseFacet } from './GetEvents200ResponseFacet';
import {
    GetEvents200ResponseFacetFromJSON,
    GetEvents200ResponseFacetFromJSONTyped,
    GetEvents200ResponseFacetToJSON,
    GetEvents200ResponseFacetToJSONTyped,
} from './GetEvents200ResponseFacet';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';

/**
 * 
 * @export
 * @interface GetEvents200Response
 */
export interface GetEvents200Response {
    /**
     * The amount of results that is being returned per page.
     * @type {number}
     * @memberof GetEvents200Response
     */
    itemsPerPage: number;
    /**
     * Total amount of results for the given query parameters.
     * @type {number}
     * @memberof GetEvents200Response
     */
    totalItems: number;
    /**
     * Search results (paginated). Note that the complete search results details will only be returned if `?embed=true` is used. Otherwise only the `@id` will be returned.
     * @type {Array<Event>}
     * @memberof GetEvents200Response
     */
    member: Array<Event>;
    /**
     * 
     * @type {GetEvents200ResponseFacet}
     * @memberof GetEvents200Response
     */
    facet?: GetEvents200ResponseFacet;
}

/**
 * Check if a given object implements the GetEvents200Response interface.
 */
export function instanceOfGetEvents200Response(value: object): value is GetEvents200Response {
    if (!('itemsPerPage' in value) || value['itemsPerPage'] === undefined) return false;
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    if (!('member' in value) || value['member'] === undefined) return false;
    return true;
}

export function GetEvents200ResponseFromJSON(json: any): GetEvents200Response {
    return GetEvents200ResponseFromJSONTyped(json, false);
}

export function GetEvents200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEvents200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'itemsPerPage': json['itemsPerPage'],
        'totalItems': json['totalItems'],
        'member': ((json['member'] as Array<any>).map(EventFromJSON)),
        'facet': json['facet'] == null ? undefined : GetEvents200ResponseFacetFromJSON(json['facet']),
    };
}

export function GetEvents200ResponseToJSON(json: any): GetEvents200Response {
    return GetEvents200ResponseToJSONTyped(json, false);
}

export function GetEvents200ResponseToJSONTyped(value?: GetEvents200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemsPerPage': value['itemsPerPage'],
        'totalItems': value['totalItems'],
        'member': ((value['member'] as Array<any>).map(EventToJSON)),
        'facet': GetEvents200ResponseFacetToJSON(value['facet']),
    };
}

