/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * With UiTdatabank\'s Search API you can search events, places and organizers.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEvents200ResponseFacet } from './GetEvents200ResponseFacet';
import {
    GetEvents200ResponseFacetFromJSON,
    GetEvents200ResponseFacetFromJSONTyped,
    GetEvents200ResponseFacetToJSON,
    GetEvents200ResponseFacetToJSONTyped,
} from './GetEvents200ResponseFacet';
import type { Place } from './Place';
import {
    PlaceFromJSON,
    PlaceFromJSONTyped,
    PlaceToJSON,
    PlaceToJSONTyped,
} from './Place';

/**
 * 
 * @export
 * @interface GetPlaces200Response
 */
export interface GetPlaces200Response {
    /**
     * The amount of results that is being returned per page.
     * @type {number}
     * @memberof GetPlaces200Response
     */
    itemsPerPage: number;
    /**
     * Total amount of results for the given query parameters.
     * @type {number}
     * @memberof GetPlaces200Response
     */
    totalItems: number;
    /**
     * Search results (paginated). Note that the complete search results details will only be returned if `?embed=true` is used. Otherwise only the `@id` will be returned.
     * @type {Array<Place>}
     * @memberof GetPlaces200Response
     */
    member: Array<Place>;
    /**
     * 
     * @type {GetEvents200ResponseFacet}
     * @memberof GetPlaces200Response
     */
    facet?: GetEvents200ResponseFacet;
}

/**
 * Check if a given object implements the GetPlaces200Response interface.
 */
export function instanceOfGetPlaces200Response(value: object): value is GetPlaces200Response {
    if (!('itemsPerPage' in value) || value['itemsPerPage'] === undefined) return false;
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    if (!('member' in value) || value['member'] === undefined) return false;
    return true;
}

export function GetPlaces200ResponseFromJSON(json: any): GetPlaces200Response {
    return GetPlaces200ResponseFromJSONTyped(json, false);
}

export function GetPlaces200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlaces200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'itemsPerPage': json['itemsPerPage'],
        'totalItems': json['totalItems'],
        'member': ((json['member'] as Array<any>).map(PlaceFromJSON)),
        'facet': json['facet'] == null ? undefined : GetEvents200ResponseFacetFromJSON(json['facet']),
    };
}

export function GetPlaces200ResponseToJSON(json: any): GetPlaces200Response {
    return GetPlaces200ResponseToJSONTyped(json, false);
}

export function GetPlaces200ResponseToJSONTyped(value?: GetPlaces200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemsPerPage': value['itemsPerPage'],
        'totalItems': value['totalItems'],
        'member': ((value['member'] as Array<any>).map(PlaceToJSON)),
        'facet': GetEvents200ResponseFacetToJSON(value['facet']),
    };
}

