/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * With UiTdatabank\'s Search API you can search events, places and organizers.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Textual represenation of the date of the event / place
 * @export
 * @interface OfferCalendarSummaryDetailText
 */
export interface OfferCalendarSummaryDetailText {
    /**
     * Extra small date, example "28 nov"
     * @type {string}
     * @memberof OfferCalendarSummaryDetailText
     */
    xs?: string;
    /**
     * Small date, example: Tot 28 nov 2022
     * @type {string}
     * @memberof OfferCalendarSummaryDetailText
     */
    sm?: string;
    /**
     * Medium date, example: Ma 28 november 2022 (uitverkocht)
     * @type {string}
     * @memberof OfferCalendarSummaryDetailText
     */
    md?: string;
    /**
     * Large date, example: Maandag 28 november 2022 van 20:00 tot 21:00 (Volzet of uitverkocht)
     * @type {string}
     * @memberof OfferCalendarSummaryDetailText
     */
    lg?: string;
}

/**
 * Check if a given object implements the OfferCalendarSummaryDetailText interface.
 */
export function instanceOfOfferCalendarSummaryDetailText(value: object): value is OfferCalendarSummaryDetailText {
    return true;
}

export function OfferCalendarSummaryDetailTextFromJSON(json: any): OfferCalendarSummaryDetailText {
    return OfferCalendarSummaryDetailTextFromJSONTyped(json, false);
}

export function OfferCalendarSummaryDetailTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfferCalendarSummaryDetailText {
    if (json == null) {
        return json;
    }
    return {
        
        'xs': json['xs'] == null ? undefined : json['xs'],
        'sm': json['sm'] == null ? undefined : json['sm'],
        'md': json['md'] == null ? undefined : json['md'],
        'lg': json['lg'] == null ? undefined : json['lg'],
    };
}

export function OfferCalendarSummaryDetailTextToJSON(json: any): OfferCalendarSummaryDetailText {
    return OfferCalendarSummaryDetailTextToJSONTyped(json, false);
}

export function OfferCalendarSummaryDetailTextToJSONTyped(value?: OfferCalendarSummaryDetailText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'xs': value['xs'],
        'sm': value['sm'],
        'md': value['md'],
        'lg': value['lg'],
    };
}

