/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Contact info containing one or more phone numbers, email addresses and/or website URLs.
 * @export
 * @interface OrganizerContactPointPut
 */
export interface OrganizerContactPointPut {
    /**
     * List of phone numbers for contact purposes (can be empty)
     * @type {Array<string>}
     * @memberof OrganizerContactPointPut
     */
    phone?: Array<string>;
    /**
     * List of email addresses for contact purposes (can be empty)
     * @type {Array<string>}
     * @memberof OrganizerContactPointPut
     */
    email?: Array<string>;
    /**
     * List of URLs for contact purposes (can be empty)
     * @type {Array<string>}
     * @memberof OrganizerContactPointPut
     */
    url?: Array<string>;
}

/**
 * Check if a given object implements the OrganizerContactPointPut interface.
 */
export function instanceOfOrganizerContactPointPut(value: object): value is OrganizerContactPointPut {
    return true;
}

export function OrganizerContactPointPutFromJSON(json: any): OrganizerContactPointPut {
    return OrganizerContactPointPutFromJSONTyped(json, false);
}

export function OrganizerContactPointPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerContactPointPut {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OrganizerContactPointPutToJSON(json: any): OrganizerContactPointPut {
    return OrganizerContactPointPutToJSONTyped(json, false);
}

export function OrganizerContactPointPutToJSONTyped(value?: OrganizerContactPointPut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
        'email': value['email'],
        'url': value['url'],
    };
}

