/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizerDescriptionPut
 */
export interface OrganizerDescriptionPut {
    /**
     * New description of the organizer, localized in a single language.
     * @type {string}
     * @memberof OrganizerDescriptionPut
     */
    description: string;
}

/**
 * Check if a given object implements the OrganizerDescriptionPut interface.
 */
export function instanceOfOrganizerDescriptionPut(value: object): value is OrganizerDescriptionPut {
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function OrganizerDescriptionPutFromJSON(json: any): OrganizerDescriptionPut {
    return OrganizerDescriptionPutFromJSONTyped(json, false);
}

export function OrganizerDescriptionPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerDescriptionPut {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
    };
}

export function OrganizerDescriptionPutToJSON(json: any): OrganizerDescriptionPut {
    return OrganizerDescriptionPutToJSONTyped(json, false);
}

export function OrganizerDescriptionPutToJSONTyped(value?: OrganizerDescriptionPut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
    };
}

