/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonAddressLocalized } from './CommonAddressLocalized';
import {
    CommonAddressLocalizedFromJSON,
    CommonAddressLocalizedFromJSONTyped,
    CommonAddressLocalizedToJSON,
    CommonAddressLocalizedToJSONTyped,
} from './CommonAddressLocalized';
import type { OrganizerContactInner } from './OrganizerContactInner';
import {
    OrganizerContactInnerFromJSON,
    OrganizerContactInnerFromJSONTyped,
    OrganizerContactInnerToJSON,
    OrganizerContactInnerToJSONTyped,
} from './OrganizerContactInner';
import type { OrganizerMainLanguage } from './OrganizerMainLanguage';
import {
    OrganizerMainLanguageFromJSON,
    OrganizerMainLanguageFromJSONTyped,
    OrganizerMainLanguageToJSON,
    OrganizerMainLanguageToJSONTyped,
} from './OrganizerMainLanguage';

/**
 * 
 * @export
 * @interface OrganizerPostDeprecated
 */
export interface OrganizerPostDeprecated {
    /**
     * A unique URI that acts as globally unique ID for the [organizer](./models/organizer.json). Based on [JSON-LD node identifiers](https://www.w3.org/TR/json-ld/#node-identifiers).
     * @type {string}
     * @memberof OrganizerPostDeprecated
     */
    id?: string;
    /**
     * 
     * @type {OrganizerMainLanguage}
     * @memberof OrganizerPostDeprecated
     */
    mainLanguage: OrganizerMainLanguage;
    /**
     * The unique website of the organizer.
     * @type {string}
     * @memberof OrganizerPostDeprecated
     */
    website: string;
    /**
     * The name of the organizer, localized in the language specified in the mainLanguage property.
     * @type {string}
     * @memberof OrganizerPostDeprecated
     */
    name: string;
    /**
     * The address of the organizer, localized in the language specified in the mainLanguage property.
     * @type {CommonAddressLocalized}
     * @memberof OrganizerPostDeprecated
     */
    address?: CommonAddressLocalized;
    /**
     * Contact info of the [organizer](./models/organizer.json) in a legacy format, containing one or more phone numbers, email addresses and/or website URLs.
     * 
     * A type is used to categories the kind of contact information. The type can be either: url, email or phone.
     * @type {Array<OrganizerContactInner>}
     * @memberof OrganizerPostDeprecated
     */
    contact?: Array<OrganizerContactInner>;
    /**
     * One or more labels that categorize the [organizer](./models/organizer.json). Labels do not have a defined set of possible values or a hierarchy.
     * 
     * Labels are allowed to be visible for end users on publication channels.
     * 
     * Labels must match the `^(?=.{2,255}$)(?=.*\S.*\S.*)[^;]*$` pattern.
     * 
     * See [hiddenLabels](./models/organizer-hiddenLabels.json) for labels that should not be visible on publication channels.
     * @type {Array<string>}
     * @memberof OrganizerPostDeprecated
     */
    labels?: Array<string>;
    /**
     * Same as [labels](./models/organizer-labels.json), but for labels that should not be visible for end users on publication channels and should instead only be used for filtering or other processing.
     * 
     * Labels must match the `^(?=.{2,255}$)(?=.*\S.*\S.*)[^;]*$` pattern.
     * @type {Array<string>}
     * @memberof OrganizerPostDeprecated
     */
    hiddenLabels?: Array<string>;
}



/**
 * Check if a given object implements the OrganizerPostDeprecated interface.
 */
export function instanceOfOrganizerPostDeprecated(value: object): value is OrganizerPostDeprecated {
    if (!('mainLanguage' in value) || value['mainLanguage'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OrganizerPostDeprecatedFromJSON(json: any): OrganizerPostDeprecated {
    return OrganizerPostDeprecatedFromJSONTyped(json, false);
}

export function OrganizerPostDeprecatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizerPostDeprecated {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['@id'] == null ? undefined : json['@id'],
        'mainLanguage': OrganizerMainLanguageFromJSON(json['mainLanguage']),
        'website': json['website'],
        'name': json['name'],
        'address': json['address'] == null ? undefined : CommonAddressLocalizedFromJSON(json['address']),
        'contact': json['contact'] == null ? undefined : ((json['contact'] as Array<any>).map(OrganizerContactInnerFromJSON)),
        'labels': json['labels'] == null ? undefined : json['labels'],
        'hiddenLabels': json['hiddenLabels'] == null ? undefined : json['hiddenLabels'],
    };
}

export function OrganizerPostDeprecatedToJSON(json: any): OrganizerPostDeprecated {
    return OrganizerPostDeprecatedToJSONTyped(json, false);
}

export function OrganizerPostDeprecatedToJSONTyped(value?: OrganizerPostDeprecated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@id': value['id'],
        'mainLanguage': OrganizerMainLanguageToJSON(value['mainLanguage']),
        'website': value['website'],
        'name': value['name'],
        'address': CommonAddressLocalizedToJSON(value['address']),
        'contact': value['contact'] == null ? undefined : ((value['contact'] as Array<any>).map(OrganizerContactInnerToJSON)),
        'labels': value['labels'],
        'hiddenLabels': value['hiddenLabels'],
    };
}

