/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * With UiTdatabank\'s Search API you can search events, places and organizers.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonBookingAvailabilityType } from './CommonBookingAvailabilityType';
import {
    CommonBookingAvailabilityTypeFromJSON,
    CommonBookingAvailabilityTypeFromJSONTyped,
    CommonBookingAvailabilityTypeToJSON,
    CommonBookingAvailabilityTypeToJSONTyped,
} from './CommonBookingAvailabilityType';

/**
 * Indicates whether the place still has tickets or reservations available. Currently only contains a `type` which can only be `Available` for places (as opposed to events that can also have `Unavailable` when sold out), as a place can never be completely sold out forever. Can later be expanded with more detailed info.
 * @export
 * @interface PlaceBookingAvailability
 */
export interface PlaceBookingAvailability {
    /**
     * 
     * @type {CommonBookingAvailabilityType}
     * @memberof PlaceBookingAvailability
     */
    type: CommonBookingAvailabilityType;
}



/**
 * Check if a given object implements the PlaceBookingAvailability interface.
 */
export function instanceOfPlaceBookingAvailability(value: object): value is PlaceBookingAvailability {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PlaceBookingAvailabilityFromJSON(json: any): PlaceBookingAvailability {
    return PlaceBookingAvailabilityFromJSONTyped(json, false);
}

export function PlaceBookingAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceBookingAvailability {
    if (json == null) {
        return json;
    }
    return {
        
        'type': CommonBookingAvailabilityTypeFromJSON(json['type']),
    };
}

export function PlaceBookingAvailabilityToJSON(json: any): PlaceBookingAvailability {
    return PlaceBookingAvailabilityToJSONTyped(json, false);
}

export function PlaceBookingAvailabilityToJSONTyped(value?: PlaceBookingAvailability | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': CommonBookingAvailabilityTypeToJSON(value['type']),
    };
}

