/* tslint:disable */
/* eslint-disable */
/**
 * Entry API
 * With UiTdatabank\'s Entry API you can create new events, places and organizers, and add extra info to them with specific requests to add/update properties. For example there are operations to add a label, remove a label, add an image, and so on.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes the request body to update an image at a [place](./models/place.json).
 * @export
 * @interface PlaceImagePut
 */
export interface PlaceImagePut {
    /**
     * Description of the image object.
     * @type {string}
     * @memberof PlaceImagePut
     */
    description: string;
    /**
     * The copyright holder of the image.
     * @type {string}
     * @memberof PlaceImagePut
     */
    copyrightHolder: string;
}

/**
 * Check if a given object implements the PlaceImagePut interface.
 */
export function instanceOfPlaceImagePut(value: object): value is PlaceImagePut {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('copyrightHolder' in value) || value['copyrightHolder'] === undefined) return false;
    return true;
}

export function PlaceImagePutFromJSON(json: any): PlaceImagePut {
    return PlaceImagePutFromJSONTyped(json, false);
}

export function PlaceImagePutFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceImagePut {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'copyrightHolder': json['copyrightHolder'],
    };
}

export function PlaceImagePutToJSON(json: any): PlaceImagePut {
    return PlaceImagePutToJSONTyped(json, false);
}

export function PlaceImagePutToJSONTyped(value?: PlaceImagePut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'copyrightHolder': value['copyrightHolder'],
    };
}

