/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * With UiTdatabank\'s Search API you can search events, places and organizers.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Contact info of the [place](./models/place.json), containing one or more phone numbers, email addresses, and/or website URLs. [Here is a detailed guide](./entry-api/shared/booking-and-contact-info#contactpoint) with more information.
 * @export
 * @interface PlaceContactPoint
 */
export interface PlaceContactPoint {
    /**
     * List of phone numbers for contact purposes (can be empty)
     * @type {Array<string>}
     * @memberof PlaceContactPoint
     */
    phone?: Array<string>;
    /**
     * List of email addresses for contact purposes (can be empty)
     * @type {Array<string>}
     * @memberof PlaceContactPoint
     */
    email?: Array<string>;
    /**
     * List of URLs for contact purposes (can be empty)
     * @type {Array<string>}
     * @memberof PlaceContactPoint
     */
    url?: Array<string>;
}

/**
 * Check if a given object implements the PlaceContactPoint interface.
 */
export function instanceOfPlaceContactPoint(value: object): value is PlaceContactPoint {
    return true;
}

export function PlaceContactPointFromJSON(json: any): PlaceContactPoint {
    return PlaceContactPointFromJSONTyped(json, false);
}

export function PlaceContactPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceContactPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function PlaceContactPointToJSON(json: any): PlaceContactPoint {
    return PlaceContactPointToJSONTyped(json, false);
}

export function PlaceContactPointToJSONTyped(value?: PlaceContactPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
        'email': value['email'],
        'url': value['url'],
    };
}

