/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * With UiTdatabank\'s Search API you can search events, places and organizers.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status in the moderation workflow.
 * 
 * Can be one of four types:
 * 
 * - `DRAFT`: Should not be visible on publication channels yet
 * - `READY_FOR_VALIDATION`: Submitted for validation. Some publication channels may choose to show these.
 * - `APPROVED`: Approved, will be visible on all publication channels (depending on the `availableFrom` and `availableTo`). Only possible if you have moderation permissions.
 * - `REJECTED`: Rejected, will be hidden from all publication channels. Only possible if you have moderation permissions.
 * - `DELETED`: Removed and should not be visible on any publication channels.
 * @export
 */
export const PlaceWorkflowStatus = {
    Draft: 'DRAFT',
    ReadyForValidation: 'READY_FOR_VALIDATION',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Deleted: 'DELETED'
} as const;
export type PlaceWorkflowStatus = typeof PlaceWorkflowStatus[keyof typeof PlaceWorkflowStatus];


export function instanceOfPlaceWorkflowStatus(value: any): boolean {
    for (const key in PlaceWorkflowStatus) {
        if (Object.prototype.hasOwnProperty.call(PlaceWorkflowStatus, key)) {
            if (PlaceWorkflowStatus[key as keyof typeof PlaceWorkflowStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PlaceWorkflowStatusFromJSON(json: any): PlaceWorkflowStatus {
    return PlaceWorkflowStatusFromJSONTyped(json, false);
}

export function PlaceWorkflowStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceWorkflowStatus {
    return json as PlaceWorkflowStatus;
}

export function PlaceWorkflowStatusToJSON(value?: PlaceWorkflowStatus | null): any {
    return value as any;
}

export function PlaceWorkflowStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): PlaceWorkflowStatus {
    return value as PlaceWorkflowStatus;
}

