/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * With UiTdatabank\'s Search API you can search events, places and organizers.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: technical-support@publiq.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonOpeningHoursAdjustedDaysInner } from './CommonOpeningHoursAdjustedDaysInner';
import {
    CommonOpeningHoursAdjustedDaysInnerFromJSON,
    CommonOpeningHoursAdjustedDaysInnerFromJSONTyped,
    CommonOpeningHoursAdjustedDaysInnerToJSON,
    CommonOpeningHoursAdjustedDaysInnerToJSONTyped,
} from './CommonOpeningHoursAdjustedDaysInner';

/**
 * 
 * @export
 * @interface PlaceOpeningHoursAdjustedDays
 */
export interface PlaceOpeningHoursAdjustedDays {
}

/**
 * Check if a given object implements the PlaceOpeningHoursAdjustedDays interface.
 */
export function instanceOfPlaceOpeningHoursAdjustedDays(value: object): value is PlaceOpeningHoursAdjustedDays {
    return true;
}

export function PlaceOpeningHoursAdjustedDaysFromJSON(json: any): PlaceOpeningHoursAdjustedDays {
    return PlaceOpeningHoursAdjustedDaysFromJSONTyped(json, false);
}

export function PlaceOpeningHoursAdjustedDaysFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceOpeningHoursAdjustedDays {
    return json;
}

export function PlaceOpeningHoursAdjustedDaysToJSON(json: any): PlaceOpeningHoursAdjustedDays {
    return PlaceOpeningHoursAdjustedDaysToJSONTyped(json, false);
}

export function PlaceOpeningHoursAdjustedDaysToJSONTyped(value?: PlaceOpeningHoursAdjustedDays | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

